Repository NYPL/nypl-design-system, pull requests merged in 2019-11, with the labels that each got.

#39 SFR-678 prepare for publish
  package-lock.json
  src/react-components/.npmignore
  src/react-components/package-lock.json
  src/react-components/package.json
  src/react-components/src/__tests__/components/Button-test.tsx
  src/react-components/src/__tests__/setupEnzyme.ts
  src/react-components/src/components/Button/Button.tsx
  src/react-components/src/index.ts
  src/react-components/src/stories/0-Welcome.stories.tsx
  src/react-components/src/stories/1-Button.stories.tsx
  src/react-components/tsconfig.json
  src/styles/package-lock.json
  src/styles/package.json
  src/twig/package-lock.json
  src/twig/package.json
  storybook/.storybook-react/config.js
  storybook/package-lock.json
  storybook/package.json
Labels: Needs Review

#45 SFR-677 Add travis configuration
  .travis.yml
Labels: Code Review Complete, Ship It!

#40 Added Breadcrumbs
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/react-components/CHANGELOG.md
  src/react-components/package.json
  src/react-components/src/__tests__/components/Breadcrumbs-test.tsx
  src/react-components/src/__tests__/components/Button-test.tsx
  src/react-components/src/components/01-atoms/Button/Button.stories.tsx
  src/react-components/src/components/01-atoms/Button/Button.tsx
  src/react-components/src/components/02-molecules/menus/Breadcrumb/Breadcrumb.stories.tsx
  src/react-components/src/components/02-molecules/menus/Breadcrumb/Breadcrumb.tsx
  src/react-components/src/index.ts
  src/react-components/src/stories/0-Welcome.stories.tsx
  src/react-components/src/stories/1-Button.stories.tsx
  src/react-components/src/utils/bem.ts
  src/react-components/tsconfig.json
  src/styles/00-base/02-typography/01-typefaces/_typefaces.scss
  src/styles/00-base/02-typography/02-type-scale/_type-scale.scss
  src/styles/00-base/03-space/01-space-inset/_space-inset.scss
  src/styles/00-base/03-space/02-space-inline/_space-inline.scss
  src/styles/00-base/03-space/03-space-stack/_space-stack.scss
  src/styles/00-base/03-space/_space.scss
  src/styles/00-base/base/_03-mixins.scss
  src/styles/00-base/base/_04-base.scss
  src/styles/00-base/base/_pl-base.scss
  src/styles/02-molecules/menus/breadcrumbs/_breadcrumbs.scss
  src/styles/CHANGELOG.md
  src/styles/package-lock.json
  src/styles/package.json
  src/twig/CHANGELOG.md
  src/twig/__tests__/components/breadcrumb.test.js
  src/twig/__tests__/components/button.test.js
  src/twig/__tests__/twig-renderer.js
  src/twig/_patterns/01-atoms/buttons/_button.stories.js
  src/twig/_patterns/01-atoms/images/icons/_icon.twig
  src/twig/_patterns/02-molecules/menus/breadcrumbs/breadcrumbs.stories.js
  src/twig/_patterns/02-molecules/menus/breadcrumbs/breadcrumbs.twig
  src/twig/package.json
  storybook/.storybook-html/.babelrc
  storybook/.storybook-html/config.js
  storybook/.storybook-html/webpack.config.js
  storybook/.storybook-react/config.js
  storybook/package.json
Labels: Code Review Complete, Ship It!

#47 SFR-616 Modified Breadcrumbs to accept components
  package-lock.json
  package.json
  src/react-components/CHANGELOG.md
  src/react-components/package-lock.json
  src/react-components/src/__tests__/components/Breadcrumbs-test.tsx
  src/react-components/src/components/02-molecules/menus/Breadcrumb/Breadcrumb.tsx
  src/react-components/src/components/02-molecules/menus/Breadcrumbs/Breadcrumbs.stories.tsx
  src/react-components/src/components/02-molecules/menus/Breadcrumbs/Breadcrumbs.tsx
  src/react-components/src/index.ts
  src/styles/00-base/02-typography/01-typefaces/_typefaces.scss
  src/styles/package-lock.json
  src/twig/package-lock.json
  storybook/package-lock.json
Labels: Code Review Complete, Ship It!

#48 Breadcrumbs updates
  src/styles/00-base/base/_03-mixins.scss
  src/styles/02-molecules/menus/breadcrumbs/_breadcrumbs.scss
  src/styles/CHANGELOG.md
Labels: Ship It!

#49 SFR-716 Added Icons to the React Design system
  .gitignore
  package-lock.json
  package.json
  src/icons/CHANGELOG.md
  src/icons/README.md
  src/icons/dist/img/sprite/sprite.svg
  src/icons/package-lock.json
  src/icons/package.json
  src/icons/src/scripts/build-icon.js
  src/icons/src/svg/arrow-xsmall.svg
  src/icons/src/svg/arrow.svg
  src/react-components/.npmignore
  src/react-components/CHANGELOG.md
  src/react-components/package-lock.json
  src/react-components/package.json
  src/react-components/src/__tests__/components/Breadcrumbs-test.tsx
  src/react-components/src/__tests__/setupEnzyme.ts
  src/react-components/src/components/01-atoms/Images/Icons/Icon.tsx
  src/react-components/src/components/02-molecules/menus/Breadcrumbs/Breadcrumbs.stories.tsx
  src/react-components/src/components/02-molecules/menus/Breadcrumbs/Breadcrumbs.tsx
  src/react-components/tsconfig.json
  src/react-components/tsd.d.ts
  src/styles/package-lock.json
  src/twig/_patterns/01-atoms/images/icons/_icon.twig
  src/twig/_twig-components/functions/sb_attach-library.js
  src/twig/package-lock.json
  src/twig/package.json
  storybook/.storybook-html/config.js
  storybook/.storybook-html/webpack.config.js
  storybook/.storybook-react/.babelrc
  storybook/.storybook-react/webpack.config.js
  storybook/package-lock.json
Labels: Code Review Complete, Ship It!

#50 SFR 638: Links
  package-lock.json
  src/icons/package-lock.json
  src/react-components/CHANGELOG.md
  src/react-components/src/__tests__/components/IconLink-test.tsx
  src/react-components/src/__tests__/components/UnderlineLink-test.tsx
  src/react-components/src/components/01-atoms/Button/Button.stories.tsx
  src/react-components/src/components/01-atoms/Links/IconLink.stories.tsx
  src/react-components/src/components/01-atoms/Links/IconLink.tsx
  src/react-components/src/components/01-atoms/Links/Link.tsx
  src/react-components/src/components/01-atoms/Links/UnderlineLink.stories.tsx
  src/react-components/src/components/01-atoms/Links/UnderlineLink.tsx
  src/react-components/src/components/02-molecules/menus/Breadcrumbs/Breadcrumbs.stories.tsx
  src/react-components/src/index.ts
  src/react-components/src/utils/bem.ts
  src/styles/01-atoms/links/link/_link.scss
  src/styles/CHANGELOG.md
  src/styles/package-lock.json
  src/twig/_patterns/01-atoms/links/link/link.stories.js
  src/twig/_patterns/01-atoms/links/link/link.yml
  src/twig/_patterns/01-atoms/links/link/more-link.twig
  src/twig/_patterns/01-atoms/links/link/more-link.yml
  src/twig/_twig-components/functions/bem.js
  storybook/package-lock.json
Labels: Code Review Complete, Ship It!
