Repository NYPL/nypl-design-system, pull requests merged in 2020-06, with the labels that each got.

#203 Updates static script
  README.md
  package.json
Labels: Needs Review

#182 Combines Various Link Components
  src/react-components/CHANGELOG.md
  src/react-components/package.json
  src/react-components/src/__tests__/components/EditionCard-test.tsx
  src/react-components/src/__tests__/components/IconLink-test.tsx
  src/react-components/src/__tests__/components/Link-test.tsx
  src/react-components/src/__tests__/components/UnderlineLink-test.tsx
  src/react-components/src/__tests__/helpers/hoc/WithOneChild-test.tsx
  src/react-components/src/components/BasicLink/BasicLink.stories.tsx
  src/react-components/src/components/BasicLink/BasicLink.tsx
  src/react-components/src/components/Button/Button.tsx
  src/react-components/src/components/EditionCard/EditionCard.stories.tsx
  src/react-components/src/components/HelperErrorText/HelperErrorText.tsx
  src/react-components/src/components/IconLink/IconLink.stories.tsx
  src/react-components/src/components/IconLink/IconLink.tsx
  src/react-components/src/components/Icons/Icon.tsx
  src/react-components/src/components/Icons/IconTypes.tsx
  src/react-components/src/components/Link/Link.stories.tsx
  src/react-components/src/components/Link/Link.tsx
  src/react-components/src/components/Link/LinkTypes.tsx
  src/react-components/src/components/Links/Link.tsx
  src/react-components/src/components/Pagination/Pagination.tsx
  src/react-components/src/components/RNHeaderWithSearch/RNHeaderWithSearch.stories.tsx
  src/react-components/src/components/SearchPromo/SearchPromo.stories.tsx
  src/react-components/src/components/SearchResultItem/SearchResultItem.stories.tsx
  src/react-components/src/components/SectionTitle/SectionTitle.tsx
  src/react-components/src/components/UnderlineLink/UnderlineLink.stories.tsx
  src/react-components/src/components/UnderlineLink/UnderlineLink.tsx
  src/react-components/src/components/UnorderedList/UnorderedList.stories.tsx
  src/react-components/src/index.ts
  src/styles/01-atoms/_icons/_icons.scss
  src/styles/01-atoms/links/link/_link.scss
  src/styles/01-atoms/text/headings/_headings.scss
  src/styles/02-molecules/edition-card/_edition-card.scss
Labels: Approved

#208 Move tests
  src/react-components/CHANGELOG.md
  src/react-components/package.json
  src/react-components/src/__tests__/helpers/hoc/WithOneChild.test.tsx
  src/react-components/src/components/Accordion/Accordion.test.tsx
  src/react-components/src/components/BodyText/BodyText.test.tsx
  src/react-components/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/react-components/src/components/Button/Button.test.tsx
  src/react-components/src/components/Checkbox/Checkbox.test.tsx
  src/react-components/src/components/DateRangeForm/DateRangeForm.test.tsx
  src/react-components/src/components/Dropdown/Dropdown.test.tsx
  src/react-components/src/components/EditionCard/EditionCard.test.tsx
  src/react-components/src/components/FormDropdown/FormDropdown.test.tsx
  src/react-components/src/components/Heading/Heading.test.tsx
  src/react-components/src/components/HelperErrorText/HelperErrorText.test.tsx
  src/react-components/src/components/Hero/Hero.test.tsx
  src/react-components/src/components/Image/Image.test.tsx
  src/react-components/src/components/Input/Input.test.tsx
  src/react-components/src/components/Label/Label.test.tsx
  src/react-components/src/components/Modal/Modal.test.tsx
  src/react-components/src/components/Pagination/Pagination.test.tsx
  src/react-components/src/components/RNHeaderWithSearch/RNHeaderWithSearch.test.tsx
  src/react-components/src/components/SearchBar/SearchBar.Test.tsx
  src/react-components/src/components/SearchResultItem/SearchResultItem.test.tsx
  src/react-components/src/components/SectionTitle/SectionTitle.test.tsx
  src/react-components/src/components/TextField/TextField.test.tsx
  src/react-components/src/components/UnorderedList/UnorderedList.test.tsx
Labels: Approved

#209 Move link test
  src/react-components/src/components/Link/Link.test.tsx
Labels: Needs Review

#210 Exports SearchBar
  src/react-components/src/index.ts
Labels: Needs Review

#216 Fixes last button story
  src/react-components/src/components/Button/Button.stories.tsx
Labels: Approved

#226 Closes #219: Makes ids optional
  src/components/Accordion/Accordion.tsx
  src/components/BodyText/BodyText.tsx
  src/components/Button/Button.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/EditionCard/EditionCard.tsx
  src/components/FormDropdown/FormDropdown.tsx
  src/components/Heading/Heading.tsx
  src/components/Input/Input.tsx
  src/components/Label/Label.tsx
  src/components/RNHeaderWithSearch/RNHeaderWithSearch.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchPromo/SearchPromo.tsx
  src/components/SearchResultItem/SearchResultItem.tsx
  src/components/SectionTitle/SectionTitle.tsx
  src/components/TextField/TextField.tsx
  src/components/UnorderedList/UnorderedList.tsx
Labels: Approved, Needs Review

#225 SFR-940 Bugfixes for DRBB integration
  CHANGELOG.md
  src/components/Button/Button.stories.tsx
  src/components/Hero/_Hero.scss
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.test.tsx
  src/components/Link/Link.tsx
  src/index.ts
Labels: Approved

#231 README Updates
  README.md
  screenshot.png
Labels: Needs Review

#230 Card
  CHANGELOG.md
  icons/svg/headset.svg
  package.json
  src/components/Button/_Button.scss
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.test.tsx
  src/components/Card/Card.tsx
  src/components/Card/_Card.scss
  src/components/EditionCard/EditionCard.stories.tsx
  src/components/EditionCard/EditionCard.test.tsx
  src/components/EditionCard/EditionCard.tsx
  src/components/EditionCard/_EditionCard.scss
  src/components/Heading/_Heading.scss
  src/components/Icons/Icon.tsx
  src/components/Icons/_Icons.scss
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.tsx
  src/components/SearchResultItem/SearchResultItem.stories.tsx
  src/components/SearchResultItem/SearchResultItem.test.tsx
  src/components/SearchResultItem/SearchResultItem.tsx
  src/components/UnorderedList/UnorderedList.stories.tsx
  src/index.ts
  src/styles.scss
  src/styles/02-typography/_type-scale.scss
Labels: Needs Review

#239 Fixes #173: Removes ResearchNow Section Title
  CHANGELOG.md
  src/components/RNHeaderWithSearch/RNHeaderWithSearch.stories.tsx
  src/components/RNHeaderWithSearch/RNHeaderWithSearch.test.tsx
  src/components/RNHeaderWithSearch/RNHeaderWithSearch.tsx
  src/components/RNHeaderWithSearch/_RNHeaderWithSearch.scss
  src/components/RNSectionTitle/RNSectionTitle.stories.tsx
  src/components/RNSectionTitle/RNSectionTitle.tsx
  src/components/RNSectionTitle/_RNSectionTitle.scss
  src/styles.scss
Labels: Needs Review

#237 ReactRouter.Link Story
  package-lock.json
  package.json
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.test.tsx
Labels: Needs Review

#242 add prepare script
  package.json
Labels: Approved

#244 add missing dep
  package-lock.json
  package.json
Labels: Approved

#245 CI/CD
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  .travis.yml
  package.json
Labels: Approved

#248 Closes #246: Update link to new hex value
  CHANGELOG.md
  src/styles/01-colors/_color-vars.scss
Labels: Approved

#250 Release 0.6.0
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/styles/01-colors/_color-vars.scss
Labels: Needs Review

#251 release workflow
  .github/workflows/release.yml
Labels: Approved

#233 Fixes #204: Adds content bottom to Template stories
  src/components/Template/Template.stories.tsx
Labels: Needs Review

#234 Fixes #197: Deprecates certain header stories
  CHANGELOG.md
  src/components/Heading/Heading.stories.tsx
  src/components/Heading/_Heading.scss
Labels: Needs Review

#253 Select API Changes
  CHANGELOG.md
  docs/docs.md
  src/components/Button/_Button.scss
  src/components/Checkbox/Checkbox.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/_Dropdown.scss
  src/components/FormDropdown/FormDropdown.stories.tsx
  src/components/FormDropdown/FormDropdown.test.tsx
  src/components/FormDropdown/FormDropdown.tsx
  src/components/FormDropdown/_FormDropdown.scss
  src/components/HelperErrorText/HelperErrorText.test.tsx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/HelperErrorText/_HelperErrorText.scss
  src/components/Input/Input.tsx
  src/components/Input/_Input.scss
  src/components/Label/Label.stories.tsx
  src/components/Label/Label.test.tsx
  src/components/Label/Label.tsx
  src/components/Label/_Label.scss
  src/components/Link/_Link.scss
  src/components/Pagination/Pagination.test.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/_Pagination.scss
  src/components/RNHeaderWithSearch/RNHeaderWithSearch.tsx
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/_SearchBar.scss
  src/components/SearchPromo/SearchPromo.stories.tsx
  src/components/SearchPromo/SearchPromo.tsx
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Select/_Select.scss
  src/components/TextField/_Textfield.scss
  src/index.ts
  src/styles.scss
  src/styles/01-colors/_colors-used.scss
Labels: Needs Review
