Repository NYPL/nypl-design-system, pull requests merged in 2021-07, with the labels that each got.

#571 DSD-138: link mdx story
  CHANGELOG.md
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.tsx
Labels: Ship It

#541 DSD-165 added new icons and enabled color selection
  CHANGELOG.md
  icons/svg/brooklyn.svg
  icons/svg/error_filled.svg
  icons/svg/error_outline.svg
  icons/svg/lpa_negative.svg
  icons/svg/lpa_positive.svg
  icons/svg/nypl_circle_negative.svg
  icons/svg/nypl_circle_positive.svg
  icons/svg/nypl_full_lock_up.svg
  icons/svg/nypl_full_lock_up_negative.svg
  icons/svg/nypl_no_lion_negative.svg
  icons/svg/nypl_no_lion_positive.svg
  icons/svg/queens_long.svg
  icons/svg/queens_stacked.svg
  icons/svg/schomburg_circle.svg
  icons/svg/schomburg_positive.svg
  icons/svg/simplye_black.svg
  icons/svg/simplye_color.svg
  icons/svg/snfl_negative.svg
  icons/svg/snfl_positive.svg
  icons/svg/speaker_notes.svg
  package-lock.json
  package.json
  src/__tests__/setupEnzyme.ts
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/Icon.stories.tsx
  src/components/Icons/Icon.test.tsx
  src/components/Icons/Icon.tsx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/IconTypes.tsx
  src/components/Icons/Svgs.tsx
  src/components/Icons/_Icons.scss
  src/styles/01-colors/_colors-brand.scss
  tsconfig.json
  tsd.d.ts
  webpack.config.js
Labels: Ship It

#589 DSD-332: iconography style guide
  CHANGELOG.md
  package-lock.json
  src/components/Iconography/Iconography.stories.mdx
  src/utils/componentCategories.ts
Labels: Needs Review

#595 DSD-353: HeadingDisplaySizes enum
  CHANGELOG.md
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.test.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/HeadingDisplaySizes.tsx
  src/components/Typography/Typography.stories.mdx
  src/index.ts
Labels: Ship It

#596 DSD-303: Minor Story documentation update for the List component
  CHANGELOG.md
  package-lock.json
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.stories.tsx
  src/components/List/List.stories.mdx
  src/components/List/List.stories.tsx
  src/components/List/List.tsx
Labels: Ship It

#548 DSD-152: Notification
  CHANGELOG.md
  icons/svg/speaker_notes.svg
  package-lock.json
  package.json
  src/components/Notification/Notification.stories.mdx
  src/components/Notification/Notification.test.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/NotificationTypes.tsx
  src/components/Notification/_Notification.scss
  src/index.ts
  src/styles.scss
  webpack.config.js
Labels: Ship It

#598 DSD-368: button padding
  CHANGELOG.md
  package-lock.json
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/_Button.scss
Labels: Needs Review

#597 DSD-361: List listItems data prop
  src/components/List/List.stories.mdx
  src/components/List/List.stories.tsx
  src/components/List/List.test.tsx
  src/components/List/List.tsx
Labels: Ship It

#593 DSD-352: Style Guide Buttons
  CHANGELOG.md
  package-lock.json
  src/components/StyleGuide/Buttons.stories.mdx
  src/utils/componentCategories.ts
Labels: Needs Review

#601 Changelog update for the List component
  CHANGELOG.md
Labels: Ship It

#600 DSD-244: Adding textarea element to the TextInput component
  CHANGELOG.md
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/TextInputTypes.tsx
  src/components/TextInput/_TextInput.scss
Labels: Ship It

#578 DSD-322: form component
  CHANGELOG.md
  package-lock.json
  src/components/Form/Form.stories.mdx
  src/components/Form/Form.test.tsx
  src/components/Form/Form.tsx
  src/components/Form/_Form.scss
  src/index.ts
  src/styles.scss
Labels: Ship It

#606 DSD-375: consolidated Style Guide stories
  src/components/StyleGuide/Bidirectionality.stories.mdx
  src/components/StyleGuide/Breakpoints.stories.mdx
  src/components/StyleGuide/Colors.stories.tsx
  src/components/StyleGuide/Iconography.stories.mdx
  src/components/StyleGuide/Spacing.stories.tsx
  src/components/StyleGuide/Typography.stories.mdx
  src/components/StyleGuide/UIDocCard.tsx
  src/utils/componentCategories.ts
Labels: Ship It, no-changelog

#605 DSD-374: TextInput label text
  CHANGELOG.md
  src/components/TextInput/_TextInput.scss
Labels: Ship It

#602 DSD-170: Fixing and updating the documentation for the Pagination component
  CHANGELOG.md
  src/components/Pagination/Pagination.stories.mdx
  src/components/Pagination/Pagination.stories.tsx
  src/components/Pagination/Pagination.tsx
Labels: Ship It

#603 DSD-45: Documentation updates to the readme, pull request template, and the contributing files
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE
  .gitignore
  CHANGELOG.md
  README.md
  SECURITY.md
Labels: Ship It

#607 DSD-374: component versioning details
  src/components/TextInput/TextInput.stories.mdx
Labels: Ship It, no-changelog

#599 DSD-366: dynamic Skeleton Loader
  CHANGELOG.md
  package-lock.json
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.tsx
  src/components/SkeletonLoader/SkeletonLoader.test.tsx
  src/components/SkeletonLoader/SkeletonLoader.tsx
  src/components/SkeletonLoader/SkeletonLoaderTypes.tsx
  src/components/SkeletonLoader/_SkeletonLoader.scss
Labels: Needs Review

#604 DSD-363: video player
  CHANGELOG.md
  package-lock.json
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/components/VideoPlayer/VideoPlayer.test.tsx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/components/VideoPlayer/VideoPlayerTypes.tsx
  src/components/VideoPlayer/_VideoPlayer.scss
  src/index.ts
  src/styles.scss
Labels: Needs Review

#608 prep for release v0.23.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs Review

#614 DSD-387: SkeletonLoader enums
  CHANGELOG.md
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/index.ts
Labels: Ship It

#613 DSD-356: Including more information about all the Storybook documentation instances
  CHANGELOG.md
  README.md
Labels: Ship It

#617 DSD-85: Adding Typescript documentation guideline file.
  CHANGELOG.md
  README.md
  TYPESCRIPT.md
Labels: Ship It

#618 DSD-328: Style Guide Spacing
  CHANGELOG.md
  src/components/StyleGuide/Spacing.stories.mdx
  src/components/StyleGuide/Spacing.stories.tsx
Labels: Ship It

#616 DSD-345: enum validation props documentation
  CHANGELOG.md
  README.md
  TYPESCRIPT.md
  package.json
Labels: Ship It

#624 DSD-346: Breadcrumbs - removing a custom SCSS breakpoint
  CHANGELOG.md
  src/components/Breadcrumbs/_Breadcrumbs.scss
Labels: Ship It

#623 DSD-382: Updating Github Actions CI/CD based on TSDX update
  .github/workflows/ci.yml
  .github/workflows/rebase.yml
  .github/workflows/release.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It

#625 DSD-328: added spacing details for Tabular Data
  src/components/StyleGuide/Spacing.stories.mdx
Labels: Needs Review

#629 DSD-391: documentation about Component Version table
  README.md
Labels: Needs Review

#628 DSD-263: Updating the warning for number of children for the Select component
  CHANGELOG.md
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
Labels: Ship It

#627 DSD-122: Fixing bem function bug that crashes Storybook
  CHANGELOG.md
  package-lock.json
  src/__tests__/utils/bem.test.ts
  src/utils/bem.ts
Labels: Ship It

#621 DSD-380/DSD-381: Implementing TSDX and Jest tests
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/rebase.yml
  .github/workflows/release.yml
  .gitignore
  .prettierrc
  .storybook/main.js
  .storybook/preview.tsx
  CHANGELOG.md
  README.md
  example/.npmignore
  example/index.html
  example/index.tsx
  example/package.json
  example/tsconfig.json
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/setup.ts
  src/__tests__/utils/utils.test.ts
  src/components/Accordion/Accordion.stories.tsx
  src/components/Autosuggest/Autosuggest.stories.tsx
  src/components/Button/Button.tsx
  src/components/Heading/Heading.tsx
  src/components/Icons/Icon.tsx
  src/components/List/List.stories.tsx
  src/components/List/List.tsx
  src/components/Pagination/Pagination.stories.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Select/Select.test.tsx
  src/components/StatusBadge/StatusBadge.stories.tsx
  src/helpers/CSSVariablesHelper.tsx
  src/styles.scss
  src/utils/bem.ts
  src/utils/componentCategories.ts
  src/utils/utils.ts
  tsconfig.json
  tsdx.config.js
  tslint.json
  webpack.config.js
Labels: Ship It

#620 DSD-386: Three examples of snapshot testing
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/rebase.yml
  .github/workflows/release.yml
  .gitignore
  .prettierrc
  .storybook/main.js
  .storybook/preview.tsx
  CHANGELOG.md
  README.md
  example/.npmignore
  example/index.html
  example/index.tsx
  example/package.json
  example/tsconfig.json
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/setup.ts
  src/__tests__/utils/utils.test.ts
  src/components/Accordion/Accordion.stories.tsx
  src/components/Autosuggest/Autosuggest.stories.tsx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Heading/Heading.tsx
  src/components/HorizontalRule/HorizontalRule.test.tsx
  src/components/HorizontalRule/__snapshots__/HorizontalRule.test.tsx.snap
  src/components/Icons/Icon.tsx
  src/components/List/List.stories.tsx
  src/components/List/List.tsx
  src/components/Notification/Notification.test.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/Pagination/Pagination.stories.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Select/Select.test.tsx
  src/components/StatusBadge/StatusBadge.stories.tsx
  src/helpers/CSSVariablesHelper.tsx
  src/styles.scss
  src/utils/bem.ts
  src/utils/componentCategories.ts
  src/utils/utils.ts
  tsconfig.json
  tsdx.config.js
  tslint.json
  webpack.config.js
Labels: Ship It
