Repository NYPL/nypl-design-system, pull requests merged in 2021-09, with the labels that each got.

#662 DSD-333: Style Guide Forms
  CHANGELOG.md
  src/components/StyleGuide/Forms.stories.mdx
  src/utils/componentCategories.ts
Labels: Ship It

#665 DSD-448: DatePicker layout correction
  src/components/DatePicker/DatePicker.tsx
Labels: Ship It

#666 prep for release v0.24.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#663 DSD-460: Chakra Radio component refactor
  src/components/Chakra/Stack.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/Radio/Radio.test.tsx
  src/components/Radio/Radio.tsx
  src/components/Radio/_Radio.scss
  src/components/Radio/__snapshots__/Radio.test.tsx.snap
  src/styles.scss
  src/theme/components/radio.ts
  src/theme/index.ts
Labels: Needs Review

#668 DSD-477: export FormSpacing enum
  CHANGELOG.md
  src/components/Form/Form.stories.mdx
  src/index.ts
Labels: Needs Review

#669 DSD-478: Hero Tertiary spacing
  src/components/Hero/Hero.tsx
Labels: Ship It

#673 DSD-481: color page error
  src/components/StyleGuide/UIDocCard.tsx
Labels: no-changelog, Ship It

#674 DSD-476: Card padding bug
  CHANGELOG.md
  src/components/Card/Card.stories.mdx
  src/components/Card/_Card.scss
Labels: Ship It

#664 DSD-199: RadioGroup component - part 2
  src/components/Radio/Radio.stories.mdx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupLayoutTypes.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/index.ts
  src/theme/components/customRadioGroup.ts
  src/theme/index.ts
Labels: Ship It

#670 DSD-479: Tabs - style update
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/theme/components/tabs.ts
  src/theme/index.ts
Labels: Needs Review

#672 DSD-465: new icons for mobile menu
  CHANGELOG.md
  icons/svg/utility_account_filled.svg
  icons/svg/utility_account_unfilled.svg
  icons/svg/utility_hamburger.svg
  icons/svg/utility_search.svg
  package-lock.json
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/IconTypes.tsx
Labels: Ship It

#661 DSD-199: RadioGroup component - Part 1
  src/components/Chakra/Stack.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/Radio/Radio.test.tsx
  src/components/Radio/Radio.tsx
  src/components/Radio/_Radio.scss
  src/components/Radio/__snapshots__/Radio.test.tsx.snap
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupLayoutTypes.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/index.ts
  src/styles.scss
  src/theme/components/customRadioGroup.ts
  src/theme/components/radio.ts
  src/theme/index.ts
Labels: Needs Review

#678 DSD-475: Renaming the errorText prop to invalidText where applicable
  CHANGELOG.md
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Checkbox/Checkbox.test.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/List/List.tsx
  src/components/Radio/Radio.stories.mdx
  src/components/Radio/Radio.test.tsx
  src/components/Radio/Radio.tsx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
Labels: Ship It

#677 DSD-451: Adding Callout variant for the Button component
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.test.tsx
  src/components/Button/ButtonTypes.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/theme/components/button.ts
Labels: Ship It

#679 Prep for Release 0.24.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#680 release v0.24.1
  CHANGELOG.md
  icons/svg/utility_account_filled.svg
  icons/svg/utility_account_unfilled.svg
  icons/svg/utility_hamburger.svg
  icons/svg/utility_search.svg
  package-lock.json
  package.json
  src/components/Card/Card.stories.mdx
  src/components/Card/_Card.scss
  src/components/Form/Form.stories.mdx
  src/components/Hero/Hero.tsx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/IconTypes.tsx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/StyleGuide/UIDocCard.tsx
  src/index.ts
Labels: Ship It, Release

#682 DSD-491: Use new Tugboat QA "development" preview server
  .github/PULL_REQUEST_TEMPLATE
  CHANGELOG.md
  README.md
Labels: Ship It

#671 DSD-471: Chakra Heading component refactor
  CHANGELOG.md
  TYPESCRIPT.md
  example/index.tsx
  package-lock.json
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Card/Card.test.tsx
  src/components/Card/_Card.scss
  src/components/CardEdition/CardEdition.stories.tsx
  src/components/CardEdition/CardEdition.test.tsx
  src/components/CardEdition/_CardEdition.scss
  src/components/Form/Form.stories.mdx
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.test.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/HeadingTypes.tsx
  src/components/Heading/_Heading.scss
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.test.tsx
  src/components/List/List.stories.tsx
  src/components/List/List.test.tsx
  src/components/List/List.tsx
  src/components/Notification/Notification.stories.mdx
  src/components/Notification/Notification.tsx
  src/components/Notification/_Notification.scss
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/StyleGuide/Colors.stories.tsx
  src/components/StyleGuide/Typography.stories.mdx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/index.ts
  src/styles.scss
  src/theme/components/heading.ts
  src/theme/index.ts
Labels: Ship It

#676 DSD-479: final styles for Tabs
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.tsx
  src/theme/components/tabs.ts
Labels: Ship It

#660 DSD-456: Chakra Checkbox
  .prettierrc.json
  .vscode/settings.json
  CHANGELOG.md
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Checkbox/Checkbox.test.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/_Checkbox.scss
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/styles.scss
  src/theme/components/checkbox.ts
  src/theme/index.ts
Labels: Ship It

#689 Fixing issue where the Heading styles did not get imported
  src/theme/index.ts
Labels: Ship It

#681 DSD-473: Chakra Accordion
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.stories.tsx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/_Accordion.scss
  src/styles.scss
  src/theme/components/accordion.ts
  src/theme/index.ts
Labels: Ship It

#683 DSD-474: DS Select component with Chakra's Select component
  CHANGELOG.md
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Select/_Select.scss
  src/styles.scss
  src/theme/components/select.ts
  src/theme/index.ts
Labels: Ship It

#684 DSD-485: Chakra TextInput
  CHANGELOG.md
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/Form/Form.test.tsx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/_TextInput.scss
  src/styles.scss
  src/theme/components/textInput.ts
  src/theme/index.ts
Labels: Ship It

#685 DSD-470: Chakra Hero
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.tsx
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/HeroTypes.tsx
  src/components/Hero/_Hero.scss
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/docs/Intro.stories.mdx
  src/styles.scss
  src/theme/components/hero.ts
  src/theme/index.ts
Labels: Ship It

#691 DSD-430: Using DS spacing values for the Heading component
  CHANGELOG.md
  src/theme/components/heading.ts
Labels: Ship It

#690 DSD-483: Adding ui/error/secondary color and updating names
  CHANGELOG.md
  src/components/Autosuggest/_Autosuggest.scss
  src/components/Breadcrumbs/_Breadcrumbs.scss
  src/components/Button/_Button.scss
  src/components/CardEdition/_CardEdition.scss
  src/components/HelperErrorText/_HelperErrorText.scss
  src/components/Hero/_Hero.scss
  src/components/HorizontalRule/_HorizontalRule.scss
  src/components/Input/_Input.scss
  src/components/Link/_Link.scss
  src/components/List/_List.scss
  src/components/Modal/_Modal.scss
  src/components/Notification/_Notification.scss
  src/components/SkeletonLoader/_SkeletonLoader.scss
  src/components/StatusBadge/_StatusBadge.scss
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyleGuide/Colors.stories.tsx
  src/components/StyleGuide/UIDocCard.tsx
  src/components/VideoPlayer/_VideoPlayer.scss
  src/docs/Chakra.stories.mdx
  src/styles/01-colors/_colors-brand.scss
  src/styles/01-colors/_colors-utility.scss
  src/styles/base/_place-holder.scss
  src/theme/components/accordion.ts
  src/theme/components/button.ts
  src/theme/components/select.ts
  src/theme/components/tabs.ts
  src/theme/components/textInput.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#693 Dsd 470/chakra hero
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.tsx
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/HeroTypes.tsx
  src/components/Hero/_Hero.scss
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/docs/Intro.stories.mdx
  src/styles.scss
  src/theme/components/hero.ts
  src/theme/index.ts
Labels: Ship It

#696 DSD-493: changelog update for SimpleGrid component
  CHANGELOG.md
Labels: Ship It

#687 DSD-338: Chakra template components
  CHANGELOG.md
  package-lock.json
  src/components/Template/Template.stories.mdx
  src/components/Template/Template.stories.tsx
  src/components/Template/Template.test.tsx
  src/components/Template/Template.tsx
  src/components/Template/_Template.scss
  src/index.ts
  src/styles.scss
  src/styles/base/_04-base.scss
  src/theme/components/template.ts
  src/theme/foundations/global.ts
  src/theme/index.ts
Labels: Ship It

#695 DSD-497: Global JS styling objects
  src/theme/components/accordion.ts
  src/theme/components/button.ts
  src/theme/components/checkbox.ts
  src/theme/components/customCheckboxGroup.ts
  src/theme/components/customRadioGroup.ts
  src/theme/components/global.ts
  src/theme/components/globalMixins.ts
  src/theme/components/heading.ts
  src/theme/components/hero.ts
  src/theme/components/radio.ts
  src/theme/components/select.ts
  src/theme/components/tabs.ts
  src/theme/components/textInput.ts
  src/theme/index.ts
Labels: Ship It

#697 DSD-495: Chakra 1.6.8
  package-lock.json
  package.json
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
Labels: Ship It

#692 DSD-496/DSD-426: Updating the Link to use Chakra
  CHANGELOG.md
  package-lock.json
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.test.tsx
  src/components/Link/Link.tsx
  src/components/Link/_Link.scss
  src/components/Pagination/Pagination.test.tsx
  src/theme/components/link.ts
  src/theme/foundations/shadows.ts
  src/theme/index.ts
Labels: Ship It

#698 DSD-494: expose Chakra Grid component
  CHANGELOG.md
  src/components/Chakra/Grid.stories.mdx
  src/index.ts
  src/utils/componentCategories.ts
Labels: Ship It

#701 DSD-462: Updating the SkeletonLoaderLayouts enum values
  CHANGELOG.md
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.test.tsx
  src/components/SkeletonLoader/SkeletonLoader.tsx
  src/components/SkeletonLoader/SkeletonLoaderTypes.tsx
  src/components/SkeletonLoader/_SkeletonLoader.scss
Labels: Ship It

#700 DSD-461: Updating the CardLayouts enum values
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Card/Card.tsx
  src/components/Card/CardTypes.tsx
  src/components/Card/_Card.scss
  src/components/Grid/SimpleGrid.stories.mdx
Labels: Ship It

#706 Prep for Release 0.25.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs Review, Release
