Repository NYPL/nypl-design-system, pull requests merged in 2021-08, with the labels that each got.

#622 DSD-388: Hero Campaign variant
  CHANGELOG.md
  package-lock.json
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/HeroTypes.tsx
  src/components/Hero/_Hero.scss
Labels: Ship It

#626 DSD-323: PostCSS & Autoprefixer
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Hero/Hero.stories.mdx
  src/styles.scss
  tsdx.config.js
Labels: Ship It

#631 DSD-398: video player text elements
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/components/VideoPlayer/VideoPlayer.test.tsx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/components/VideoPlayer/_VideoPlayer.scss
Labels: Ship It

#630 DSD-400: Jest storybook integration
  .github/workflows/gh-pages.yml
  .jest-test-results.json
  .prettierignore
  .storybook/main.js
  .storybook/preview.tsx
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/components/Accordion/Accordion.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Button/Button.stories.mdx
  src/components/Card/Card.stories.tsx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Form/Form.stories.mdx
  src/components/Heading/Heading.stories.mdx
  src/components/HelperErrorText/HelperErrorText.stories.tsx
  src/components/Hero/Hero.stories.mdx
  src/components/HorizontalRule/HorizontalRule.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Image/Image.stories.tsx
  src/components/Input/Input.stories.tsx
  src/components/Label/Label.stories.tsx
  src/components/Link/Link.stories.mdx
  src/components/List/List.stories.mdx
  src/components/Modal/Modal.stories.mdx
  src/components/Notification/Notification.stories.mdx
  src/components/Pagination/Pagination.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/components/StatusBadge/StatusBadge.stories.tsx
  src/components/TextInput/TextInput.stories.mdx
  src/components/VideoPlayer/VideoPlayer.stories.mdx
Labels: Ship It

#615 DSD-253: Storybook component categories
  .storybook/main.js
  .storybook/preview.tsx
  README.md
  package-lock.json
  src/components/Accordion/Accordion.stories.mdx
  src/components/Autosuggest/Autosuggest.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Card/Card.stories.tsx
  src/components/Heading/Heading.stories.mdx
  src/components/HelperErrorText/HelperErrorText.stories.tsx
  src/components/Hero/Hero.stories.mdx
  src/components/HorizontalRule/HorizontalRule.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Image/Image.stories.tsx
  src/components/Link/Link.stories.mdx
  src/components/List/List.stories.mdx
  src/components/Modal/Modal.stories.mdx
  src/components/Notification/Notification.stories.mdx
  src/components/Pagination/Pagination.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/components/StatusBadge/StatusBadge.stories.tsx
  src/components/Template/Template.stories.tsx
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/docs/Intro.stories.mdx
  src/utils/componentCategories.ts
Labels: Needs Review, no-changelog

#643 DSD-428: Using Tugboat QA
  .tugboat/config.yml
  CHANGELOG.md
Labels: Ship It

#641 DSD-415: Chakra layout components
  CHANGELOG.md
  README.md
  src/components/Chakra/Box.stories.mdx
  src/components/Chakra/Center.stories.mdx
  src/components/Chakra/Stack.stories.mdx
  src/index.ts
  src/utils/componentCategories.ts
Labels: Ship It

#634 DSD-396: DatePicker component
  package-lock.json
  package.json
  src/components/Autosuggest/Autosuggest.stories.mdx
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/DatePickerTypes.tsx
  src/components/DatePicker/_DatePicker.scss
  src/index.ts
  src/styles.scss
Labels: Ship It

#638 DSD-397: DatePicker styling
  package-lock.json
  package.json
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/_DatePicker.scss
Labels: Changes Requested

#647 DSD-397: final DatePicker styling
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/_DatePicker.scss
Labels: no-changelog, Ship It

#645 DSD-438: Conditionally render "Required" or "Optional" in the `DatePicker`, `TextInput`, and `Label` components
  CHANGELOG.md
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/Label/Label.stories.mdx
  src/components/Label/Label.stories.tsx
  src/components/Label/Label.tsx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
Labels: Ship It

#649 DSD-439: Adding the 'showOptReqLabel' prop in the Select
  CHANGELOG.md
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
Labels: Ship It

#650 DSD-420: Accordion story bug fix
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.tsx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/List/List.tsx
Labels: Ship It

#651 DSD-440: form spacing variants
  CHANGELOG.md
  src/components/Form/Form.stories.mdx
  src/components/Form/Form.test.tsx
  src/components/Form/Form.tsx
  src/components/Form/FormTypes.tsx
  src/components/Form/_Form.scss
  src/styles/03-space/_space-inline.scss
  src/styles/03-space/_space-inset.scss
  src/styles/03-space/_space-stack.scss
Labels: Ship It

#653 Bug fix: Explicitly adding postcss 8
  package-lock.json
  package.json
Labels: Bug, Ship It

#585 RENO-2240 - Build New Card Component in React DS
  CHANGELOG.md
  package-lock.json
  src/components/Card/Card.stories.mdx
  src/components/Card/Card.test.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardTypes.tsx
  src/components/Card/_Card.scss
  src/components/CardEdition/CardEdition.stories.tsx
  src/components/CardEdition/CardEdition.test.tsx
  src/components/CardEdition/CardEdition.tsx
  src/components/CardEdition/_CardEdition.scss
  src/components/List/List.stories.tsx
  src/components/Modal/Modal.stories.mdx
  src/components/StyleGuide/Spacing.stories.mdx
  src/index.ts
  src/styles.scss
  src/utils/componentCategories.ts
Labels: Ship It

#657 DSD-473: form spacing corrections
  package-lock.json
  src/components/DatePicker/DatePicker.test.tsx
  src/components/Form/Form.test.tsx
  src/components/Form/_Form.scss
  src/components/Form/__snapshots__/Form.test.tsx.snap
Labels: Ship It

#659 DSD-455: Style Guide Typography cleanup
  src/components/StyleGuide/Typography.stories.mdx
Labels: Ship It

#658 DSD-454: Style Guide Iconography cleanup
  src/components/StyleGuide/Iconography.stories.mdx
Labels: Ship It

#652 DSD-29: Tab components
  .storybook/main.js
  CHANGELOG.md
  README.md
  src/components/Button/Button.stories.mdx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/docs/Chakra.stories.mdx
  src/docs/Intro.stories.mdx
  src/index.ts
  src/theme/foundations/spacing.ts
Labels: Ship It

#648 DSD-417: Extending Chakra's base theme with NYPL's theme.
  .storybook/main.js
  CHANGELOG.md
  README.md
  src/components/Button/Button.stories.mdx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/docs/Chakra.stories.mdx
  src/docs/Intro.stories.mdx
  src/index.ts
  src/styles.scss
  src/styles/01-colors/_colors-brand.scss
  src/styles/01-colors/_colors-utility.scss
  src/styles/03-space/_space-inline.scss
  src/styles/03-space/_space-inset.scss
  src/styles/03-space/_space-stack.scss
  src/styles/base/_02-breakpoints.scss
  src/styles/base/_typography.scss
  src/theme/components/button.ts
  src/theme/foundations/breakpoints.ts
  src/theme/foundations/colors.ts
  src/theme/foundations/global.ts
  src/theme/foundations/spacing.ts
  src/theme/foundations/typography.ts
  src/theme/index.ts
  src/theme/types.ts
Labels: Needs Review

#642 DSD-418: Chakra/DS Button component
  .storybook/main.js
  CHANGELOG.md
  README.md
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonTypes.tsx
  src/components/Button/_Button.scss
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/DatePicker/DatePicker.test.tsx
  src/components/Notification/_Notification.scss
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/StyleGuide/Bidirectionality.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/docs/Chakra.stories.mdx
  src/docs/Intro.stories.mdx
  src/index.ts
  src/styles.scss
  src/styles/01-colors/_colors-brand.scss
  src/styles/01-colors/_colors-utility.scss
  src/styles/03-space/_space-inline.scss
  src/styles/03-space/_space-inset.scss
  src/styles/03-space/_space-stack.scss
  src/styles/base/_02-breakpoints.scss
  src/styles/base/_typography.scss
  src/theme/components/button.ts
  src/theme/foundations/breakpoints.ts
  src/theme/foundations/colors.ts
  src/theme/foundations/global.ts
  src/theme/foundations/spacing.ts
  src/theme/foundations/typography.ts
  src/theme/index.ts
  src/theme/types.ts
Labels: Needs Review
