Repository NYPL/nypl-design-system, pull requests merged in 2021-06, with the labels that each got.

#563 DSD-279: CSS Color Vars Malformed in Production Build
  src/styles/01-colors/_colors-utility.scss
Labels: Needs Review

#564 DSD-281: space css vars
  CHANGELOG.md
  src/styles.scss
  src/styles/base/_03-mixins.scss
Labels: Ship It

#565 DSD-284: breadcrumbs mdx story
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/_Breadcrumbs.scss
Labels: Ship It

#576 DSD-304: breadcrumbs width
  CHANGELOG.md
  src/components/Breadcrumbs/_Breadcrumbs.scss
Labels: Ship It

#575 DSD-305: hero width
  CHANGELOG.md
  src/components/Hero/_Hero.scss
Labels: Ship It

#569 DSD-295: horizontal rule
  .storybook/manager-head.html
  CHANGELOG.md
  src/components/HorizontalRule/HorizontalRule.stories.mdx
  src/components/HorizontalRule/HorizontalRule.test.tsx
  src/components/HorizontalRule/HorizontalRule.tsx
  src/components/HorizontalRule/_HorizontalRule.scss
  src/index.ts
  src/styles.scss
Labels: Needs Review

#568 DSD-289: heading mdx story
  CHANGELOG.md
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.stories.tsx
Labels: Ship It

#574 DSD-306: Template DOM structure
  CHANGELOG.md
  src/components/Template/Template.stories.tsx
  src/styles/base/_place-holder.scss
Labels: Ship It, no-changelog

#579 DSD-325: add Style Guide category
  .storybook/manager-head.html
  CHANGELOG.md
  src/components/Breakpoints/Breakpoints.stories.tsx
  src/components/Colors/Colors.stories.tsx
  src/components/Spacing/Spacing.stories.tsx
  src/components/Template/Bidirectionality.stories.mdx
  src/components/Typography/Typography.stories.tsx
  src/utils/componentCategories.ts
Labels: Needs Review

#581 prep for release v0.23.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs Review

#582 release v0.23.0
  .storybook/manager-head.html
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/_Breadcrumbs.scss
  src/components/Breakpoints/Breakpoints.stories.tsx
  src/components/Colors/Colors.stories.tsx
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.stories.tsx
  src/components/Hero/_Hero.scss
  src/components/HorizontalRule/HorizontalRule.stories.mdx
  src/components/HorizontalRule/HorizontalRule.test.tsx
  src/components/HorizontalRule/HorizontalRule.tsx
  src/components/HorizontalRule/_HorizontalRule.scss
  src/components/Spacing/Spacing.stories.tsx
  src/components/Template/Bidirectionality.stories.mdx
  src/components/Template/Template.stories.tsx
  src/components/Typography/Typography.stories.tsx
  src/index.ts
  src/styles.scss
  src/styles/base/_place-holder.scss
  src/utils/componentCategories.ts
Labels: Needs Review
