Repository NYPL/nypl-design-system, pull requests merged in 2021-12, with the labels that each got.

#785 DSD-638: Fixing DatePicker tests
  CHANGELOG.md
  src/components/DatePicker/DatePicker.test.tsx
Labels: Ship It

#780 DSD-636: Removing the knobs addon
  .storybook/main.js
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/CardEdition/CardEdition.stories.tsx
  src/components/Input/Input.stories.tsx
Labels: Ship It

#782 DSD-609: Deprecates the CardEdition component
  CHANGELOG.md
  src/utils/componentCategories.ts
Labels: Ship It

#786 DSD-617, DSD-618 & DSD-621: corrected latest version numbers
  CHANGELOG.md
  src/components/Image/Image.stories.mdx
  src/components/Notification/Notification.stories.mdx
  src/components/Pagination/Pagination.stories.mdx
Labels: Ship It

#781 DSD-608: Deprecates the Input component
  CHANGELOG.md
  src/utils/componentCategories.ts
Labels: Ship It

#784 DSD-620: Updating the margin for sublabels in DatePicker component
  CHANGELOG.md
  src/theme/components/datePicker.ts
Labels: Ship It

#783 DSD-624: Adding additionalStyles prop to Breadcrumbs
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
Labels: Ship It

#787 DSD-639: Better aria labels in the Slider component
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
Labels: Ship It

#795 DSD-644: Refactoring Tabs
  CHANGELOG.md
  src/components/Tabs/Tabs.tsx
Labels: Ship It

#794 DSD-546: Adding a11y documentation
  .github/PULL_REQUEST_TEMPLATE
  README.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Autosuggest/Autosuggest.stories.tsx
  src/components/Card/Card.stories.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/Template/Template.stories.mdx
  src/styles/base/_place-holder.scss
Labels: Ship It

#791 DSD-635: GA Linter update
  .github/workflows/ci.yml
  CHANGELOG.md
  src/components/ProgressIndicator/ProgressIndicator.tsx
  src/components/Slider/Slider.tsx
  src/theme/components/skeletonLoader.ts
Labels: Ship It

#789 DSD-637: Removing alignText from the Notification component
  .github/workflows/ci.yml
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Notification/Notification.stories.mdx
  src/components/Notification/Notification.tsx
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.tsx
  src/components/Template/Template.stories.mdx
Labels: Ship It

#796 DSD-642: Removing the showLabel prop from SearchBar
  CHANGELOG.md
  src/components/Notification/Notification.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.tsx
Labels: Ship It

#790 DSD-622: Using nvm to set the Node version
  .nvmrc
  README.md
  package-lock.json
  package.json
Labels: Ship It

#797 DSD-641: DatePicker - date range proper form spacing
  CHANGELOG.md
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
Labels: Ship It

#798 DSD-619: Updating the Pagination Storybook links
  .jest-test-results.json
  src/components/Pagination/Pagination.stories.mdx
  src/components/Pagination/Pagination.stories.tsx
Labels: Ship It

#799 DSD-645: ActionHelpDefault and ActionHelpOutline icons
  CHANGELOG.md
  icons/svg/action_help_default.svg
  icons/svg/action_help_outline.svg
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/IconTypes.tsx
Labels: Ship It

#800 Prep for Release v0.25.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs Review, Release

#802 Updating Github Pages deployment action to use node 12
  .github/workflows/gh-pages.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It

#803 Release v0.25.5
  .github/workflows/gh-pages.yml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#804 DSD-663: export statements for ProgressIndicator and Slider
  CHANGELOG.md
  src/index.ts
Labels: Ship It

#806 DSD-653: Blogs color variant for Breadcrumbs
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/BreadcrumbsTypes.tsx
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/theme/components/breadcrumb.ts
Labels: Needs Review

#805 DSD-530: SearchBar Required Placeholder
  CHANGELOG.md
  src/components/SearchBar/SearchBar.Test.tsx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.tsx
Labels: Ship It

#808 Prep for Release v0.25.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs Review, Release

#809 Release v0.25.6
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/BreadcrumbsTypes.tsx
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/components/SearchBar/SearchBar.Test.tsx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.tsx
  src/index.ts
  src/theme/components/breadcrumb.ts
Labels: Ship It, Release

#813 DSD-682: Fixing installation bug for node versions greater than 12.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It

#816 Prep for Release 0.25.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#817 Release v0.25.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#810 DSD-569: component category for Table
  CHANGELOG.md
  src/utils/componentCategories.ts
Labels: Ship It

#811 DSD-669: enums for ProgressIndicator
  CHANGELOG.md
  src/index.ts
Labels: Ship It

#812 DSD-675: bg color for Locations variant in Breadcrumbs
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/theme/components/breadcrumb.ts
Labels: Ship It

#807 DSD-646: Label bottom margin
  CHANGELOG.md
  src/theme/components/global.ts
Labels: Ship It

#820 DSD-671 & DSD-672: Slider onChange and isRangeSlider bug fixes
  CHANGELOG.md
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
Labels: Ship It

#821 DSD-676: show icon for Standard Notification
  CHANGELOG.md
  icons/svg/alert_notification_important.svg
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/IconTypes.tsx
  src/components/Notification/Notification.stories.mdx
  src/components/Notification/Notification.test.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.tsx
Labels: Ship It

#815 DSD-668: embedCode prop for VideoPlayer
  CHANGELOG.md
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/components/VideoPlayer/VideoPlayer.test.tsx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
Labels: Ship It

#822 DSD-677: XXS and XS image size variants
  CHANGELOG.md
  src/components/Card/Card.stories.mdx
  src/components/Card/Card.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Image/Image.stories.mdx
  src/components/Image/Image.test.tsx
  src/components/Image/ImageTypes.ts
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/theme/components/card.ts
  src/theme/components/image.ts
Labels: Ship It

#758 DSD-292 Toggle Component
  CHANGELOG.md
  package-lock.json
  src/components/Accordion/Accordion.stories.mdx
  src/components/Button/Button.tsx
  src/components/Card/Card.stories.mdx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Notification/Notification.stories.mdx
  src/components/Pagination/Pagination.stories.mdx
  src/components/Template/Template.stories.mdx
  src/components/Toggle/Toggle.stories.mdx
  src/components/Toggle/Toggle.test.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/ToggleSizes.tsx
  src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/index.ts
  src/theme/components/toggle.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It
