Repository NYPL/nypl-design-system, pull requests merged in 2022-11, with the labels that each got.

#1189 DSD-1187: updated spacing for tertiary variant
  CHANGELOG.md
  src/components/Hero/Hero.stories.mdx
  src/theme/components/hero.ts
Labels: Ship It

#1191 DSD-1189: TextInput focus on input element when clear button is clicked
  CHANGELOG.md
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
Labels: Ship It

#1190 DSD-1180: Adding isClearable to the SearchBar component
  CHANGELOG.md
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
Labels: Ship It

#1188 DSD-1185: docs for button sizes
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
Labels: Ship It

#1192 Prep for Release v1.2.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release

#1194 Release v1.2.2
  CHANGELOG.md
  icons/svg/error-filled.svg
  icons/svg/error-outline.svg
  package-lock.json
  package.json
  src/components/Button/Button.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Footer/__snapshots__/Footer.test.tsx.snap
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Icons/Icon.stories.mdx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Logo/Logo.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/Table/__snapshots__/Table.test.tsx.snap
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/Tooltip/Tooltip.stories.mdx
  src/components/Tooltip/Tooltip.tsx
  src/theme/components/hero.ts
  src/theme/components/textInput.ts
Labels: Release

#1196 DSD-1188: Remove button deprecation warning
  CHANGELOG.md
  src/components/Button/Button.tsx
Labels: Needs Review

#1193 DSD-1175: Replace padding for menuButton
  src/theme/components/multiSelectMenuButton.ts
Labels: Ship It

#1197 DSD-1199: custom viewport options for Storybook
  .storybook/preview.tsx
  CHANGELOG.md
  package.json
Labels: Ship It

#1199 Node env patch for vercel
  CHANGELOG.md
Labels: Ship It

#1198 DSD-1203: default text color for Template
  package.json
  src/theme/components/template.ts
Labels: Ship It
