Repository NYPL/nypl-design-system, pull requests merged in 2022-06, with the labels that each got.

#1028 DSD-996: Bumping up to 1.0.2 and writing why
  .github/workflows/release.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Accordion/Accordion.stories.mdx
  src/components/Button/Button.stories.mdx
  src/components/ButtonGroup/ButtonGroup.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/Heading/Heading.stories.mdx
  src/components/Image/Image.stories.mdx
  src/components/Logo/Logo.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/SkipNavigation/SkipNavigation.stories.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/Table/Table.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/Toggle/Toggle.stories.mdx
Labels: Ship It, Release

#1015 DSD-981: Pinning react-focus-lock through Chakra's own package
  package-lock.json
  package.json
Labels: Ship It, Header

#1026 DSD-991: Updating responsive Template styling for the sidebar
  CHANGELOG.md
  package-lock.json
  src/components/Template/Template.stories.mdx
  src/theme/components/template.ts
Labels: Ship It

#1023 DSD-988: Adding TextInput number type prop validation
  CHANGELOG.md
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: Ship It

#1032 DSD-995: NYPL text only logo
  CHANGELOG.md
  icons/svg/logo-nypl-lion-white.svg
  icons/svg/logo-nypl-text-black.svg
  icons/svg/logo-nypl-text-white.svg
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
Labels: Ship It

#1027 DSD-952: Card linkbox styles
  CHANGELOG.md
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Card/Card.stories.mdx
  src/components/Card/Card.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
Labels: Ship It

#1030 DSD-993: Card's Image size for mobile view
  CHANGELOG.md
  src/components/Card/Card.tsx
Labels: Ship It

#1034 DSD-977 - hover style for Select element
  CHANGELOG.md
  src/components/Select/Select.stories.mdx
  src/theme/components/select.ts
Labels: Ship It

#1035 DSD-997: Optimize npm release bundle
  .npmignore
  README.md
  package-lock.json
  package.json
  src/hooks/__tests__/useCarouselStyles.test.ts
  src/hooks/__tests__/useNYPLTheme.test.tsx
Labels: Ship It

#1033 DSD-999: Fixing bugs found after installing v1.0.2 in Turbine
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Table/Table.stories.mdx
  src/components/Table/Table.tsx
  src/components/Toggle/Toggle.stories.mdx
  src/theme/components/toggle.ts
Labels: Ship It

#1037 DSD-934: responsive Table
  CHANGELOG.md
  src/components/Table/Table.stories.mdx
  src/components/Table/Table.test.tsx
  src/components/Table/Table.tsx
  src/components/Table/__snapshots__/Table.test.tsx.snap
  src/theme/components/customTable.ts
Labels: Ship It

#1031 DSD-985: Header login functionality
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/components/Login.test.tsx
  src/components/Header/components/Login.tsx
  src/components/Header/components/UpperNav.tsx
  src/components/Header/headerUtils.ts
  src/theme/components/headerUpperNav.ts
Labels: Ship It, Header

#1042 Prep for Release v1.0.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Logo/Logo.stories.mdx
Labels: Needs Review, Release

#1046 DSD-1010: MLN Color logo
  CHANGELOG.md
  icons/svg/logo-mln-color.svg
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
Labels: Ship It

#1045 DSD-1017 & DSD-1023: new icon variants
  CHANGELOG.md
  icons/svg/action-exit.svg
  icons/svg/action-power.svg
  icons/svg/action-settings.svg
  icons/svg/building.svg
  icons/svg/locator.svg
  icons/svg/social-facebook.svg
  icons/svg/social-instagram.svg
  icons/svg/social-tumblr.svg
  icons/svg/social-twitter.svg
  icons/svg/social-youtube.svg
  src/components/Button/Button.stories.mdx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/Icon.tsx
  src/components/Icons/IconSvgs.tsx
Labels: Ship It

#1017 DSD-967: Header mobile search
  CHANGELOG.md
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/Mobile.tsx
  src/components/Header/components/MobileNav.test.tsx
  src/components/Header/components/MobileNav.tsx
  src/components/Header/components/MobileNavButton.test.tsx
  src/components/Header/components/MobileNavButton.tsx
  src/components/Header/components/SearchButton.test.tsx
  src/components/Header/components/SearchButton.tsx
  src/components/Header/components/SearchForm.test.tsx
  src/components/Header/components/SearchForm.tsx
  src/components/Header/components/SitewideAlerts.tsx
  src/components/Header/components/__snapshots__/MobileNav.test.tsx.snap
  src/components/Header/components/__snapshots__/MobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/SearchButton.test.tsx.snap
  src/components/Header/components/__snapshots__/SearchForm.test.tsx.snap
  src/theme/components/header.ts
  src/theme/components/headerLowerNav.ts
  src/theme/components/headerMobile.ts
  src/theme/components/headerMobileNav.ts
  src/theme/components/headerMobileNavButton.ts
  src/theme/components/headerSearchButton.ts
  src/theme/components/headerSearchForm.ts
  src/theme/components/sitewideAlerts.ts
  src/theme/index.ts
Labels: Ship It, Header

#1039 DSD-91: Image component lazy loading
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Card/Card.test.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Grid/SimpleGrid.test.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Image/Image.stories.mdx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/StructuredContent/StructuredContent.test.tsx
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/Table/Table.test.tsx
  src/components/Table/__snapshots__/Table.test.tsx.snap
  src/theme/components/image.ts
Labels: Ship It

#1041 DSD-1001: Updated main SCSS file
  CHANGELOG.md
  README.md
  src/components/Placeholder/_Placeholder.scss
  src/resources.scss
  src/styles.scss
  src/styles/base/_02-mixins.scss
Labels: Ship It

#1052 DSD-1020 - text case styles
  CHANGELOG.md
  src/components/Text/Text.stories.mdx
  src/components/Text/Text.tsx
  src/theme/components/text.ts
Labels: Ship It

#1051 DSD-1003 - default BG for Checkbox and Radio
  CHANGELOG.md
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/theme/components/checkbox.ts
  src/theme/components/radio.ts
Labels: Ship It

#1056 DSD-1018: docs for Table component
  CHANGELOG.md
  src/components/Table/Table.stories.mdx
Labels: Ship It

#1054 DSD-1015: mobile styles for Button, Select and TextInput
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/theme/components/button.ts
  src/theme/components/global.ts
  src/theme/components/select.ts
  src/theme/components/textInput.ts
Labels: Ship It

#1057 DSD-1026: width of select in SearchBar
  CHANGELOG.md
  src/components/SearchBar/SearchBar.stories.mdx
  src/theme/components/searchBar.ts
Labels: Ship It

#1050 DSD-1008: Login refresh
  CHANGELOG.md
  package-lock.json
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/authApiMockResponse.ts
  src/components/Header/components/SitewideAlerts.test.tsx
  src/components/Header/components/SitewideAlertsMocks.ts
  src/components/Header/headerUtils.ts
Labels: Needs Review, Header

#1053 DSD-1021 - Heading case styles
  CHANGELOG.md
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.tsx
  src/theme/components/heading.ts
Labels: Ship It

#1044 DSD-966: Mobile Header Login
  CHANGELOG.md
  package-lock.json
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/Login.test.tsx
  src/components/Header/components/Login.tsx
  src/components/Header/components/LoginButton.test.tsx
  src/components/Header/components/LoginButton.tsx
  src/components/Header/components/Mobile.tsx
  src/components/Header/components/UpperNav.tsx
  src/theme/components/headerLogin.ts
  src/theme/components/headerLoginButton.ts
  src/theme/components/headerMobile.ts
  src/theme/components/headerUpperNav.ts
  src/theme/index.ts
Labels: Ship It, Header

#1058 Prep for Release v1.0.4
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Logo/Logo.stories.mdx
Labels: Release

#1061 DSD-1027: Header Refactoring 2 (Styles)
  src/components/Form/Form.tsx
  src/components/Form/__snapshots__/Form.test.tsx.snap
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/Login.tsx
  src/components/Header/components/LoginButton.test.tsx
  src/components/Header/components/LoginButton.tsx
  src/components/Header/components/LowerNav.tsx
  src/components/Header/components/Mobile.tsx
  src/components/Header/components/MobileIconNav.tsx
  src/components/Header/components/MobileNav.tsx
  src/components/Header/components/MobileNavButton.tsx
  src/components/Header/components/SearchButton.tsx
  src/components/Header/components/SearchForm.tsx
  src/components/Header/components/SitewideAlerts.test.tsx
  src/components/Header/components/SitewideAlerts.tsx
  src/components/Header/components/UpperNav.tsx
  src/components/Header/components/__snapshots__/MobileNav.test.tsx.snap
  src/components/Header/components/__snapshots__/MobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/SearchForm.test.tsx.snap
  src/components/Header/components/index.tsx
  src/components/Header/utils/SitewideAlertsMocks.ts
  src/components/Header/utils/authApiMockResponse.ts
  src/components/Header/utils/headerUtils.test.ts
  src/components/Header/utils/headerUtils.ts
  src/theme/components/header/header.ts
  src/theme/components/header/headerLogin.ts
  src/theme/components/header/headerLoginButton.ts
  src/theme/components/header/headerLowerNav.ts
  src/theme/components/header/headerMobileIconNav.ts
  src/theme/components/header/headerMobileNav.ts
  src/theme/components/header/headerMobileNavButton.ts
  src/theme/components/header/headerSearchButton.ts
  src/theme/components/header/headerSearchForm.ts
  src/theme/components/header/headerSitewideAlerts.ts
  src/theme/components/header/headerUpperNav.ts
  src/theme/index.ts
Labels: Needs Review, Header

#1065 DSD-1037: Adding new svg icons to mobile Header nav
  src/components/Header/components/MobileNav.tsx
  src/components/Header/components/__snapshots__/MobileNav.test.tsx.snap
  src/theme/components/header/headerMobileNav.ts
Labels: Needs Review, Header

#1063 DSD-665: updated doc for Colors Style Guide
  CHANGELOG.md
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/Colors.stories.mdx
  src/index.ts
Labels: Ship It
