Repository NYPL/nypl-design-system, pull requests merged in 2022-04, with the labels that each got.

#928 Small fix for bad merge
  src/theme/components/card.ts
Labels: Ship It

#929 Prep for Release v0.25.13
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Heading/Heading.stories.mdx
  src/components/Hero/Hero.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Image/Image.stories.mdx
  src/components/List/List.stories.mdx
  src/components/Notification/Notification.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/components/StructuredContent/StructuredContent.stories.mdx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Text/Text.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
Labels: Ship It, Release

#940 DSD-915: hex value for ui.gray.light-cool
  CHANGELOG.md
  src/theme/foundations/colors.ts
Labels: Ship It

#939 DSD-906: default BG color in Accordion
  CHANGELOG.md
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Labels: Ship It

#938 DSD-907: default BG color in Hero
  CHANGELOG.md
  src/theme/components/hero.ts
Labels: Ship It

#937 DSD-908: BG color in SkeletonLoader
  CHANGELOG.md
  src/theme/components/skeletonLoader.ts
Labels: Ship It

#936 DSD-909: BG color in VideoPlayer
  CHANGELOG.md
  src/theme/components/videoPlayer.ts
Labels: Ship It

#935 DSD-905: BG colors in Tabs
  CHANGELOG.md
  src/theme/components/tabs.ts
Labels: Ship It

#932 DSD-898: button colors
  CHANGELOG.md
  src/theme/components/button.ts
Labels: Ship It

#933 DSD-901: form inputs disabled state styles
  CHANGELOG.md
  src/components/Toggle/Toggle.tsx
  src/theme/components/checkbox.ts
  src/theme/components/global.ts
  src/theme/components/radio.ts
  src/theme/components/select.ts
  src/theme/components/slider.ts
  src/theme/components/textInput.ts
  src/theme/components/toggle.ts
Labels: Ship It

#934 DSD-899: Checkbox border radius
  CHANGELOG.md
  src/theme/components/checkbox.ts
  src/theme/foundations/radii.ts
Labels: Ship It

#931 DSD-845: Hooks Storybook documentation & more exposed design tokens
  CHANGELOG.md
  src/docs/Chakra.stories.mdx
  src/hooks/useCarouselStyles.stories.mdx
  src/hooks/useCarouselStyles.ts
  src/hooks/useNYPLTheme.stories.mdx
  src/hooks/useNYPLTheme.ts
  src/hooks/useWindowSize.stories.mdx
  src/index.ts
  src/theme/foundations/spacing.ts
Labels: Ship It

#941 Dsd 880/remove auto ids
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Accordion/Accordion.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Card/Card.tsx
  src/components/Checkbox/Checkbox.test.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/CheckboxGroup/CheckboxGroup.test.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/ComponentWrapper/ComponentWrapper.tsx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/Fieldset/Fieldset.test.tsx
  src/components/Fieldset/Fieldset.tsx
  src/components/Fieldset/__snapshots__/Fieldset.test.tsx.snap
  src/components/Form/Form.test.tsx
  src/components/Form/Form.tsx
  src/components/Grid/SimpleGrid.tsx
  src/components/Heading/Heading.tsx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/Icons/Icon.tsx
  src/components/Label/Label.test.tsx
  src/components/Label/Label.tsx
  src/components/Link/Link.tsx
  src/components/List/List.tsx
  src/components/Logo/Logo.tsx
  src/components/Notification/Notification.tsx
  src/components/Pagination/Pagination.tsx
  src/components/ProgressIndicator/ProgressIndicator.test.tsx
  src/components/ProgressIndicator/ProgressIndicator.tsx
  src/components/Radio/Radio.test.tsx
  src/components/Radio/Radio.tsx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
  src/components/StatusBadge/StatusBadge.tsx
  src/components/StructuredContent/StructuredContent.tsx
  src/components/StyleGuide/Forms.stories.mdx
  src/components/Table/Table.tsx
  src/components/Tabs/Tabs.tsx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/Toggle/Toggle.test.tsx
  src/components/Toggle/Toggle.tsx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/helpers/generateUUID.tsx
Labels: Ship It

#942 DSD-897: Updating Required text in the Label and Fieldset components
  CHANGELOG.md
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.test.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Fieldset/Fieldset.stories.mdx
  src/components/Fieldset/Fieldset.test.tsx
  src/components/Fieldset/Fieldset.tsx
  src/components/Fieldset/__snapshots__/Fieldset.test.tsx.snap
  src/components/Form/Form.stories.mdx
  src/components/Label/Label.stories.mdx
  src/components/Label/Label.test.tsx
  src/components/Label/Label.tsx
  src/components/Label/__snapshots__/Label.test.tsx.snap
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/theme/components/fieldset.ts
  src/theme/components/global.ts
  src/theme/components/label.ts
Labels: Ship It

#927 DSD-885: Accessibility docs for Content Display components
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/StatusBadge/StatusBadge.stories.mdx
  src/components/StatusBadge/StatusBadge.tsx
Labels: Ship It

#944 DSD-910: Fixing bad storybook args which caused Pagination log message
  src/components/Pagination/Pagination.stories.mdx
Labels: Ship It

#947 Dsd 857/row layout select
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/Label/Label.stories.mdx
  src/components/Label/Label.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Select/SelectTypes.tsx
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/index.ts
  src/theme/components/label.ts
  src/theme/components/select.ts
Labels: Ship It

#945 DSD-918: Adding IDs to form components in docs
  src/components/Button/Button.stories.mdx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/Form/Form.stories.mdx
  src/components/Label/Label.stories.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/Toggle/Toggle.stories.mdx
Labels: Ship It

#925 DSD-824: HelperErrorText styling/implementation refactor
  CHANGELOG.md
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Checkbox/Checkbox.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/ComponentWrapper/ComponentWrapper.tsx
  src/components/ComponentWrapper/__snapshots__/ComponentWrapper.test.tsx.snap
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/Radio/Radio.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/Slider/Slider.tsx
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/Toggle/Toggle.stories.mdx
  src/components/Toggle/Toggle.tsx
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
  src/theme/components/checkbox.ts
  src/theme/components/checkboxGroup.ts
  src/theme/components/componentWrapper.ts
  src/theme/components/global.ts
  src/theme/components/helperErrorText.ts
  src/theme/components/radio.ts
  src/theme/components/radioGroup.ts
  src/theme/components/select.ts
  src/theme/components/slider.ts
  src/theme/components/textInput.ts
  src/theme/components/toggle.ts
Labels: Ship It

#920 DSD-859: Refactoring RadioGroup
  CHANGELOG.md
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/Radio/Radio.tsx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/theme/components/fieldset.ts
Labels: Ship It

#957 DSD-320: semantic design tokens for spacing
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/Chakra/Grid.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Form/__snapshots__/Form.test.tsx.snap
  src/components/Grid/GridTypes.tsx
  src/components/Grid/__snapshots__/SimpleGrid.test.tsx.snap
  src/components/Placeholder/Placeholder.tsx
  src/components/StyleGuide/Spacing.stories.mdx
  src/components/Template/__snapshots__/Template.test.tsx.snap
  src/styles/base/_place-holder.scss
  src/theme/components/button.ts
  src/theme/components/card.ts
  src/theme/components/hero.ts
  src/theme/components/list.ts
  src/theme/components/notification.ts
  src/theme/components/select.ts
  src/theme/components/statusBadge.ts
  src/theme/components/structuredContent.ts
  src/theme/components/template.ts
  src/theme/components/textInput.ts
  src/theme/foundations/spacing.ts
  src/theme/foundations/typography.ts
Labels: Ship It

#958 DSD-922: focus styles for Radio and TextInput
  CHANGELOG.md
  src/theme/components/global.ts
  src/theme/components/radio.ts
  src/theme/components/select.ts
  src/theme/components/textInput.ts
Labels: Ship It

#951 DSD-886: Adding a11y docs for Feedback components
  src/components/Notification/Notification.stories.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
Labels: Ship It

#952 DSD-892: Adding a11y docs for Typography components
  src/components/Heading/Heading.stories.mdx
  src/components/List/List.stories.mdx
  src/components/Text/Text.stories.mdx
Labels: Ship It

#953 DSD-890: Adding a11y docs for Overlays
  src/components/Modal/Modal.stories.mdx
  src/components/Tabs/Tabs.stories.mdx
Labels: Ship It

#954 DSD-891: Adding a11y docs for page layout components
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/HorizontalRule/HorizontalRule.stories.mdx
  src/components/StructuredContent/StructuredContent.stories.mdx
  src/components/Table/Table.stories.mdx
  src/components/Template/Template.stories.mdx
  src/utils/componentCategories.ts
Labels: Ship It

#955 DSD-889: Adding a11y docs for navigation components
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Link/Link.stories.mdx
  src/components/Pagination/Pagination.stories.mdx
Labels: Ship It

#956 DSD-888: Adding a11y docs for Media components
  src/components/Icons/Icon.stories.mdx
  src/components/Image/Image.stories.mdx
  src/components/Logo/Logo.stories.mdx
  src/components/VideoPlayer/VideoPlayer.stories.mdx
Labels: Ship It

#960 DSD-927: Updating List definition to description
  CHANGELOG.md
  src/components/List/List.stories.mdx
  src/components/List/List.test.tsx
  src/components/List/List.tsx
  src/components/List/ListTypes.tsx
  src/components/List/__snapshots__/List.test.tsx.snap
  src/components/StyleGuide/Spacing.stories.mdx
Labels: Ship It

#962 DSD-674: Fixing the button layout in the Form components
  CHANGELOG.md
  src/components/Form/Form.stories.mdx
  src/theme/components/button.ts
Labels: Ship It

#959 DSD-920: Updating styles for the datepicker's calendar popup
  CHANGELOG.md
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/DatePicker/_DatePicker.scss
Labels: Ship It

#964 DSD-933: Fixing controlling the Select component in the SearchBar component
  CHANGELOG.md
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
Labels: Ship It

#961 DSD-887: Adding accessibility documentation for form components
  src/components/Button/Button.stories.mdx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/Fieldset/Fieldset.stories.mdx
  src/components/Form/Form.stories.mdx
  src/components/Label/Label.stories.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/Toggle/Toggle.stories.mdx
  src/components/Toggle/Toggle.tsx
Labels: Ship It

#966 DSD-836: Updates URL for storybook
  .github/workflows/gh-pages.yml
  .jest-test-results.json
  .tugboat/config.yml
  CHANGELOG.md
  package.json
Labels: Needs Review

#922 DSD-865: Reservoir branding
  .github/CONTRIBUTING.md
  .storybook/CustomTheme.js
  .storybook/manager-head.html
  .storybook/public/favicon.ico
  .storybook/public/favicon.png
  .storybook/public/nypl-reservoir-design-system-logo.svg
  CHAKRA_MIGRATION_GUIDE.md
  CHANGELOG.md
  README.md
  TYPESCRIPT.md
  example/index.html
  icons/svg/logo_reservoir_horizontal_color.svg
  icons/svg/logo_reservoir_icon_color.svg
  icons/svg/logo_reservoir_vertical_color.svg
  package.json
  src/components/Autosuggest/Autosuggest.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Chakra/Grid.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/Form/Form.stories.mdx
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/LogoSvgs.tsx
  src/components/Logo/LogoTypes.tsx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/StyleGuide/Bidirectionality.stories.mdx
  src/components/StyleGuide/Breakpoints.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyleGuide/DesignTokens.stories.mdx
  src/components/StyleGuide/Forms.stories.mdx
  src/components/StyleGuide/Iconography.stories.mdx
  src/components/StyleGuide/Spacing.stories.mdx
  src/components/StyleGuide/Typography.stories.mdx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Template/Template.stories.mdx
  src/docs/Chakra.stories.mdx
  src/docs/Welcome.stories.mdx
  src/utils/componentCategories.ts
Labels: Ship It

#969 Prep for Release v0.26.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#971 0.26.1: updates package-lock and updates prod url
  .github/workflows/gh-pages.yml
  .tugboat/config.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
Labels: Ship It, Release

#972 Release v0.26.1
  .github/workflows/gh-pages.yml
  .tugboat/config.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
Labels: Ship It, Release

#965 DSD-926: Header static
  .jest-test-results.json
  CHANGELOG.md
  src/components/Header/Header.stories.mdx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/index.ts
  src/theme/components/header.ts
  src/theme/index.ts
Labels: Blocked

#975 DSD-935: Links hover state
  CHANGELOG.md
  package-lock.json
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/theme/components/header.ts
Labels: Needs Review

#967 DSD-930: Bumping up to React 17
  .jest-test-results.json
  .storybook/main.js
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.test.tsx
  src/components/Pagination/Pagination.stories.mdx
Labels: Ship It

#968 DSD-802: Chakra update
  .storybook/main.js
  .storybook/preview.tsx
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It

#974 DSD-946: Helper text position
  CHANGELOG.md
  package-lock.json
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/theme/components/select.ts
Labels: Needs Review

#977 Prep for Release v0.27.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release
