Repository NYPL/nypl-design-system, pull requests merged in 2022-09, with the labels that each got.

#1127 DSD-1120: dark mode support for global styles
  CHANGELOG.md
  src/theme/foundations/global.ts
Labels: Needs Review

#1126 DSD-1105: dark mode support for Content Display components
  CHANGELOG.md
  src/theme/components/helperErrorText.ts
  src/theme/components/statusBadge.ts
Labels: Ship It

#1131 Removes default background color in storybook
  .storybook/preview.tsx
Labels: Ship It

#1133 DSD-1104: dark mode support for Basic Elements
  CHANGELOG.md
  src/components/Card/Card.stories.mdx
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/Hero/Hero.stories.mdx
  src/components/StatusBadge/StatusBadge.stories.mdx
  src/theme/components/card.ts
  src/theme/components/hero.ts
  src/theme/foundations/colors.ts
  src/utils/utils.ts
Labels: Needs Review

#1129 DSD-1133: Passing defaultValue down to hidden TextInput
  CHANGELOG.md
  package-lock.json
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.tsx
Labels: Ship It

#1112 DSD-1075: MultiSelect accessibility fixes
  package-lock.json
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelectMenuButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/theme/components/multiSelectMenuButton.ts
Labels: Ship It

#1036 DSD-957: Multiselect Group Component
  .jest-test-results.json
  package-lock.json
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/components/MultiSelect/MultiSelectListbox.tsx
  src/components/MultiSelect/MultiSelectMenuButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/MultiSelectGroup.stories.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/theme/components/multiSelect.ts
  src/theme/components/multiSelectMenuButton.ts
  src/utils/componentCategories.ts
Labels: Ship It

#1135 DSD-1113: text variant for Button component
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/StyleGuide/Buttons.stories.mdx
  src/theme/components/button.ts
Labels: Ship It

#1132 DSD-1112: dark mode support for Typography components
  CHANGELOG.md
  src/theme/components/heading.ts
  src/theme/components/list.ts
Labels: Ship It

#1142 DSD-1113: warning message for deprecated variant
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/components/Header/components/HeaderMobileNavButton.tsx
  src/components/Header/components/HeaderSearchButton.tsx
  src/components/Notification/Notification.tsx
  src/theme/components/header/headerSearchButton.ts
Labels: Ship It

#1140 Prep for Release v1.1.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#1134 DSD-1107: dark mode support for Form Elements component
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/DatePicker/_DatePicker.scss
  src/components/Fieldset/Fieldset.stories.mdx
  src/components/Label/Label.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.tsx
  src/components/TextInput/TextInput.stories.mdx
  src/components/Toggle/Toggle.stories.mdx
  src/theme/components/button.ts
  src/theme/components/checkbox.ts
  src/theme/components/global.ts
  src/theme/components/radio.ts
  src/theme/components/searchBar.ts
  src/theme/components/select.ts
  src/theme/components/slider.ts
  src/theme/components/textInput.ts
  src/theme/components/toggle.ts
Labels: Ship It

#1138 DSD-1139: Secondary Button styles
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/theme/components/button.ts
Labels: Ship It

#1139 DSD-1115: remove Tooltip drop shadow
  CHANGELOG.md
  src/components/Tooltip/Tooltip.stories.mdx
  src/theme/components/tooltip.ts
Labels: Ship It

#1137 DSD-1106/dark mode feedback cat
  CHANGELOG.md
  package-lock.json
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Notification/Notification.stories.mdx
  src/components/Notification/Notification.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/ProgressIndicator/ProgressIndicator.stories.mdx
  src/components/ProgressIndicator/ProgressIndicator.test.tsx
  src/components/ProgressIndicator/ProgressIndicator.tsx
  src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.tsx
  src/theme/components/button.ts
  src/theme/components/notification.ts
  src/theme/components/progressIndicator.ts
  src/theme/components/skeletonLoader.ts
Labels: Ship It

#1148 DSD-1111: dark mode support for Page Layout components
  CHANGELOG.md
  icons/svg/utility-hamburger.svg
  src/components/Footer/Footer.stories.mdx
  src/components/Header/Header.stories.mdx
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderSearchButton.tsx
  src/components/HorizontalRule/HorizontalRule.stories.mdx
  src/components/Table/Table.stories.mdx
  src/theme/components/customTable.ts
  src/theme/components/footer.ts
  src/theme/components/header/header.ts
  src/theme/components/header/headerLoginButton.ts
  src/theme/components/header/headerLowerNav.ts
  src/theme/components/header/headerMobileIconNav.ts
  src/theme/components/header/headerMobileNavButton.ts
  src/theme/components/header/headerSearchButton.ts
  src/theme/components/header/headerSitewideAlerts.ts
  src/theme/components/header/headerUpperNav.ts
  src/theme/components/horizontalRule.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#1141 DSD-1137: Updating spacing between icon and text in the Notification component
  CHANGELOG.md
  package-lock.json
  src/theme/components/notification.ts
Labels: Ship It

#1147 DSD-1142: Accordion always render content
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
Labels: Ship It

#1149 DSD-1124: Fixing placement of links in the Footer
  CHANGELOG.md
  src/components/Footer/Footer.stories.mdx
  src/theme/components/footer.ts
Labels: Ship It

#1150 DSD-1140: Removing data-testid from the Button component
  CHANGELOG.md
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderMobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: Ship It

#1151 DSD-1092: Updating content alignment in the Table component
  CHANGELOG.md
  src/components/Table/Table.stories.mdx
  src/theme/components/customTable.ts
Labels: Ship It

#1136 DDS-1135/Refactor useMultiSelect
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/hooks/__tests__/useMultiSelect.test.ts
  src/hooks/useMultiSelect.stories.mdx
  src/hooks/useMultiSelect.ts
Labels: Needs Review

#1146 DSD-1114: Button sizes
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Header/Header.stories.mdx
  src/components/Notification/Notification.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/theme/components/button.ts
  src/theme/components/header/headerLoginButton.ts
  src/theme/components/header/headerSearchButton.ts
  src/theme/components/header/headerSearchForm.ts
  src/theme/foundations/spacing.ts
  src/theme/foundations/typography.ts
Labels: Ship It

#1153 DSD-1145: Allowing the Slider component to update programmatically
  CHANGELOG.md
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
Labels: Ship It

#1155 DSD-1146: Allow CheckboxGroup to update programmatically
  CHANGELOG.md
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.test.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
Labels: Ship It

#1156 Prep for Release v1.1.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Slider/Slider.stories.mdx
Labels: Release

#1157 Release v1.1.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.test.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/Footer/Footer.stories.mdx
  src/components/Header/Header.stories.mdx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderMobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/components/Notification/Notification.stories.mdx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/Table/Table.stories.mdx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/Tooltip/Tooltip.stories.mdx
  src/theme/components/button.ts
  src/theme/components/customTable.ts
  src/theme/components/footer.ts
  src/theme/components/header/headerLoginButton.ts
  src/theme/components/header/headerSearchButton.ts
  src/theme/components/header/headerSearchForm.ts
  src/theme/components/notification.ts
  src/theme/components/tooltip.ts
  src/theme/foundations/spacing.ts
  src/theme/foundations/typography.ts
Labels: Ship It, Release
