Repository NYPL/nypl-design-system, pull requests merged in 2022-08, with the labels that each got.

#987 DSD-240: Multiselect Component
  .jest-test-results.json
  package-lock.json
  package.json
  src/components/Icons/Icon.tsx
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/components/MultiSelect/MultiSelectListbox.tsx
  src/components/MultiSelect/MultiSelectMenuButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/hooks/__tests__/useMultiSelect.test.ts
  src/hooks/useMultiSelect.stories.mdx
  src/hooks/useMultiSelect.ts
  src/index.ts
  src/theme/components/button.ts
  src/theme/components/icon.ts
  src/theme/components/multiSelect.ts
  src/theme/components/multiSelectMenuButton.ts
  src/theme/foundations/radii.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It

#1107 DSD-498: Updating the Placeholder's css
  CHANGELOG.md
  src/components/Placeholder/_Placeholder.scss
  src/components/Template/Template.stories.mdx
Labels: Ship It

#1108 DSD-1079: styles for sidebar heading
  .storybook/manager-head.html
Labels: Ship It

#1109 DSD-46: [Addendum] Adding TemplateContentBottom and updating the Template DOM structure
  src/components/Template/Template.stories.mdx
  src/components/Template/Template.tsx
  src/components/Template/__snapshots__/Template.test.tsx.snap
  src/theme/components/skipNavigation.ts
  src/theme/components/template.ts
Labels: Ship It

#1101 Adding new hex values for some base colors and adding dark mode colors
  CHANGELOG.md
  package-lock.json
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/Colors.stories.mdx
  src/hooks/__tests__/useNYPLTheme.test.tsx
  src/hooks/useNYPLTheme.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#1105 DSD-1082: Header VQA fixes
  package-lock.json
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderMobileNav.test.tsx
  src/components/Header/components/HeaderMobileNav.tsx
  src/components/Header/components/HeaderSearchButton.tsx
  src/components/Header/components/__snapshots__/HeaderMobileNav.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchButton.test.tsx.snap
  src/theme/components/header/header.ts
  src/theme/components/header/headerLogin.ts
  src/theme/components/header/headerLoginButton.ts
  src/theme/components/header/headerLowerNav.ts
  src/theme/components/header/headerMobileNav.ts
  src/theme/components/header/headerMobileNavButton.ts
  src/theme/components/header/headerSearchButton.ts
  src/theme/components/header/headerSearchForm.ts
  src/theme/components/header/headerSitewideAlerts.ts
  src/theme/components/header/headerUpperNav.ts
Labels: Ship It, Header

#1111 DSD-1043: TOC styles for Style Guide pages
  CHANGELOG.md
  src/components/StyleGuide/Bidirectionality.stories.mdx
  src/components/StyleGuide/Breakpoints.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/StyleGuide/ColorMode.stories.mdx
  src/components/StyleGuide/DesignTokens.stories.mdx
  src/components/StyleGuide/Forms.stories.mdx
  src/components/StyleGuide/Iconography.stories.mdx
  src/components/StyleGuide/Spacing.stories.mdx
  src/components/StyleGuide/Typography.stories.mdx
Labels: Ship It

#1098 DSD-46: Using grid instead of flexbox for the template components
  CHANGELOG.md
  package-lock.json
  src/components/Placeholder/_Placeholder.scss
  src/components/Template/Template.stories.mdx
  src/components/Template/Template.tsx
  src/components/Template/__snapshots__/Template.test.tsx.snap
  src/theme/components/skipNavigation.ts
  src/theme/components/template.ts
Labels: Ship It

#1110 DSD-1091: Passing props in the Image component to the correct location
  CHANGELOG.md
  src/components/Image/Image.stories.mdx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
Labels: Ship It

#1106 DSD-499: panelMaxHeight prop on Accordion
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Labels: Ship It

#1113 DSD-1095: Conditionally render accordion contents
  CHANGELOG.md
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Labels: Ship It

#1114 Prep for Release v1.0.8
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Image/Image.stories.mdx
Labels: Ship It, Release

#1115 Release v1.0.8
  .storybook/manager-head.html
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Image/Image.stories.mdx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Placeholder/_Placeholder.scss
  src/components/StyleGuide/Bidirectionality.stories.mdx
  src/components/StyleGuide/Breakpoints.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/ColorMode.stories.mdx
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyleGuide/DesignTokens.stories.mdx
  src/components/StyleGuide/Forms.stories.mdx
  src/components/StyleGuide/Iconography.stories.mdx
  src/components/StyleGuide/Spacing.stories.mdx
  src/components/StyleGuide/Typography.stories.mdx
  src/components/Template/Template.stories.mdx
  src/components/Template/Template.tsx
  src/components/Template/__snapshots__/Template.test.tsx.snap
  src/hooks/__tests__/useNYPLTheme.test.tsx
  src/hooks/useNYPLTheme.ts
  src/theme/components/skipNavigation.ts
  src/theme/components/template.ts
  src/theme/foundations/colors.ts
Labels: Ship It, Release

#1118 DSD-336: Tooltip Component
  CHANGELOG.md
  src/components/Tooltip/Tooltip.stories.mdx
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/Tooltip.tsx
  src/index.ts
  src/theme/components/tooltip.ts
  src/theme/index.ts
Labels: Ship It

#1121 DSD-1090: Update colormode story
  CHANGELOG.md
  src/components/StyleGuide/ColorMode.stories.mdx
Labels: Ship It

#1104 DSD-1054: Footer
  CHANGELOG.md
  src/components/Footer/Footer.stories.mdx
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/__snapshots__/Footer.test.tsx.snap
  src/components/Footer/footerLinks.ts
  src/theme/components/fieldset.ts
  src/theme/components/footer.ts
  src/theme/components/globalMixins.ts
  src/theme/components/radio.ts
  src/theme/index.ts
Labels: Ship It, Footer

#1125 Prep release for 1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Template/Template.stories.mdx
Labels: Ship It, Release
