Repository NYPL/nypl-design-system, pull requests merged in 2022-05, with the labels that each got.

#983 DSD-923 - Select remove unnecessary spacing
  CHANGELOG.md
  src/theme/components/select.ts
Labels: Ship It

#984 DSD-953: Removing the attributes prop
  CHANGELOG.md
  src/components/Autosuggest/Autosuggest.stories.tsx
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.tsx
  src/components/Notification/Notification.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Radio/Radio.tsx
  src/components/Slider/Slider.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Template/Template.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: Ship It

#963 DSD-929: SkipNav component
  CHANGELOG.md
  package-lock.json
  src/components/AccessibilityGuide/SkipNavigation.stories.mdx
  src/components/SkipNavigation/SkipNavigation.stories.mdx
  src/components/SkipNavigation/SkipNavigation.test.tsx
  src/components/SkipNavigation/SkipNavigation.tsx
  src/components/SkipNavigation/__snapshots__/SkipNavigation.test.tsx.snap
  src/components/Template/Template.stories.mdx
  src/components/Template/Template.tsx
  src/index.ts
  src/theme/components/skipNavigation.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Needs Review

#991 DSD-614: Hero documentation
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Template/Template.stories.mdx
Labels: Ship It

#993 DSD-954: Minor typo fix to Modal example
  src/components/Modal/Modal.stories.mdx
Labels: Ship It

#985 DSD-921: ButtonGroup component
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/ButtonGroup/ButtonGroup.stories.mdx
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/Form/Form.stories.mdx
  src/components/Modal/Modal.stories.mdx
  src/components/Modal/Modal.tsx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/index.ts
  src/theme/components/buttonGroup.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It

#981 DSD-942: Allows JSX elements to be rendered in the Table component
  CHANGELOG.md
  src/components/Table/Table.stories.mdx
  src/components/Table/Table.test.tsx
  src/components/Table/Table.tsx
  src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: Ship It

#995 Prep for Release v0.28.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/SkipNavigation/SkipNavigation.stories.mdx
Labels: Release

#989 DSD-958: URL link cleanup
  CHAKRA_MIGRATION_GUIDE.md
  README.md
  src/components/Card/Card.stories.mdx
  src/components/Chakra/Box.stories.mdx
  src/components/Chakra/Center.stories.mdx
  src/components/Chakra/Flex.stories.mdx
  src/components/Chakra/Grid.stories.mdx
  src/components/Chakra/Stack.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyleGuide/Forms.stories.mdx
  src/components/StyleGuide/Iconography.stories.mdx
  src/components/StyleGuide/Spacing.stories.mdx
  src/components/StyleGuide/Typography.stories.mdx
  src/theme/foundations/colors.ts
Labels: Ship It

#1001 Prep for Release v1.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#999 DSD-936: Login dropdown
  CHANGELOG.md
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/Login.tsx
  src/components/Header/components/LowerNav.tsx
  src/components/Header/components/Mobile.tsx
  src/components/Header/components/UpperNav.tsx
  src/theme/components/header.ts
  src/theme/components/headerLowerNav.ts
  src/theme/components/headerMobile.ts
  src/theme/components/headerUpperNav.ts
  src/theme/foundations/radii.ts
  src/theme/index.ts
Labels: Ship It

#1003 DSD-974: Focus Trap
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Header/Header.test.tsx
  src/components/Header/components/Login.tsx
  src/theme/components/headerUpperNav.ts
Labels: Ship It

#1002 Release v1.0.0
  .github/workflows/gh-pages.yml
  .tugboat/config.yml
  CHAKRA_MIGRATION_GUIDE.md
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/components/ButtonGroup/ButtonGroup.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Chakra/Box.stories.mdx
  src/components/Chakra/Center.stories.mdx
  src/components/Chakra/Flex.stories.mdx
  src/components/Chakra/Grid.stories.mdx
  src/components/Chakra/Stack.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyleGuide/Forms.stories.mdx
  src/components/StyleGuide/Iconography.stories.mdx
  src/components/StyleGuide/Spacing.stories.mdx
  src/components/StyleGuide/Typography.stories.mdx
  src/theme/foundations/colors.ts
Labels: Release

#979 DSD-945: Fixing images rendered with a non-default aspectRation in a figure
  CHANGELOG.md
  package-lock.json
  src/components/Image/Image.stories.mdx
  src/theme/components/image.ts
Labels: Ship It

#988 DSD-949 - Heading add noSpace prop
  CHANGELOG.md
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.tsx
  src/theme/components/heading.ts
Labels: Ship It

#994 DSD-753 - Add validation for equal headers and data column
  CHANGELOG.md
  src/components/Table/Table.stories.mdx
  src/components/Table/Table.test.tsx
  src/components/Table/Table.tsx
Labels: Ship It, DON’T MERGE YET

#998 DSD-964: Accordion spacing bug
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Labels: Ship It

#1007 DSD-971: Removing tugboat and adding vercel info
  .github/PULL_REQUEST_TEMPLATE
  .tugboat/config.yml
  CHANGELOG.md
  README.md
Labels: Ship It

#1005 DSD-973: Adding SkipNavigation to Header
  CHANGELOG.md
  package-lock.json
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/theme/components/skipNavigation.ts
Labels: Ship It, Header

#1009 DSD-894: new logo variants
  CHANGELOG.md
  icons/svg/logo-apple-app-store-black.svg
  icons/svg/logo-apple-app-store-white.svg
  icons/svg/logo-clever-badge-color.svg
  icons/svg/logo-google-play-black.svg
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
Labels: Ship It

#1010 DSD-753: table data cleanup
  src/components/Table/Table.stories.mdx
Labels: Ship It

#990 DSD-956: cleanup console warnings
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Card/Card.tsx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Logo/Logo.stories.mdx
  src/components/Modal/Modal.stories.mdx
  src/components/Pagination/Pagination.stories.mdx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/Template/Template.stories.mdx
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/docs/Chakra.stories.mdx
Labels: Ship It

#1011 DSD-956: warnings on SkipNavigation story
  src/components/SkipNavigation/SkipNavigation.stories.mdx
Labels: Needs Review

#1008 DSD-975: Pinning Chakra UI to a pre-2.0 version range
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It

#980 DSD-944: Fixing Card layout when isAlignedRightActions is true
  CHANGELOG.md
  src/components/Card/Card.stories.mdx
  src/components/Card/Card.tsx
  src/theme/components/card.ts
Labels: Ship It

#1006 DSD-940: Header's SitewideAlerts component
  CHANGELOG.md
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/SitewideAlerts.test.tsx
  src/components/Header/components/SitewideAlerts.tsx
  src/components/Header/components/__snapshots__/SitewideAlerts.test.tsx.snap
  src/components/Header/headerUtils.ts
  src/theme/components/sitewideAlerts.ts
  src/theme/index.ts
Labels: Ship It, Header

#1014 DSD-948 - add hover state to icon only button
  CHANGELOG.md
  src/theme/components/button.ts
Labels: Ship It

#1016 DSD-982: Allows Buttons in the ButtonGroup to be disabled individually
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/components/ButtonGroup/ButtonGroup.stories.mdx
  src/components/ButtonGroup/ButtonGroup.tsx
Labels: Ship It
