Repository NYPL/nypl-design-system, pull requests merged in 2022-03, with the labels that each got.

#881 DSD-811: SearchBar styling fix
  CHANGELOG.md
  package-lock.json
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.tsx
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.tsx
  src/theme/components/searchBar.ts
Labels: Ship It

#882 DSD-813: Fixing mobile styling for the StructuredContent
  CHANGELOG.md
  package-lock.json
  src/theme/components/structuredContent.ts
Labels: Ship It

#884 DSD-819: Tabs log warning
  CHANGELOG.md
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.tsx
Labels: Ship It

#883 DSD-798: Updating list styles for inline
  CHANGELOG.md
  src/components/List/List.stories.mdx
  src/components/List/List.test.tsx
  src/components/List/List.tsx
  src/components/List/__snapshots__/List.test.tsx.snap
  src/theme/components/list.ts
Labels: Ship It

#885 Prep for Release 0.25.11
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/Logo/Logo.stories.mdx
  src/components/StructuredContent/StructuredContent.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
Labels: Needs Review, Release

#888 DSD-670: Fixing margin styles for the Slider component
  CHANGELOG.md
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.tsx
  src/theme/components/slider.ts
Labels: Ship It

#889 DSD-825: Updating margins for List ul and ol
  CHANGELOG.md
  src/components/List/List.stories.mdx
  src/styles/base/_03-base.scss
  src/theme/components/global.ts
  src/theme/components/list.ts
  src/theme/foundations/global.ts
Labels: Ship It

#887 DSD-828: Notification bug fixes
  CHANGELOG.md
  src/components/Notification/Notification.stories.mdx
  src/components/Notification/Notification.test.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/theme/components/notification.ts
Labels: Ship It

#890 DSD-827: Removing border and padding from fieldset
  CHANGELOG.md
  src/components/Fieldset/Fieldset.stories.mdx
  src/theme/components/fieldset.ts
Labels: Ship It

#891 DSD-733: Updating the SearchBar's placeholder
  CHANGELOG.md
  src/components/SearchBar/SearchBar.Test.tsx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.tsx
Labels: Ship It

#893 DSD-815: Open eBooks and FirstBook logos
  CHANGELOG.md
  icons/svg/logo_firstbook_color.svg
  icons/svg/logo_firstbook_color_negative.svg
  icons/svg/logo_openebooks_color.svg
  icons/svg/logo_openebooks_negative.svg
  icons/svg/logo_openebooks_wtext_color.svg
  icons/svg/logo_openebooks_wtext_negative.svg
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/LogoSvgs.tsx
  src/components/Logo/LogoTypes.tsx
  src/utils/componentCategories.ts
Labels: Ship It

#894 DSD-816: styles for Select component
  CHANGELOG.md
  src/components/Select/Select.stories.mdx
  src/theme/components/select.ts
Labels: Ship It

#895 DSD-832: Removes the .nypl-ds css class rule
  .storybook/preview-body.html
  CHAKRA_MIGRATION_GUIDE.md
  CHANGELOG.md
  README.md
  src/components/StyleGuide/Bidirectionality.stories.mdx
  src/components/Template/Template.stories.mdx
  src/components/Template/Template.tsx
  src/components/Template/__snapshots__/Template.test.tsx.snap
  src/docs/Chakra.stories.mdx
  src/styles.scss
  src/styles/base/_03-base.scss
  src/styles/base/_04-focus.scss
  src/styles/base/_place-holder.scss
  src/theme/components/global.ts
  src/theme/components/globalMixins.ts
  src/theme/components/select.ts
  src/theme/components/textInput.ts
  src/theme/foundations/global.ts
Labels: Ship It

#900 DSD-714: font stack typo
  CHANGELOG.md
  src/theme/foundations/typography.ts
Labels: Ship It

#899 DSD-864: Education section colors
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/BreadcrumbsTypes.tsx
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/IconTypes.tsx
  src/components/StyleGuide/Colors.stories.mdx
  src/theme/components/breadcrumb.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#902 DSD-864: typo on page for Style Guide Colors
  src/components/StyleGuide/Colors.stories.mdx
Labels: Ship It

#903 Prep for Release v0.25.12
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release

#908 DSD-871: Pagination bug fix, adds test
  CHANGELOG.md
  package-lock.json
  src/components/Pagination/Pagination.test.tsx
  src/components/Pagination/Pagination.tsx
Labels: Ship It

#910 Dsd 856/pagination alignment
  CHANGELOG.md
  src/components/Pagination/Pagination.stories.mdx
  src/theme/components/pagination.ts
Labels: Ship It

#907 DSD-847: Storybook Sidebar
  .storybook/main.js
  .storybook/preview.tsx
  CHANGELOG.md
  src/docs/Welcome.stories.mdx
  src/hooks/useCarouselStyles.stories.mdx
  src/utils/componentCategories.ts
Labels: Ship It

#909 DSD-860: Updating the Image's caption text to font size 12px
  CHANGELOG.md
  src/components/Image/Image.test.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/theme/components/image.ts
Labels: Ship It

#911 DSD-863: Adding mainContent id to the TemplateAppContainer and a11y guides
  .storybook/preview.tsx
  CHANGELOG.md
  package-lock.json
  src/components/AccessibilityGuide/SkipNavigation.stories.mdx
  src/components/Template/Template.stories.mdx
  src/components/Template/Template.test.tsx
  src/components/Template/Template.tsx
  src/components/Template/__snapshots__/Template.test.tsx.snap
  src/utils/componentCategories.ts
Labels: Ship It

#905 DSD-868: Checkbox JSX labels and full-width CheckboxGroup
  CHANGELOG.md
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Checkbox/Checkbox.test.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.test.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/Form/Form.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/Radio/Radio.test.tsx
  src/components/Radio/Radio.tsx
  src/components/Radio/__snapshots__/Radio.test.tsx.snap
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/theme/components/checkboxGroup.ts
  src/theme/components/global.ts
  src/theme/components/radioGroup.ts
Labels: Ship It

#912 DSD-883: A11y docs for Accordion, Slider, StructuredContent
  src/components/Accordion/Accordion.stories.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/StructuredContent/StructuredContent.stories.mdx
Labels: Ship It

#914 DSD-699: Updating the spacing for the Toggle component
  CHANGELOG.md
  package-lock.json
  src/components/Toggle/Toggle.stories.mdx
  src/components/Toggle/Toggle.test.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/theme/components/toggle.ts
Labels: Ship It

#915 DSD-877: Fixing Breadcrumbs Blogs svg arrow color
  CHANGELOG.md
  src/theme/components/breadcrumb.ts
Labels: Ship It

#916 DSD-881: Fixing the spacing between list items in the List component
  CHANGELOG.md
  src/theme/components/list.ts
Labels: Ship It

#918 DSD-858: Select arrow focus fix
  CHANGELOG.md
  src/components/Select/Select.stories.mdx
  src/theme/components/select.ts
Labels: Ship It

#919 DSD-879: Add bgcolor prop to Accordion
  CHANGELOG.md
  src/components/Accordion/Accordion.stories.mdx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionTypes.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/index.ts
  src/theme/components/accordion.ts
Labels: Ship It

#921 DSD-872: Updating the Card's image styling for mobile
  CHANGELOG.md
  src/components/Card/Card.stories.mdx
  src/components/Card/Card.tsx
  src/theme/components/card.ts
Labels: Ship It

#923 DSD-876: Hero Campaign mobile bottom spacing fix
  CHANGELOG.md
  src/theme/components/hero.ts
Labels: Ship It

#924 DSD-776: Slider stack overflow fix
  CHANGELOG.md
  package-lock.json
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.tsx
Labels: Ship It

#917 DSD-854: Updating all console warnings with NYPL branding
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Card/Card.test.tsx
  src/components/Card/Card.tsx
  src/components/CheckboxGroup/CheckboxGroup.test.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/ComponentWrapper/ComponentWrapper.tsx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/Form/Form.test.tsx
  src/components/Form/Form.tsx
  src/components/Heading/Heading.test.tsx
  src/components/Heading/Heading.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/HorizontalRule/HorizontalRule.test.tsx
  src/components/HorizontalRule/HorizontalRule.tsx
  src/components/Icons/Icon.test.tsx
  src/components/Icons/Icon.tsx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/List/List.test.tsx
  src/components/List/List.tsx
  src/components/Logo/Logo.test.tsx
  src/components/Logo/Logo.tsx
  src/components/Pagination/Pagination.test.tsx
  src/components/Pagination/Pagination.tsx
  src/components/ProgressIndicator/ProgressIndicator.test.tsx
  src/components/ProgressIndicator/ProgressIndicator.tsx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/StatusBadge/StatusBadge.test.tsx
  src/components/StatusBadge/StatusBadge.tsx
  src/components/StructuredContent/StructuredContent.test.tsx
  src/components/StructuredContent/StructuredContent.tsx
  src/components/Table/Table.test.tsx
  src/components/Table/Table.tsx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Template/Template.test.tsx
  src/components/Template/Template.tsx
  src/components/Text/Text.test.tsx
  src/components/Text/Text.tsx
  src/components/VideoPlayer/VideoPlayer.test.tsx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/hooks/tests/useNYPLTheme.test.tsx
  src/hooks/useNYPLTheme.ts
Labels: Ship It
