Repository NYPL/nypl-design-system, pull requests merged in 2022-10, with the labels that each got.

#1158 DSD-1143: hamburger icon color
  CHANGELOG.md
  icons/svg/utility-hamburger.svg
  src/components/Icons/Icon.stories.mdx
Labels: Ship It

#1159 DSD-1144: NYCDOE logo
  CHANGELOG.md
  icons/svg/logo-nycdoe-color.svg
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
Labels: Ship It

#1119 DSD-411: Tagset component
  .jest-test-results.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Icons/Icon.tsx
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/components/MultiSelect/MultiSelectListbox.tsx
  src/components/MultiSelect/MultiSelectMenuButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/MultiSelectGroup.stories.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/TagSet/TagSet.stories.mdx
  src/components/TagSet/TagSet.test.tsx
  src/components/TagSet/TagSet.tsx
  src/components/TagSet/TagSetExplore.tsx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/hooks/__tests__/useMultiSelect.test.ts
  src/hooks/useMultiSelect.stories.mdx
  src/hooks/useMultiSelect.ts
  src/index.ts
  src/theme/components/button.ts
  src/theme/components/icon.ts
  src/theme/components/multiSelect.ts
  src/theme/components/multiSelectMenuButton.ts
  src/theme/components/tagSet.ts
  src/theme/foundations/radii.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It, DON’T MERGE YET

#1143 DSD-578: AlphabetFilter Component
  CHANGELOG.md
  src/components/AlphabetFilter/AlphabetFilter.stories.mdx
  src/components/AlphabetFilter/AlphabetFilter.test.tsx
  src/components/AlphabetFilter/AlphabetFilter.tsx
  src/components/AlphabetFilter/__snapshots__/AlphabetFilter.test.tsx.snap
  src/components/ComponentWrapper/ComponentWrapper.tsx
  src/index.ts
  src/theme/components/alphabetFilter.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It, DON’T MERGE YET

#1162 1.2.0-rc v2: Fixing alphabetFilter button color issue
  package-lock.json
  package.json
  src/components/AlphabetFilter/AlphabetFilter.tsx
  src/index.ts
  src/theme/components/alphabetFilter.ts
  src/theme/index.ts
Labels: Ship It

#1165 1.2.0-rc v3: Fixing DOMParser is not defined issue
  package-lock.json
  package.json
  src/components/AudioPlayer/AudioPlayer.test.tsx
  src/components/AudioPlayer/AudioPlayer.tsx
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
Labels: Ship It

#1164 DSD-1103: dark mode button colors
  CHANGELOG.md
  src/theme/components/button.ts
  src/theme/foundations/colors.ts
Labels: Ship It, DON’T MERGE YET

#1168 DSD-1155: Add requiredLabelText to Label and TextInput components
  .jest-test-results.json
  CHANGELOG.md
  src/components/Label/Label.stories.mdx
  src/components/Label/Label.test.tsx
  src/components/Label/Label.tsx
  src/components/Label/__snapshots__/Label.test.tsx.snap
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: Ship It

#1161 1.2.0 Release Candidate
  .jest-test-results.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/AlphabetFilter/AlphabetFilter.stories.mdx
  src/components/AlphabetFilter/AlphabetFilter.test.tsx
  src/components/AlphabetFilter/AlphabetFilter.tsx
  src/components/AlphabetFilter/__snapshots__/AlphabetFilter.test.tsx.snap
  src/components/AudioPlayer/AudioPlayer.stories.mdx
  src/components/AudioPlayer/AudioPlayer.test.tsx
  src/components/AudioPlayer/AudioPlayer.tsx
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/ComponentWrapper/ComponentWrapper.tsx
  src/components/Icons/Icon.tsx
  src/components/TagSet/TagSet.stories.mdx
  src/components/TagSet/TagSet.test.tsx
  src/components/TagSet/TagSet.tsx
  src/components/TagSet/TagSetExplore.tsx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/index.ts
  src/theme/components/alphabetFilter.ts
  src/theme/components/audioPlayer.ts
  src/theme/components/button.ts
  src/theme/components/icon.ts
  src/theme/components/tagSet.ts
  src/theme/foundations/radii.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It, Release Candidate

#1169 Prep for Release v1.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#1170 Release v1.2.0
  .jest-test-results.json
  CHANGELOG.md
  icons/svg/logo-nycdoe-color.svg
  icons/svg/utility-hamburger.svg
  package-lock.json
  package.json
  src/components/AlphabetFilter/AlphabetFilter.stories.mdx
  src/components/AlphabetFilter/AlphabetFilter.test.tsx
  src/components/AlphabetFilter/AlphabetFilter.tsx
  src/components/AlphabetFilter/__snapshots__/AlphabetFilter.test.tsx.snap
  src/components/AudioPlayer/AudioPlayer.stories.mdx
  src/components/AudioPlayer/AudioPlayer.test.tsx
  src/components/AudioPlayer/AudioPlayer.tsx
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/ComponentWrapper/ComponentWrapper.tsx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/Icon.tsx
  src/components/Label/Label.stories.mdx
  src/components/Label/Label.test.tsx
  src/components/Label/Label.tsx
  src/components/Label/__snapshots__/Label.test.tsx.snap
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
  src/components/TagSet/TagSet.stories.mdx
  src/components/TagSet/TagSet.test.tsx
  src/components/TagSet/TagSet.tsx
  src/components/TagSet/TagSetExplore.tsx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/Tooltip.tsx
  src/index.ts
  src/theme/components/alphabetFilter.ts
  src/theme/components/audioPlayer.ts
  src/theme/components/button.ts
  src/theme/components/icon.ts
  src/theme/components/tagSet.ts
  src/theme/foundations/radii.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It, Release

#1171 DSD-1150: Clean Up Storybook, Update Component Version
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/hooks/useMultiSelect.ts
Labels: Ship It

#1175 DSD-1166: Improve a11y for AlphabetFilter
  CHANGELOG.md
  src/components/AlphabetFilter/AlphabetFilter.stories.mdx
  src/components/AlphabetFilter/AlphabetFilter.test.tsx
  src/components/AlphabetFilter/AlphabetFilter.tsx
  src/components/AlphabetFilter/__snapshots__/AlphabetFilter.test.tsx.snap
Labels: Ship It

#1172 DSD-1110: dark mode for overlays and switchers category
  CHANGELOG.md
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/theme/components/accordion.ts
  src/theme/components/modal.ts
  src/theme/components/tabs.ts
  src/theme/components/tooltip.ts
  src/theme/index.ts
Labels: Ship It

#1176 [DSD-1153] Adds background styles to Hero component variants
  CHANGELOG.md
  src/components/Hero/Hero.stories.mdx
  src/theme/components/hero.ts
Labels: Ship It

#1174 DSD-1163, DSD-1164: Updating hover styles for Checkbox and Radio
  CHANGELOG.md
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/Radio/Radio.tsx
  src/theme/components/checkbox.ts
  src/theme/components/global.ts
  src/theme/components/radio.ts
  src/theme/index.ts
Labels: Ship It

#1177 DSD-1039: Updating storybook to 6.5.13 to fix a few bugs.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It

#1173 DSD-1165: TagSet a11y update
  CHANGELOG.md
  src/components/TagSet/TagSet.stories.mdx
  src/components/TagSet/TagSet.test.tsx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
Labels: Ship It

#1179 Prep for Release v1.2.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/AlphabetFilter/AlphabetFilter.stories.mdx
Labels: Ship It, Release

#1182 DSD-1172: broken TOC link on Card story
  CHANGELOG.md
  src/components/Card/Card.stories.mdx
Labels: Ship It

#1183 DSD-1173: sizing of error icons
  CHANGELOG.md
  icons/svg/error-filled.svg
  icons/svg/error-outline.svg
  src/components/Icons/Icon.stories.mdx
Labels: Ship It

#1181 DSD-1154: dark mode support for new components in v1.2.0
  CHANGELOG.md
  src/components/AlphabetFilter/AlphabetFilter.stories.mdx
  src/components/AlphabetFilter/AlphabetFilter.tsx
  src/components/AudioPlayer/AudioPlayer.stories.mdx
  src/components/TagSet/TagSet.stories.mdx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/theme/components/audioPlayer.ts
  src/theme/components/tagSet.ts
  src/theme/components/videoPlayer.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#1186 DSD-1177, DSD-1178: Update Icon and Logo size docs
  CHANGELOG.md
  src/components/Icons/Icon.stories.mdx
  src/components/Logo/Logo.stories.mdx
Labels: Ship It
