Repository NYPL/nypl-design-system, pull requests merged in 2022-07, with the labels that each got.

#1068 DSD-1031 & DSD-1032: border color for Checkbox and Radio
  CHANGELOG.md
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/theme/components/checkbox.ts
  src/theme/components/radio.ts
Labels: Ship It

#1066 DSD-1045: Header component naming
  CHANGELOG.md
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderLogin.test.tsx
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/components/Header/components/HeaderLowerNav.tsx
  src/components/Header/components/HeaderMobileIconNav.tsx
  src/components/Header/components/HeaderMobileNav.test.tsx
  src/components/Header/components/HeaderMobileNav.tsx
  src/components/Header/components/HeaderMobileNavButton.test.tsx
  src/components/Header/components/HeaderMobileNavButton.tsx
  src/components/Header/components/HeaderSearchButton.test.tsx
  src/components/Header/components/HeaderSearchButton.tsx
  src/components/Header/components/HeaderSearchForm.test.tsx
  src/components/Header/components/HeaderSearchForm.tsx
  src/components/Header/components/HeaderSitewideAlerts.test.tsx
  src/components/Header/components/HeaderSitewideAlerts.tsx
  src/components/Header/components/HeaderUpperNav.tsx
  src/components/Header/components/LoginButton.tsx
  src/components/Header/components/SearchButton.tsx
  src/components/Header/components/SearchForm.tsx
  src/components/Header/components/__snapshots__/HeaderMobileNav.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderMobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSitewideAlerts.test.tsx.snap
  src/components/Header/components/__snapshots__/SitewideAlerts.test.tsx.snap
  src/components/Header/components/index.tsx
  src/components/Header/context/headerPatronContext.test.tsx
  src/components/Header/context/headerPatronContext.tsx
  src/components/Header/context/patronContext.tsx
  src/components/Header/utils/sitewideAlertsMocks.ts
Labels: Needs Review, Header

#1077 Release v1.0.5
  CHANGELOG.md
  icons/svg/action-check-circle-filled.svg
  icons/svg/action-registration.svg
  icons/svg/decorative-envelope.svg
  icons/svg/decorative-library-card.svg
  icons/svg/decorative-shopping-bag.svg
  package-lock.json
  package.json
  src/components/Button/Button.stories.mdx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/Icon.tsx
  src/components/Icons/IconSvgs.tsx
  src/components/Radio/Radio.stories.mdx
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/Colors.stories.mdx
  src/hooks/useNYPLBreakpoints.stories.mdx
  src/hooks/useNYPLBreakpoints.ts
  src/index.ts
  src/theme/components/checkbox.ts
  src/theme/components/radio.ts
Labels: Needs Review, Release

#1070 DSD-1042: Adding isLazy prop to Image component
  CHANGELOG.md
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Card/Card.test.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Grid/SimpleGrid.test.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Image/Image.stories.mdx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/StructuredContent/StructuredContent.test.tsx
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/Table/Table.test.tsx
  src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: Ship It

#1072 DSD-1038: Header Google Analytics
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Header/Header.stories.mdx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/__snapshots__/Header.test.tsx.snap
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/components/Header/components/HeaderLowerNav.tsx
  src/components/Header/components/HeaderMobileIconNav.tsx
  src/components/Header/components/HeaderMobileNav.test.tsx
  src/components/Header/components/HeaderMobileNav.tsx
  src/components/Header/components/HeaderMobileNavButton.test.tsx
  src/components/Header/components/HeaderMobileNavButton.tsx
  src/components/Header/components/HeaderSearchButton.test.tsx
  src/components/Header/components/HeaderSearchButton.tsx
  src/components/Header/components/HeaderSearchForm.test.tsx
  src/components/Header/components/HeaderSearchForm.tsx
  src/components/Header/components/HeaderUpperNav.tsx
  src/components/Header/components/__snapshots__/HeaderMobileNav.test.tsx.snap
  src/components/Header/utils/googleAnalyticsUtils.test.ts
  src/components/Header/utils/googleAnalyticsUtils.ts
  src/components/Header/utils/headerUtils.ts
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.tsx
  src/components/Pagination/Pagination.stories.mdx
  src/components/Pagination/Pagination.tsx
  src/theme/components/header/headerSearchForm.ts
Labels: Ship It, Header

#1073 DSD-1049: Adding development auth links for the Header login links
  CHANGELOG.md
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderLogin.test.tsx
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/components/Header/context/headerContext.test.tsx
  src/components/Header/context/headerContext.tsx
  src/components/Header/context/headerPatronContext.test.tsx
  src/components/Header/context/headerPatronContext.tsx
  src/components/Header/utils/headerUtils.ts
Labels: Ship It, Header

#1079 DSD-1048: Implementing padding-inline/margin-inline for RTL support
  CHANGELOG.md
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/StyleGuide/Bidirectionality.stories.mdx
  src/components/StyleGuide/ColorCard.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/docs/Chakra.stories.mdx
  src/hooks/__tests__/useCarouselStyles.test.ts
  src/hooks/useCarouselStyles.ts
  src/theme/components/breadcrumb.ts
  src/theme/components/card.ts
  src/theme/components/customTable.ts
  src/theme/components/global.ts
  src/theme/components/globalMixins.ts
  src/theme/components/heading.ts
  src/theme/components/hero.ts
  src/theme/components/horizontalRule.ts
  src/theme/components/icon.ts
  src/theme/components/image.ts
  src/theme/components/list.ts
  src/theme/components/notification.ts
  src/theme/components/select.ts
  src/theme/components/skeletonLoader.ts
  src/theme/components/slider.ts
  src/theme/components/structuredContent.ts
  src/theme/components/tabs.ts
  src/theme/components/template.ts
  src/theme/components/toggle.ts
Labels: Ship It

#1074 DSD-1050: Header timeout functions
  CHANGELOG.md
  src/components/Header/Header.tsx
  src/components/Header/utils/encoreCatalogLogOutTimer.test.ts
  src/components/Header/utils/encoreCatalogLogOutTimer.ts
Labels: Ship It, Header

#1081 DSD-1055 & DSD-1056: legacy icons for Header and Footer
  CHANGELOG.md
  icons/svg/legacy-account-filled.svg
  icons/svg/legacy-account-unfilled.svg
  icons/svg/legacy-social-facebook.svg
  icons/svg/legacy-social-instagram.svg
  icons/svg/legacy-social-twitter.svg
  icons/svg/legacy-social-youtube.svg
  src/components/Button/Button.stories.mdx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/Icon.tsx
  src/components/Icons/IconSvgs.tsx
Labels: Needs Review

#1080 DSD-1052: Initial Footer component
  CHANGELOG.md
  src/components/Footer/Footer.stories.mdx
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/__snapshots__/Footer.test.tsx.snap
  src/components/Footer/footerLinks.ts
  src/theme/components/fieldset.ts
  src/theme/components/footer.ts
  src/theme/components/globalMixins.ts
  src/theme/components/radio.ts
  src/theme/index.ts
Labels: Ship It, Footer

#1082 DSD-1058: warning icons
  CHANGELOG.md
  icons/svg/alert-warning-filled.svg
  icons/svg/alert-warning-outline.svg
  src/components/Button/Button.stories.mdx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/Icon.tsx
  src/components/Icons/IconSvgs.tsx
Labels: Ship It

#1071 DSD-1033: MultiSelect final styles
  package-lock.json
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/components/MultiSelect/MultiSelectListbox.tsx
  src/components/MultiSelect/MultiSelectMenuButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/theme/components/button.ts
  src/theme/components/multiSelect.ts
  src/theme/components/multiSelectMenuButton.ts
  src/theme/foundations/radii.ts
Labels: Ship It

#1087 Prep for Release v1.0.6
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Logo/Logo.stories.mdx
Labels: Ship It, Release

#1090 Additional Prep for Release 1.0.6
  CHANGELOG.md
Labels: Needs Review

#1083 DSD-1054: Updating SVG icons in the Footer
  CHANGELOG.md
  src/components/Footer/footerLinks.ts
Labels: Ship It, Footer

#1092 Fixes one instance where value should have been gotten from context
  src/components/Header/components/HeaderLogin.test.tsx
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderLoginButton.tsx
Labels: Ship It, Header

#1085 DSD-1064: Footer documentation
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Footer/Footer.stories.mdx
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/components/Footer/__snapshots__/Footer.test.tsx.snap
  src/components/Logo/Logo.stories.mdx
Labels: Ship It, Footer

#1093 DSD-1053: top border color for Description List
  CHANGELOG.md
  src/components/List/List.stories.mdx
  src/theme/components/list.ts
  src/theme/components/structuredContent.ts
Labels: Ship It

#1095 DSD-1069: Updating select options props in SearchBar
  CHANGELOG.md
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
Labels: Ship It

#1094 DSD-1068: Updating how rest props propagate in the Link component
  CHANGELOG.md
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.test.tsx
  src/components/Link/Link.tsx
  src/components/Link/__snapshots__/Link.test.tsx.snap
Labels: Ship It

#1096 DSD-1072: Hero secondary image layout alignment
  CHANGELOG.md
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.tsx
  src/components/Image/Image.stories.mdx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/theme/components/hero.ts
Labels: Ship It

#1091 Adds focus trap and login docs
  src/components/Header/Header.stories.mdx
Labels: Ship It, Header

#1089 DSD-1060: Header Docs
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Header/Header.stories.mdx
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/components/Header/components/HeaderLowerNav.tsx
  src/components/Header/components/HeaderMobileIconNav.tsx
  src/components/Header/components/HeaderMobileNav.tsx
  src/components/Header/components/HeaderMobileNavButton.tsx
  src/components/Header/components/HeaderSearchButton.tsx
  src/components/Header/components/HeaderUpperNav.tsx
  src/components/Link/Link.test.tsx
  src/components/Link/Link.tsx
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/components/List/List.stories.mdx
  src/components/Logo/Logo.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/theme/components/list.ts
  src/theme/components/structuredContent.ts
Labels: Ship It, Header

#1097 DSD-1077: Fixing the layout of the image in the Hero 'fiftyfifty' variant
  CHANGELOG.md
  src/components/Hero/Hero.stories.mdx
  src/theme/components/hero.ts
Labels: Needs Review

#1099 Prep for Release v1.0.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#1100 Release v1.0.7
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.tsx
  src/components/Image/Image.stories.mdx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.test.tsx
  src/components/Link/Link.tsx
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/components/List/List.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/theme/components/hero.ts
  src/theme/components/list.ts
  src/theme/components/structuredContent.ts
Labels: Release
