Repository NYPL/nypl-design-system, pull requests merged in 2022-12, with the labels that each got.

#1203 DSD-1214: color adjustments for Hero and Footer
  src/theme/components/footer.ts
  src/theme/components/hero.ts
Labels: Ship It

#1204 DSD-1212: updated md (mobile) breakpoint
  CHANGELOG.md
  src/theme/foundations/breakpoints.ts
Labels: Ship It

#1200 DSD-1205: expanding color theme object
  CHANGELOG.md
  src/components/Heading/Heading.stories.mdx
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/Colors.stories.mdx
  src/theme/foundations/colors.ts
Labels: Needs Review

#1185 DSD-1162: StyledList component
  CHANGELOG.md
  src/components/List/List.tsx
  src/components/StyledList/StyledList.stories.mdx
  src/components/StyledList/StyledList.test.tsx
  src/components/StyledList/StyledList.tsx
  src/components/StyledList/__snapshots__/StyledList.test.tsx.snap
  src/components/Text/Text.tsx
  src/index.ts
  src/theme/components/styledList.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It

#1195 DSD-1174: FeedbackBox
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/FeedbackBox/FeedbackBox.stories.mdx
  src/components/FeedbackBox/FeedbackBox.test.tsx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/FeedbackBox/__snapshots__/FeedbackBox.test.tsx.snap
  src/components/FeedbackBox/useFeedbackBoxReducer.ts
  src/components/Form/Form.tsx
  src/hooks/__tests__/useStateWithDependencies.test.tsx
  src/hooks/useStateWithDependencies.ts
  src/theme/components/feedbackBox.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It

#1210 Prep for Release v1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Icons/Icon.stories.mdx
Labels: Ship It, Release

#1213 Bugfix: Node issues
  package-lock.json
  package.json
Labels: Ship It, Release

#1207 DSD-1219: color adjustments for dark palette
  src/components/Notification/Notification.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/theme/components/global.ts
  src/theme/components/header/header.ts
  src/theme/components/header/headerLogin.ts
  src/theme/components/header/headerLowerNav.ts
  src/theme/components/header/headerSearchButton.ts
  src/theme/components/header/headerSearchForm.ts
  src/theme/components/header/headerSitewideAlerts.ts
  src/theme/components/header/headerUpperNav.ts
  src/theme/components/notification.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#1208 DSD-1215: Adding isClearableCallback prop to the TextInput component
  CHANGELOG.md
  package-lock.json
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
Labels: Ship It

#1209 DSD-1200: Adding zindex to svg icon when the select is focused
  CHANGELOG.md
  src/components/Select/Select.stories.mdx
  src/theme/components/select.ts
Labels: Ship It

#1212 DSD-1220: secondary button BG color
  CHANGELOG.md
  src/theme/components/button.ts
  src/theme/foundations/colors.ts
  src/utils/utils.ts
Labels: Ship It

#1214 Prep for Release v1.3.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Button/Button.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
Labels: Ship It, Release

#1215 Release v1.3.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Button/Button.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/theme/components/button.ts
  src/theme/components/select.ts
  src/theme/foundations/colors.ts
  src/utils/utils.ts
Labels: Ship It, Release

#1202 DSD-234: FilterBar
  .jest-test-results.json
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/FilterBar/FilterBar.stories.mdx
  src/components/FilterBar/FilterBar.stories.tsx
  src/components/FilterBar/FilterBar.test.tsx
  src/components/FilterBar/FilterBar.tsx
  src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/hooks/__tests__/useFilterBar.test.ts
  src/hooks/__tests__/useMultiSelect.test.ts
  src/hooks/useFilterBar.stories.mdx
  src/hooks/useFilterBar.ts
  src/hooks/useMultiSelect.stories.mdx
  src/hooks/useMultiSelect.ts
  src/index.ts
  src/theme/components/filterBar.ts
  src/theme/components/multiSelect.ts
  src/theme/components/multiSelectGroup.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It

#1217 DSD-1227: dark mode for v1.3.0 components
  .storybook/preview.tsx
  CHANGELOG.md
  src/components/AlphabetFilter/AlphabetFilter.stories.mdx
  src/components/AudioPlayer/AudioPlayer.stories.mdx
  src/components/Button/Button.stories.mdx
  src/components/Card/Card.stories.mdx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/FeedbackBox/FeedbackBox.stories.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/Fieldset/Fieldset.stories.mdx
  src/components/Footer/Footer.stories.mdx
  src/components/Header/Header.stories.mdx
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/Hero/Hero.stories.mdx
  src/components/HorizontalRule/HorizontalRule.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Label/Label.stories.mdx
  src/components/Notification/Notification.stories.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/Select/Select.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/StatusBadge/StatusBadge.stories.mdx
  src/components/StyledList/StyledList.stories.mdx
  src/components/Table/Table.stories.mdx
  src/components/TagSet/TagSet.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/Toggle/Toggle.stories.mdx
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/theme/components/feedbackBox.ts
  src/theme/components/styledList.ts
Labels: Ship It

#1166 MultiSelect/ FilterBar Feature Branch
  .jest-test-results.json
  CHANGELOG.md
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/FilterBar/FilterBar.stories.mdx
  src/components/FilterBar/FilterBar.stories.tsx
  src/components/FilterBar/FilterBar.test.tsx
  src/components/FilterBar/FilterBar.tsx
  src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/components/MultiSelect/MultiSelectListbox.tsx
  src/components/MultiSelect/MultiSelectMenuButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/MultiSelectGroup.stories.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/hooks/__tests__/useFilterBar.test.ts
  src/hooks/__tests__/useMultiSelect.test.ts
  src/hooks/useFilterBar.stories.mdx
  src/hooks/useFilterBar.ts
  src/hooks/useMultiSelect.stories.mdx
  src/hooks/useMultiSelect.ts
  src/index.ts
  src/theme/components/filterBar.ts
  src/theme/components/multiSelect.ts
  src/theme/components/multiSelectGroup.ts
  src/theme/components/multiSelectMenuButton.ts
  src/theme/index.ts
  src/utils/componentCategories.ts
Labels: Ship It

#1216 DSD-1217: link button styles
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/theme/components/button.ts
  src/theme/components/link.ts
  src/theme/components/select.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#1219 DSD-1224: updated color values
  CHANGELOG.md
  src/components/StyleGuide/Colors.stories.mdx
  src/theme/foundations/colors.ts
  src/utils/utils.ts
Labels: Ship It

#1220 DSD-1207, DSD-1222, DSD-1229: UI fixes for FeedbackBox
  CHANGELOG.md
  src/components/FeedbackBox/FeedbackBox.stories.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
Labels: Ship It

#1221 DSD-1238: remove deprecation warning from Link component
  CHANGELOG.md
  src/components/Link/Link.test.tsx
  src/components/Link/Link.tsx
Labels: Ship It

#1226 DSD-1239 & DSD-1244: BG color for iconOnly and text variants in Button component
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/theme/components/button.ts
Labels: Ship It

#1225 DSD-1232: improved accessibility for FeedbackBox
  CHANGELOG.md
  src/components/FeedbackBox/FeedbackBox.tsx
  src/theme/components/feedbackBox.ts
Labels: Ship It

#1223 DSD-1242: remove aria-live from HelpErerrorText
  CHANGELOG.md
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/ComponentWrapper/__snapshots__/ComponentWrapper.test.tsx.snap
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/HelperErrorText/HelperErrorText.test.tsx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/HelperErrorText/__snapshots__/HelperErrorText.test.tsx.snap
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
Labels: Ship It

#1224 DSD-1230: SR-only descriptive text for Link component
  CHANGELOG.md
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.tsx
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/theme/components/link.ts
Labels: Ship It
