Repository NYPL/nypl-design-system, pull requests merged in 2023-05, with the labels that each got.

#1306 DSD-1280: Fixes styling for clear button, updates snapshots
  CHANGELOG.md
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/theme/components/textInput.ts
Labels: Ship It

#1315 DSD-1456: Storybook7 Statusbadge
  .storybook/main.ts
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StatusBadge/StatusBadge.stories.mdx
  src/components/StatusBadge/StatusBadge.stories.tsx
  src/components/StatusBadge/StatusBadge.tsx
Labels: Needs Review

#1312 DSD-1418: A11y Guide in Storybook 7
  .storybook/main.ts
  .storybook/manager-head.html
  package-lock.json
  src/components/AccessibilityGuide/DynamicContent.mdx
  src/components/AccessibilityGuide/Links.mdx
  src/components/AccessibilityGuide/RepetitiveActions.mdx
  src/components/AccessibilityGuide/SkipNavigation.mdx
  src/components/AccessibilityGuide/SkipNavigation.stories.mdx
Labels: Ship It

#1320 Release v1.5.4
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/Select.stories.mdx
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/theme/components/select.ts
  src/theme/components/textInput.ts
Labels: Ship It, Release

#1309 DSD-1419: AlphabetFilter in Storybook 7
  .storybook/main.ts
  src/components/AlphabetFilter/AlphabetFilter.mdx
  src/components/AlphabetFilter/AlphabetFilter.stories.mdx
  src/components/AlphabetFilter/AlphabetFilter.stories.tsx
Labels: Ship It

#1308 DSD-1422: Storybook7 Breadcrumbs
  .storybook/main.ts
  package-lock.json
  src/components/Accordion/Accordion.stories.tsx
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
Labels: Ship It

#1310 DSD-1420: AudioPlayer in Storybook 7
  .storybook/main.ts
  src/components/AudioPlayer/AudioPlayer.mdx
  src/components/AudioPlayer/AudioPlayer.stories.mdx
  src/components/AudioPlayer/AudioPlayer.stories.tsx
Labels: Ship It

#1314 DSD-1430: Storybook7 Fieldset
  .storybook/main.ts
  src/components/Fieldset/Fieldset.mdx
  src/components/Fieldset/Fieldset.stories.tsx
Labels: Ship It

#1327 DSD-1426: Storybook7 Checkbox/ CheckboxGroup
  .storybook/main.ts
  src/components/Checkbox/Checkbox.mdx
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/CheckboxGroup/CheckboxGroup.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.tsx
  src/helpers/types.ts
Labels: Ship It

#1317 DSD-1427: Updating DatePicker storybook7 documentation
  .storybook/main.ts
  package-lock.json
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/DatePicker/DatePicker.tsx
Labels: Ship It

#1318 DSD-1429: Storybook7 FeedbackBox
  .storybook/main.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.stories.tsx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/index.ts
Labels: Ship It

#1321 DSD-1424: Updating Card documentation to Storybook 7
  .storybook/main.ts
  src/components/Card/Card.mdx
  src/components/Card/Card.stories.tsx
Labels: Ship It

#1323 DSD-1449: Updating ProgressIndicator documentation to Storybook 7
  .storybook/main.ts
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.tsx
  src/components/ProgressIndicator/ProgressIndicator.tsx
Labels: Ship It

#1326 DSD-1451: Storybook7 Searchbar
  .storybook/main.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.stories.tsx
Labels: Ship It

#1332 DSD-1463: Text component in Storybook 7
  .storybook/main.ts
  src/components/Text/Text.mdx
  src/components/Text/Text.stories.mdx
  src/components/Text/Text.stories.tsx
  src/components/Text/Text.tsx
Labels: Ship It

#1331 DSD-1466: VideoPlayer in Storybook 7
  .storybook/main.ts
  package-lock.json
  src/components/VideoPlayer/VideoPlayer.mdx
  src/components/VideoPlayer/VideoPlayer.stories.tsx
  src/components/VideoPlayer/VideoPlayer.tsx
Labels: Ship It

#1338 DSD-1460: Tabs in Storybook 7
  .storybook/main.ts
  src/components/Tabs/Tabs.mdx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.stories.tsx
Labels: Ship It

#1324 DSD-1437: Storybook 7 Hero documentation
  .storybook/main.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.tsx
Labels: Ship It

#1325 DSD-1441: Storybook7 Label Textinput Documentation
  .storybook/main.ts
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Label/Label.mdx
  src/components/Label/Label.stories.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.stories.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: Ship It

#1329 DSD-1459: Storybook7 Table update
  .storybook/main.ts
  src/components/Table/Table.mdx
  src/components/Table/Table.stories.tsx
Labels: Ship It

#1334 DSD-1455: Storybook 7 documentation for Slider component
  .storybook/main.ts
  src/components/Slider/Slider.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.stories.tsx
Labels: Ship It

#1335 DSD-1452: Updating Storybook documentation for Select component
  .storybook/main.ts
  src/components/Select/Select.mdx
  src/components/Select/Select.stories.mdx
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.tsx
Labels: Ship It

#1336 DSD-1445: Updating Storybook documentation for Modal component
  .storybook/main.ts
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.stories.tsx
Labels: Ship It

#1337 DSD-1462: Updating Storybook documentation for Template component
  .storybook/main.ts
  src/components/Template/Template.mdx
  src/components/Template/Template.stories.mdx
  src/components/Template/Template.stories.tsx
  src/components/Template/Template.tsx
Labels: Ship It

#1339 DSD-1428: Storybook 7 Dev Guide docs
  .storybook/main.ts
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/DevelopmentGuide/SupportingDarkMode.mdx
Labels: Ship It

#1344 DSD-1454: Updating Storybook documentation for SkipNavigation component
  .storybook/main.ts
  src/components/SkipNavigation/SkipNavigation.mdx
  src/components/SkipNavigation/SkipNavigation.stories.tsx
Labels: Ship It

#1316 DSD-1423: Button and ButtonGroup in Storybook 7
  .storybook/main.ts
  package-lock.json
  src/components/Button/Button.mdx
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/ButtonGroup/ButtonGroup.mdx
  src/components/ButtonGroup/ButtonGroup.stories.mdx
  src/components/ButtonGroup/ButtonGroup.stories.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
Labels: Ship It

#1341 DSD-1461: TagSet in Storybook 7
  .storybook/main.ts
  src/components/TagSet/TagSet.mdx
  src/components/TagSet/TagSet.stories.mdx
  src/components/TagSet/TagSet.stories.tsx
  src/components/TagSet/TagSetExplore.tsx
Labels: Ship It

#1346 DSD-1453: SkeletonLoader in Storybook 7
  .storybook/main.ts
  src/components/SkeletonLoader/SkeletonLoader.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.tsx
  src/components/SkeletonLoader/SkeletonLoader.tsx
Labels: Ship It

#1348 DSD-1447: Notification in Storybook 7
  .storybook/main.ts
  src/components/Notification/Notification.mdx
  src/components/Notification/Notification.stories.mdx
  src/components/Notification/Notification.stories.tsx
  src/components/Notification/Notification.tsx
Labels: Ship It

#1330 Updating Storybook documentation for Tooltip component
  .storybook/main.ts
  src/components/Tooltip/Tooltip.mdx
  src/components/Tooltip/Tooltip.stories.mdx
  src/components/Tooltip/Tooltip.stories.tsx
Labels: Ship It

#1333 DSD-1464: Storybook 7 Toggle
  .storybook/main.ts
  src/components/Toggle/Toggle.mdx
  src/components/Toggle/Toggle.stories.mdx
  src/components/Toggle/Toggle.stories.tsx
  src/components/Toggle/Toggle.tsx
Labels: Ship It

#1340 DSD-1439: Storybook 7 Icon documentation
  .storybook/main.ts
  src/components/Button/Button.stories.tsx
  src/components/Icons/Icon.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/Icon.stories.tsx
  src/components/Icons/Icon.tsx
  src/components/Icons/IconColors.tsx
  src/components/Icons/IconNames.tsx
  src/components/Icons/iconVariables.ts
Labels: Ship It

#1345 DSD-1457: Updating Storybook documentation for StructuredContent component
  .storybook/main.ts
  src/components/StructuredContent/StructuredContent.mdx
  src/components/StructuredContent/StructuredContent.stories.mdx
  src/components/StructuredContent/StructuredContent.stories.tsx
Labels: Ship It

#1349 DSD-1436: HelperErrorText in Storybook 7
  .storybook/main.ts
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/HelperErrorText/HelperErrorText.stories.tsx
Labels: Ship It

#1343 DSD-1450: Storybook 7 Radio & RadioGroup
  .storybook/main.ts
  package-lock.json
  src/components/Radio/Radio.mdx
  src/components/Radio/Radio.stories.mdx
  src/components/Radio/Radio.stories.tsx
  src/components/RadioGroup/RadioGroup.mdx
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.stories.tsx
Labels: Ship It

#1347 DSD-1446: Updating Storybook documentation for MultiSelect and MultiSelectGroup
  .storybook/main.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
Labels: Ship It

#1354 DSD-1440: Updating Storybook documentation for Image component
  .storybook/main.ts
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.mdx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.tsx
Labels: Ship It

#1350 DSD-1435: Heading in Storybook 7
  .storybook/main.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.stories.mdx
  src/components/Heading/Heading.stories.tsx
  src/components/Heading/Heading.tsx
Labels: Ship It

#1353 DSD-1442: Updating Storybook documentation for Link component
  .storybook/main.ts
  src/components/Link/Link.mdx
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.tsx
Labels: Ship It

#1328 DSD-1458: Styleguide docs to storybook7
  .storybook/main.ts
  .storybook/preview-body.html
  src/components/AccessibilityGuide/DynamicContent.mdx
  src/components/StyleGuide/Bidirectionality.mdx
  src/components/StyleGuide/Breakpoints.mdx
  src/components/StyleGuide/Buttons.mdx
  src/components/StyleGuide/Buttons.stories.mdx
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/Colors.mdx
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyleGuide/Forms.mdx
  src/components/StyleGuide/Iconography.mdx
  src/components/StyleGuide/Spacing.mdx
  src/components/StyleGuide/Typography.mdx
  src/theme/foundations/colors.ts
  src/utils/colorUtils.ts
Labels: Ship It

#1356 DSD-1433: SimpleGrid in Storybook 7
  .storybook/main.ts
  src/components/Grid/SimpleGrid.mdx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Grid/SimpleGrid.stories.tsx
  src/components/Grid/SimpleGrid.tsx
Labels: Ship It

#1357 DSD-1432: Form in Storybook 7
  .storybook/main.ts
  src/components/Form/Form.mdx
  src/components/Form/Form.stories.mdx
  src/components/Form/Form.stories.tsx
Labels: Ship It

#1342 DSD-1444: Updating Storybook documentation for Logo component
  .storybook/main.ts
  icons/svg/logo-simplye-black.svg
  icons/svg/logo-simplye-color.svg
  icons/svg/logo-simplye-white.svg
  src/components/Logo/Logo.mdx
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.stories.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/logoVariables.ts
  vite.config.ts
Labels: Ship It

#1358 DSD-1487: custom text styles for Storybook 7
  .storybook/preview-body.html
Labels: Ship It

#1359 DSD-1489: improved story names
  src/components/Accordion/Accordion.stories.tsx
  src/components/Autosuggest/Autosuggest.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Button/Button.mdx
  src/components/Button/Button.stories.mdx
  src/components/Button/Button.stories.tsx
  src/components/Card/Card.mdx
  src/components/Card/Card.stories.tsx
  src/components/Checkbox/Checkbox.mdx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/CheckboxGroup/CheckboxGroup.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.tsx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Icons/Icon.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/Icon.stories.tsx
  src/components/Icons/IconNames.tsx
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.tsx
  src/components/List/List.mdx
  src/components/List/List.stories.mdx
  src/components/List/List.stories.tsx
  src/components/Logo/Logo.mdx
  src/components/Logo/Logo.stories.tsx
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.tsx
  src/components/Radio/Radio.mdx
  src/components/Radio/Radio.stories.tsx
  src/components/RadioGroup/RadioGroup.mdx
  src/components/RadioGroup/RadioGroup.stories.tsx
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/Select/Select.stories.mdx
  src/components/SkeletonLoader/SkeletonLoader.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.tsx
  src/components/SkipNavigation/SkipNavigation.mdx
  src/components/SkipNavigation/SkipNavigation.stories.tsx
  src/components/Slider/Slider.stories.mdx
  src/components/StructuredContent/StructuredContent.stories.tsx
  src/components/Table/Table.mdx
  src/components/Table/Table.stories.tsx
  src/components/Template/Template.mdx
  src/components/Template/Template.stories.tsx
  src/components/TextInput/TextInput.stories.mdx
  src/components/Tooltip/Tooltip.mdx
  src/components/Tooltip/Tooltip.stories.tsx
Labels: Ship It
