Repository NYPL/nypl-design-system, pull requests merged in 2023-09, with the labels that each got.

#1413 DSD-1571: NYC Public Schools logo
  CHANGELOG.md
  icons/svg/logo-nycps-black.svg
  icons/svg/logo-nycps-color.svg
  icons/svg/logo-nycps-white.svg
  src/components/Icons/Icon.mdx
  src/components/Logo/Logo.mdx
  src/components/Logo/LogoSvgs.tsx
  src/components/Logo/logoVariables.ts
Labels: Ship It

#1414 DSD-1557: sun and moon icons
  CHANGELOG.md
  icons/svg/moon-crescent.svg
  icons/svg/sun-full.svg
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconVariables.ts
Labels: Ship It

#1391 Reno 3617/social media components
  .gitignore
  src/components/Link/Link.tsx
  src/components/SocialMediaLinks/SocialMediaLinks.mdx
  src/components/SocialMediaLinks/SocialMediaLinks.stories.tsx
  src/components/SocialMediaLinks/SocialMediaLinks.test.tsx
  src/components/SocialMediaLinks/SocialMediaLinks.tsx
  src/components/SocialMediaLinks/SocialMediaLinksUtils.ts
  src/components/SocialMediaLinks/__snapshots__/SocialMediaLinks.test.tsx.snap
  src/theme/components/socialmedialinks.ts
  src/theme/index.ts
Labels: Ship It, DON’T MERGE YET

#1415 DSD-1518: Adding/updating some tests that were missing
  src/components/Text/Text.test.tsx
  src/components/Text/Text.tsx
  src/components/Text/__snapshots__/Text.test.tsx.snap
Labels: Ship It

#1416 hotfix: breadcrumb fontsize for older design token value
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/theme/foundations/typography.ts
Labels: Ship It

#1417 Prep for Release v1.7.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Icons/Icon.mdx
Labels: Ship It, Release

#1418 Release v1.7.3
  CHANGELOG.md
  icons/svg/logo-nycps-black.svg
  icons/svg/logo-nycps-color.svg
  icons/svg/logo-nycps-white.svg
  icons/svg/moon-crescent.svg
  icons/svg/sun-full.svg
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconVariables.ts
  src/components/Logo/Logo.mdx
  src/components/Logo/LogoSvgs.tsx
  src/components/Logo/logoVariables.ts
  src/theme/foundations/typography.ts
Labels: Ship It, Release

#1424 Updating documentation and links to better reference the v2 update
  .github/workflows/gh-pages.yml
  .github/workflows/static.yml
  CHAKRA_MIGRATION_GUIDE.md
  README.md
  package.json
  src/components/TagSet/TagSet.mdx
  src/theme/foundations/colors.ts
Labels: Ship It, Questions

#1425 Prep for Release v2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Accordion/Accordion.mdx
  src/components/AlphabetFilter/AlphabetFilter.mdx
  src/components/AudioPlayer/AudioPlayer.mdx
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Button/Button.mdx
  src/components/Card/Card.mdx
  src/components/Checkbox/Checkbox.mdx
  src/components/DatePicker/DatePicker.mdx
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/Fieldset/Fieldset.mdx
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/Hero/Hero.mdx
  src/components/Image/Image.mdx
  src/components/Label/Label.mdx
  src/components/Link/Link.mdx
  src/components/Modal/Modal.mdx
  src/components/MultiSelect/MultiSelect.mdx
  src/components/Notification/Notification.mdx
  src/components/Pagination/Pagination.mdx
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/Radio/Radio.mdx
  src/components/SearchBar/SearchBar.mdx
  src/components/Select/Select.mdx
  src/components/Slider/Slider.mdx
  src/components/SocialMediaLinks/SocialMediaLinks.mdx
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StructuredContent/StructuredContent.mdx
  src/components/StyledList/StyledList.mdx
  src/components/Table/Table.mdx
  src/components/Tabs/Tabs.mdx
  src/components/TagSet/TagSet.mdx
  src/components/Text/Text.mdx
  src/components/TextInput/TextInput.mdx
  src/components/Toggle/Toggle.mdx
  src/components/Tooltip/Tooltip.mdx
  src/components/VideoPlayer/VideoPlayer.mdx
Labels: Ship It, Release

#1427 Prep for Release v2.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#1428 Release v2.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release

#1429 Remove some files from storybook
  CHANGELOG.md
  src/components/FilterBar/FilterBar.md
  src/components/FilterBar/FilterBar.stories-temp-remove.tsx
  src/components/MultiSelect/MultiSelect.md
  src/components/MultiSelect/MultiSelect.stories-temp-remove.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.md
  src/components/MultiSelectGroup/MultiSelectGroup.stories-temp-remove.tsx
  src/hooks/useFilterBar.md
  src/hooks/useMultiSelect.md
Labels: Needs Review

#1430 Storybook sidebar update
  CHANGELOG.md
  src/components/FilterBar/FilterBar.md
  src/components/FilterBar/FilterBar.stories-temp-remove.tsx
  src/components/MultiSelect/MultiSelect.md
  src/components/MultiSelect/MultiSelect.stories-temp-remove.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.md
  src/components/MultiSelectGroup/MultiSelectGroup.stories-temp-remove.tsx
  src/hooks/useFilterBar.md
  src/hooks/useMultiSelect.md
Labels: Needs Review
