Repository NYPL/nypl-design-system, pull requests merged in 2023-11, with the labels that each got.

#1457 DSD-1618: autoComplete prop for TextInput
  CHANGELOG.md
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/TextInput.stories.tsx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/TextInput/textInputChangelogData.ts
Labels: Ship It

#1456 DSD-1520: Add sizeBasedOn prop to Logo
  CHANGELOG.md
  src/components/Logo/Logo.mdx
  src/components/Logo/Logo.stories.tsx
  src/components/Logo/Logo.test.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/__snapshots__/Logo.test.tsx.snap
  src/components/Logo/logoChangelogData.ts
  src/components/Logo/logoVariables.ts
  src/theme/components/logo.ts
Labels: Ship It

#1452 DSD-1612: Updating Chakra UI to max version of 1.8.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It

#1454 DSD-1569: Updating layout for Hero campaign variant
  src/components/Hero/Hero.mdx
  src/components/Hero/heroChangelogData.ts
  src/theme/components/hero.ts
Labels: Ship It

#1455 DSD-1604: Updating the getSectionColors function to return the dark mode colors
  src/__tests__/utils/getSectionColors.test.ts
  src/components/NewsletterSignup/NewsletterSignup.test.tsx
  src/helpers/getSectionColors.ts
  src/helpers/types.ts
  src/theme/components/newsletterSignup.ts
  src/utils/getSectionColors.ts
Labels: Ship It

#1459 Prep for Release v2.1.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Hero/Hero.mdx
  src/components/Hero/heroChangelogData.ts
  src/components/Logo/Logo.mdx
  src/components/Logo/logoChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/textInputChangelogData.ts
Labels: Ship It, Release

#1458 DSD-1607: Updates zIndex for searchbar select icon
  CHANGELOG.md
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/theme/components/searchBar.ts
Labels: Ship It

#1461 DSD-624: hasVisitedState prop
  CHANGELOG.md
  src/components/Link/Link.mdx
  src/components/Link/Link.tsx
  src/components/Link/linkChangelogData.ts
  src/theme/components/link.ts
Labels: Ship It

#1464 DSD-1590: NYPL color design tokens in DC logo
  CHANGELOG.md
  icons/svg/logo-digital-collections-black.svg
  src/components/Logo/Logo.mdx
  src/components/Logo/logoChangelogData.ts
Labels: Needs Review

#1462 DSD-1630: Adding and passing down isLazy from Card to its Image component
  CHANGELOG.md
  src/components/Card/Card.mdx
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.tsx
  src/components/Card/cardChangelogData.ts
  src/components/Slider/Slider.mdx
Labels: Ship It
