Repository NYPL/nypl-design-system, pull requests merged in 2023-12, with the labels that each got.

#1469 DSD-1633: spacing for FeaturedContent
  CHANGELOG.md
  src/components/FeaturedContent/FeaturedContent.mdx
  src/components/FeaturedContent/FeaturedContent.stories.tsx
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/theme/components/featuredContent.ts
Labels: Ship It

#1470 DSD-1634 & DSD-1100: campaign hero spacing and background image styles
  CHANGELOG.md
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Hero/heroChangelogData.ts
  src/theme/components/hero.ts
Labels: Needs Review

#1465 DSD-1521: Add sizeBasedOn prop to Image
  CHANGELOG.md
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Image/imageChangelogData.ts
  src/components/Logo/Logo.stories.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/logoVariables.ts
  src/helpers/types.ts
  src/theme/components/image.ts
Labels: Ship It

#1473 Prep for Release v2.1.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/AlphabetFilter/AlphabetFilter.mdx
  src/components/AlphabetFilter/alphabetFilterChangelogData.ts
  src/components/AudioPlayer/AudioPlayer.mdx
  src/components/AudioPlayer/audioPlayerChangelogData.ts
  src/components/Card/Card.mdx
  src/components/Card/cardChangelogData.ts
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/FeaturedContent/FeaturedContent.mdx
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/heroChangelogData.ts
  src/components/Image/Image.mdx
  src/components/Image/imageChangelogData.ts
  src/components/Link/Link.mdx
  src/components/Link/linkChangelogData.ts
  src/components/List/List.mdx
  src/components/List/listChangelogData.ts
  src/components/Logo/Logo.mdx
  src/components/Logo/logoChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/components/Notification/Notification.mdx
  src/components/Notification/notificationChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/StructuredContent/StructuredContent.mdx
  src/components/StructuredContent/structuredContentChangelogData.ts
  src/components/Text/Text.mdx
  src/components/Text/textChangelogData.ts
  src/components/VideoPlayer/VideoPlayer.mdx
  src/components/VideoPlayer/videoPlayerChangelogData.ts
Labels: Ship It, Release

#1471 DSD-1637: Update Content Display Chakra
  package-lock.json
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/HelperErrorText/helperErrorTextChangelogData.ts
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StatusBadge/StatusBadge.tsx
  src/components/StatusBadge/statusBadgeChangelogData.ts
  src/theme/components/helperErrorText.ts
  src/theme/components/statusBadge.ts
Labels: Ship It
