Repository NYPL/nypl-design-system, pull requests merged in 2023-10, with the labels that each got.

#1432 DSD-1581: better aria-label values for Slider
  CHANGELOG.md
  src/components/Slider/Slider.mdx
  src/components/Slider/Slider.stories.tsx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
Labels: Needs Review

#1421 DSD-1578: Datepicker fix focus
  CHANGELOG.md
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/DatePicker.tsx
Labels: Ship It, Questions

#1435 DSD-1598: updated link patterns in FeedbackBox
  CHANGELOG.md
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
Labels: Ship It

#1431 DSD-1281: Fix Hero backgroundColor/foregroundColor issue
  CHANGELOG.md
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
Labels: Ship It

#1433 DSD-1577: helper text association
  CHANGELOG.md
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/TextInput.stories.tsx
  src/components/TextInput/TextInput.tsx
  src/utils/utils.ts
Labels: Needs Review

#1436 DSD-1603: component changelogs
  CHANGELOG.md
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/heroChangelogData.ts
  src/components/Slider/Slider.mdx
  src/components/Slider/sliderChangelogData.ts
  src/utils/ComponentChangelogTable.tsx
Labels: Needs Review

#1434 DR-2525 FeaturedContent Component
  .jest-test-results.json
  CHANGELOG.md
  src/components/FeaturedContent/FeaturedContent.mdx
  src/components/FeaturedContent/FeaturedContent.stories.tsx
  src/components/FeaturedContent/FeaturedContent.test.tsx
  src/components/FeaturedContent/FeaturedContent.tsx
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/index.ts
  src/theme/components/featuredContent.ts
  src/theme/index.ts
Labels: Ship It

#1422 RENO-3681: NewsletterSignup Component
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/NewsletterSignup.stories.tsx
  src/components/NewsletterSignup/NewsletterSignup.test.tsx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/helpers/getSectionColors.ts
  src/helpers/types.ts
  src/hooks/useStateWithDependencies.ts
  src/index.ts
  src/theme/components/newsletterSignup.ts
  src/theme/index.ts
Labels: Ship It

#1442 Release v2.1.0
  .jest-test-results.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/FeaturedContent/FeaturedContent.mdx
  src/components/FeaturedContent/FeaturedContent.stories.tsx
  src/components/FeaturedContent/FeaturedContent.test.tsx
  src/components/FeaturedContent/FeaturedContent.tsx
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Hero/heroChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/NewsletterSignup.stories.tsx
  src/components/NewsletterSignup/NewsletterSignup.test.tsx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/components/Slider/Slider.mdx
  src/components/Slider/Slider.stories.tsx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/Slider/sliderChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/TextInput.stories.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/textInputChangelogData.ts
  src/helpers/getSectionColors.ts
  src/helpers/types.ts
  src/hooks/useStateWithDependencies.ts
  src/index.ts
  src/theme/components/featuredContent.ts
  src/theme/components/newsletterSignup.ts
  src/theme/index.ts
  src/utils/ComponentChangelogTable.tsx
  src/utils/utils.ts
Labels: Ship It, Release

#1439 DSD-1606: tabindex for FeedbackBox and NewsletterSignup
  CHANGELOG.md
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
Labels: Ship It

#1445 DSD-1572: deprecate secondary and fiftyFifty variants for Hero
  CHANGELOG.md
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/heroChangelogData.ts
Labels: Ship It

#1449 DSD-1614: Upgrading to Storybook v7.5.1
  .storybook/main.ts
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Needs Review

#1450 Prep for Release v2.1.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/heroChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/components/TextInput/TextInput.mdx
Labels: Ship It, Release
