Repository NYPL/nypl-design-system, pull requests merged in 2023-03, with the labels that each got.

#1254 Prep for Release 1.4.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Logo/Logo.stories.mdx
  src/components/Slider/Slider.stories.mdx
Labels: Release

#1255 Release v1.4.2
  CHANGELOG.md
  README.md
  icons/svg/logo-digital-collections-black.svg
  icons/svg/logo-digital-collections-white.svg
  package-lock.json
  package.json
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
Labels: Ship It, Release

#1256 DSD-1300: Supporting Dark Mode docs
  .storybook/preview-body.html
  .storybook/preview.tsx
  CHANGELOG.md
  src/components/DevelopmentGuide/SupportingDarkMode.stories.mdx
  src/utils/componentCategories.ts
Labels: Needs Review

#1258 DSD-1324: Design Token docs
  CHANGELOG.md
  src/components/DevelopmentGuide/DesignTokens.stories.mdx
  src/components/DevelopmentGuide/SupportingDarkMode.stories.mdx
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyleGuide/DesignTokens.stories.mdx
  src/components/StyleGuide/Spacing.stories.mdx
  src/components/StyleGuide/Typography.stories.mdx
  src/utils/componentCategories.ts
Labels: Ship It

#1233 DSD-1274: updated hex value for link primary
  CHANGELOG.md
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/Colors.stories.mdx
  src/theme/foundations/colors.ts
Labels: Ship It, DON’T MERGE YET

#1218 DSD-1211: visited state for Link component
  CHANGELOG.md
  src/components/Link/Link.stories.mdx
  src/theme/components/link.ts
  src/theme/foundations/colors.ts
Labels: Ship It, DON’T MERGE YET

#1260 DSD-1342: dark mode colors for Announcement Notification
  src/components/Notification/Notification.tsx
  src/theme/components/notification.ts
Labels: Ship It

#1261 DSD-1241: dark mode colors for SkipNavigation component
  src/theme/components/skipNavigation.ts
Labels: Ship It

#1262 DSD-1354: dark mode colors on FilterBar story page
  src/components/FilterBar/FilterBar.stories.mdx
  src/components/FilterBar/FilterBar.stories.tsx
Labels: Ship It

#1263 DSD-1346: hover state colors for Breadcrumbs in dark mode
  src/theme/components/breadcrumb.ts
Labels: Ship It

#1264 DSD-1347: dark mode styles for Primary Hero bg image
  src/theme/components/hero.ts
Labels: Ship It

#1266 DSD-1349: dark mode styles for MultiSelect scrollbar
  src/theme/components/multiSelect.ts
Labels: Ship It

#1265 DSD-1348: dark mode colors for Header
  src/theme/components/header/header.ts
  src/theme/components/header/headerLogin.ts
  src/theme/components/header/headerLoginButton.ts
  src/theme/components/header/headerMobileNav.ts
  src/theme/components/header/headerSearchButton.ts
  src/theme/components/header/headerSearchForm.ts
  src/theme/components/header/headerSitewideAlerts.ts
  src/theme/components/header/headerUpperNav.ts
Labels: Needs Review

#1269 DSD-1325: secondary button background color
  CHANGELOG.md
  src/components/Button/Button.stories.mdx
  src/theme/components/button.ts
Labels: Ship It

#1271 DSD-1318: image height for Hero campaign and 5050
  CHANGELOG.md
  src/components/Hero/Hero.stories.mdx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/theme/components/hero.ts
Labels: Needs Review

#1273 DSD-1383: remove Color Mode page
  CHANGELOG.md
  src/components/StyleGuide/ColorMode.stories.mdx
Labels: Ship It

#1280 DSD-1343: Skip Nav v1 link
  src/components/SkipNavigation/SkipNavigation.stories.mdx
Labels: Ship It

#1286 Fixing multiselect and header tests :shrug:
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
Labels: Ship It

#1281 DSD-1336: Updating aria labels for Tabs mobile next/prev buttons
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Labels: Ship It, Questions
