Repository NYPL/nypl-design-system, pull requests merged in 2023-04, with the labels that each got.

#1288 DSD-1395: Docs on npm link and install
  README.md
Labels: Needs Review

#1287 DSD-1407: NYCDOE logo variants
  CHANGELOG.md
  icons/svg/logo-nycdoe-black.svg
  icons/svg/logo-nycdoe-white.svg
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
Labels: Needs Review

#1291 Prep for Release v1.5.2
  CHANGELOG.md
  src/components/Logo/Logo.stories.mdx
  src/components/Tabs/Tabs.stories.mdx
  src/hooks/useCloseDropDown.stories.mdx
  src/index.ts
Labels: Needs Review, Release

#1292 Release v1.5.2
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  icons/svg/logo-nycdoe-black.svg
  icons/svg/logo-nycdoe-white.svg
  package-lock.json
  package.json
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/components/Header/components/HeaderMobileNavButton.tsx
  src/components/Header/components/HeaderSearchButton.tsx
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/components/SkipNavigation/SkipNavigation.stories.mdx
  src/components/Tabs/Tabs.stories.mdx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/hooks/__tests__/useCloseDropDown.test.tsx
  src/hooks/useCloseDropDown.stories.mdx
  src/hooks/useCloseDropDown.ts
  src/index.ts
Labels: Ship It, Release

#1290 DSD-1398: Update rel attribute for external Link type
  CHANGELOG.md
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.tsx
  src/components/Link/__snapshots__/Link.test.tsx.snap
Labels: Needs Review

#1296 DSD-1382: Fix typo in Slider docs
  src/components/Slider/Slider.stories.mdx
Labels: Ship It

#1294 DSD-1386 & DSD-1388: new grays and better dark mode color values
  CHANGELOG.md
  src/components/DatePicker/_DatePicker.scss
  src/components/DevelopmentGuide/DesignTokens.stories.mdx
  src/components/FeedbackBox/FeedbackBox.stories.mdx
  src/components/Footer/Footer.stories.mdx
  src/components/Header/Header.stories.mdx
  src/components/List/List.stories.mdx
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyledList/StyledList.stories.mdx
  src/components/Toggle/Toggle.stories.mdx
  src/theme/components/feedbackBox.ts
  src/theme/components/footer.ts
  src/theme/components/global.ts
  src/theme/components/header/headerSearchForm.ts
  src/theme/components/list.ts
  src/theme/components/styledList.ts
  src/theme/components/tabs.ts
  src/theme/components/toggle.ts
  src/theme/foundations/colors.ts
Labels: Needs Review

#1284 DSD-1390: Vite update
  .eslintrc
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
  .gitignore
  .jest-test-results.json
  .nvmrc
  .storybook/main.cjs
  CHANGELOG.md
  README.md
  gulpfile.js
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/fileMock.ts
  src/__tests__/setup.ts
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/ComponentWrapper/__snapshots__/ComponentWrapper.test.tsx.snap
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/Header/components/HeaderSearchForm.test.tsx
  src/components/Header/components/__snapshots__/HeaderMobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/HelperErrorText/__snapshots__/HelperErrorText.test.tsx.snap
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap
  src/components/Radio/__snapshots__/Radio.test.tsx.snap
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/SkeletonLoader/__snapshots__/SkeletonLoader.test.tsx.snap
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/components/Tooltip/Tooltip.test.tsx
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
  src/docs/Chakra.stories.mdx
  src/index.ts
  src/resources.scss
  src/styles.scss
  src/styles/_01-breakpoints.scss
  src/styles/base/_02-mixins.scss
  src/styles/space/_space-inline.scss
  src/styles/space/_space-inset.scss
  src/styles/space/_space-stack.scss
  src/theme/foundations/colors.ts
  tsconfig.json
  tsconfig.node.json
  tsdx.config.js
  vite.config.ts
Labels: Needs Review

#1299 DSD-1405: Adds Audio/Video Accessibility Guide
  .eslintrc.js
  CHANGELOG.md
  src/components/AccessibilityGuide/AudioAndVideo.stories.mdx
  src/utils/componentCategories.ts
Labels: Ship It

#1295 [DSD-1396] Allow external clearing of TextInput's value.
  CHANGELOG.md
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: Ship It

#1283 DSD-1334: Updating DOM so that the tooltip is accessible on every breadcrumb link
  CHANGELOG.md
  package-lock.json
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/theme/components/breadcrumb.ts
  src/utils/utils.ts
Labels: Ship It

#1303 DSD-1469: Pinterest and SoundCloud icons
  CHANGELOG.md
  icons/svg/social-pinterest.svg
  icons/svg/social-soundcloud.svg
  package-lock.json
  src/components/Button/Button.stories.mdx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/IconNames.tsx
  src/components/Icons/IconSvgs.tsx
Labels: Needs Review

#1304 Prep for Release 1.5.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/FeedbackBox/FeedbackBox.stories.mdx
  src/components/Footer/Footer.stories.mdx
  src/components/Header/Header.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Link/Link.stories.mdx
  src/components/List/List.stories.mdx
  src/components/Slider/Slider.stories.mdx
  src/components/StyledList/StyledList.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/Toggle/Toggle.stories.mdx
Labels: Ship It, Release

#1305 Release v1.5.3
  .eslintrc.js
  CHANGELOG.md
  icons/svg/social-pinterest.svg
  icons/svg/social-soundcloud.svg
  package-lock.json
  package.json
  src/components/AccessibilityGuide/AudioAndVideo.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/components/Button/Button.stories.mdx
  src/components/DatePicker/_DatePicker.scss
  src/components/DevelopmentGuide/DesignTokens.stories.mdx
  src/components/FeedbackBox/FeedbackBox.stories.mdx
  src/components/Footer/Footer.stories.mdx
  src/components/Grid/SimpleGrid.stories.mdx
  src/components/Header/Header.stories.mdx
  src/components/Icons/Icon.stories.mdx
  src/components/Icons/IconNames.tsx
  src/components/Icons/IconSvgs.tsx
  src/components/Link/Link.stories.mdx
  src/components/Link/Link.tsx
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/components/List/List.stories.mdx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Slider/Slider.stories.mdx
  src/components/StyleGuide/Colors.stories.mdx
  src/components/StyledList/StyledList.stories.mdx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/Toggle/Toggle.stories.mdx
  src/theme/components/breadcrumb.ts
  src/theme/components/feedbackBox.ts
  src/theme/components/footer.ts
  src/theme/components/global.ts
  src/theme/components/header/headerSearchForm.ts
  src/theme/components/list.ts
  src/theme/components/styledList.ts
  src/theme/components/tabs.ts
  src/theme/components/toggle.ts
  src/theme/foundations/colors.ts
  src/utils/componentCategories.ts
  src/utils/utils.ts
Labels: Ship It, Release

#1307 DSD-1438: HorizontalRule in Storybook 7
  .storybook/main.ts
  package-lock.json
  src/components/HorizontalRule/HorizontalRule.mdx
  src/components/HorizontalRule/HorizontalRule.stories.tsx
  src/utils/componentCategories.ts
Labels: Needs Review
