Repository NYPL/nypl-design-system, pull requests merged in 2023-02, with the labels that each got.

#1120 DSD-1101: Header - Adds the third radio button for searching
  CHANGELOG.md
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderLogin.test.tsx
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/components/Header/components/HeaderSearchForm.test.tsx
  src/components/Header/components/HeaderSearchForm.tsx
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Header/utils/headerUtils.test.ts
  src/components/Header/utils/headerUtils.ts
  src/theme/components/header/headerLogin.ts
  src/theme/components/header/headerSearchForm.ts
Labels: Ship It, DON’T MERGE YET, Header

#1227 DSD-1206 truncate breadcrumb text if beyond 40 characters
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/utils/utils.ts
Labels: Ship It

#1236 DSD-1231: FeedbackBox onSubmit doc update
  CHANGELOG.md
  src/components/FeedbackBox/FeedbackBox.stories.mdx
Labels: Ship It

#1239 DSD-1287: Add ESC action and test to MultiSelectDialog component
  .jest-test-results.json
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/hooks/useFilterBar.stories.mdx
  src/hooks/useMultiSelect.stories.mdx
Labels: Ship It

#1240 DSD-1201: Passing down more props from SearchBar to TextInput
  CHANGELOG.md
  src/components/SearchBar/SearchBar.stories.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
Labels: Ship It

#1246 DSD-1297: Add ArgsTable To FilterBar Storybook
  src/components/FilterBar/FilterBar.stories.mdx
Labels: Ship It

#1244 DSD-1272: Dynamic Content a11y guide
  CHANGELOG.md
  src/components/AccessibilityGuide/DynamicContent.stories.mdx
  src/utils/componentCategories.ts
Labels: Needs Review

#1247 DSD-1271: HelperErrorText better aria-live rendering
  CHANGELOG.md
  src/components/AlphabetFilter/__snapshots__/AlphabetFilter.test.tsx.snap
  src/components/AudioPlayer/AudioPlayer.stories.mdx
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/Checkbox/Checkbox.stories.mdx
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/ComponentWrapper/ComponentWrapper.tsx
  src/components/ComponentWrapper/__snapshots__/ComponentWrapper.test.tsx.snap
  src/components/DatePicker/DatePicker.stories.mdx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/HelperErrorText/HelperErrorText.test.tsx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/HelperErrorText/__snapshots__/HelperErrorText.test.tsx.snap
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/Radio/Radio.stories.mdx
  src/components/Radio/__snapshots__/Radio.test.tsx.snap
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/Select.stories.mdx
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/Toggle/Toggle.stories.mdx
  src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/components/VideoPlayer/VideoPlayer.stories.mdx
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
Labels: Ship It

#1248 Prep for Release v1.4.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Header/Header.stories.mdx
Labels: Ship It, Release

#1250 DSD-1298: dark mode for v1.4.0 components
  CHANGELOG.md
  package-lock.json
  src/components/FilterBar/FilterBar.tsx
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/TextInput/TextInput.stories.mdx
  src/theme/components/filterBar.ts
  src/theme/components/multiSelect.ts
  src/theme/components/multiSelectMenuButton.ts
  src/theme/components/skeletonLoader.ts
Labels: Ship It

#1252 DSD-1315: Documentation for release candidates
  README.md
Labels: Ship It

#1251 DSD-1303: Fix Slider onChangeEnd with value prop issue
  CHANGELOG.md
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
Labels: Ship It

#1253 DSD-1320: Digital Collections variants in Logo
  CHANGELOG.md
  icons/svg/logo-digital-collections-black.svg
  icons/svg/logo-digital-collections-white.svg
  src/components/Logo/Logo.stories.mdx
  src/components/Logo/Logo.tsx
  src/components/Logo/LogoSvgs.tsx
Labels: Ship It
