Repository NYPL/nypl-design-system, pull requests merged in 2023-08, with the labels that each got.

#1387 DSD-1531: better ARIA for Heading
  CHANGELOG.md
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.tsx
  src/components/Heading/__snapshots__/Heading.test.tsx.snap
  src/components/Text/Text.tsx
Labels: Ship It

#1388 DSD-1532: better typography docs
  CHANGELOG.md
  src/components/StyleGuide/Typography.mdx
  src/components/Text/Text.mdx
Labels: Ship It

#1390 DSD-1326: Adding backdropBackgroundColor prop for campaign Hero component
  CHANGELOG.md
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
Labels: Ship It

#1395 Prep for Release v1.7.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Heading/Heading.mdx
  src/components/Hero/Hero.mdx
  src/components/Icons/Icon.mdx
  src/components/Text/Text.mdx
Labels: Release

#1396 Release v1.7.1
  CHANGELOG.md
  icons/svg/social-tiktok.svg
  package-lock.json
  package.json
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.tsx
  src/components/Heading/__snapshots__/Heading.test.tsx.snap
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconVariables.ts
  src/components/StyleGuide/Typography.mdx
  src/components/Text/Text.mdx
  src/components/Text/Text.tsx
Labels: Ship It, Release

#1392 DSD-1308: standalone link variant
  CHANGELOG.md
  src/components/AccessibilityGuide/Links.mdx
  src/components/Link/Link.mdx
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.test.tsx
  src/components/Link/Link.tsx
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/theme/components/link.ts
  src/utils/utils.ts
Labels: Ship It

#1394 DSD-1558: applying Typo2023 color scheme
  CHANGELOG.md
  src/components/Accordion/Accordion.mdx
  src/components/AlphabetFilter/AlphabetFilter.mdx
  src/components/AudioPlayer/AudioPlayer.mdx
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Button/Button.mdx
  src/components/Checkbox/Checkbox.mdx
  src/components/DatePicker/DatePicker.mdx
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/Fieldset/Fieldset.mdx
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/Image/Image.mdx
  src/components/Label/Label.mdx
  src/components/List/List.mdx
  src/components/Modal/Modal.mdx
  src/components/MultiSelect/MultiSelect.mdx
  src/components/Notification/Notification.mdx
  src/components/Pagination/Pagination.mdx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/Radio/Radio.mdx
  src/components/SearchBar/SearchBar.mdx
  src/components/Select/Select.mdx
  src/components/Slider/Slider.mdx
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StructuredContent/StructuredContent.mdx
  src/components/StyledList/StyledList.mdx
  src/components/Table/Table.mdx
  src/components/Tabs/Tabs.mdx
  src/components/TagSet/TagSet.mdx
  src/components/Text/Text.mdx
  src/components/TextInput/TextInput.mdx
  src/components/Toggle/Toggle.mdx
  src/components/Tooltip/Tooltip.mdx
  src/components/VideoPlayer/VideoPlayer.mdx
  src/theme/components/accordion.ts
  src/theme/components/button.ts
  src/theme/components/customTable.ts
  src/theme/components/feedbackBox.ts
  src/theme/components/fieldset.ts
  src/theme/components/global.ts
  src/theme/components/heading.ts
  src/theme/components/hero.ts
  src/theme/components/list.ts
  src/theme/components/modal.ts
  src/theme/components/multiSelectMenuButton.ts
  src/theme/components/notification.ts
  src/theme/components/progressIndicator.ts
  src/theme/components/statusBadge.ts
  src/theme/components/tabs.ts
  src/theme/components/tagSet.ts
  src/theme/components/tooltip.ts
  src/theme/foundations/colors.ts
  src/theme/foundations/global.ts
Labels: Ship It

#1402 DSD-1547: Typo2023 styles for Typography category
  CHANGELOG.md
  src/components/AlphabetFilter/__snapshots__/AlphabetFilter.test.tsx.snap
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/ComponentWrapper/__snapshots__/ComponentWrapper.test.tsx.snap
  src/components/Heading/Heading.tsx
  src/components/Heading/__snapshots__/Heading.test.tsx.snap
  src/components/List/__snapshots__/List.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
  src/theme/foundations/global.ts
  src/theme/foundations/typography.ts
Labels: Ship It

#1397 DSD-1549: Typo2023 styles for Content Display category
  CHANGELOG.md
  src/theme/components/statusBadge.ts
Labels: Ship It

#1398 DSD-1550: Typo2023 styles for Feedback category
  CHANGELOG.md
  src/components/Notification/Notification.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/theme/components/notification.ts
  src/theme/components/progressIndicator.ts
Labels: Ship It

#1404 DSD-1543: new svg options in Icon
  CHANGELOG.md
  icons/svg/action-identity-filled.svg
  icons/svg/action-identity.svg
  icons/svg/action-search.svg
  icons/svg/maps-place.svg
  icons/svg/social-spotify.svg
  icons/svg/social-vimeo.svg
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconVariables.ts
Labels: Needs Review

#1401 DSD-1551: Typo2023 styles for Form category
  CHANGELOG.md
  src/theme/components/checkbox.ts
  src/theme/components/feedbackBox.ts
  src/theme/components/multiSelectMenuButton.ts
  src/theme/components/select.ts
  src/theme/components/slider.ts
  src/theme/components/tagSet.ts
  src/theme/components/textInput.ts
Labels: Ship It

#1405 DSD-1552: Typo2023 styles for Media & Icons category
  CHANGELOG.md
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/theme/components/image.ts
Labels: Ship It

#1406 DSD-1553: Typo2023 styles for Navigation category
  CHANGELOG.md
  src/theme/components/alphabetFilter.ts
Labels: Ship It

#1407 DSD-1554: Typo2023 styles for Overlays & Content Switchers category
  CHANGELOG.md
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/theme/components/modal.ts
  src/theme/components/tooltip.ts
Labels: Ship It

#1403 DSD-1479: Add documentation to Modal component
  CHANGELOG.md
  src/components/Modal/Modal.mdx
Labels: Ship It

#1410 DSD-1568: isUnderlined adjustments in Link component
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.tsx
Labels: Needs Review

#1408 DSD-1555: Typo2023 styles for Page Layout category
  CHANGELOG.md
  src/components/Placeholder/_Placeholder.scss
  src/components/StructuredContent/StructuredContent.tsx
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/theme/components/customTable.ts
Labels: Ship It

#1409 DSD-1559: link patterns in consuming components
  CHANGELOG.md
  src/components/Heading/Heading.tsx
  src/components/SkipNavigation/SkipNavigation.tsx
  src/theme/components/breadcrumb.ts
  src/theme/components/card.ts
  src/theme/components/heading.ts
  src/theme/components/pagination.ts
Labels: Ship It

#1411 Prep for Release v1.7.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Icons/Icon.mdx
  src/components/List/List.mdx
Labels: Ship It, Release

#1412 Release v1.7.2
  CHANGELOG.md
  icons/svg/action-identity-filled.svg
  icons/svg/action-identity.svg
  icons/svg/action-search.svg
  icons/svg/maps-place.svg
  icons/svg/social-spotify.svg
  icons/svg/social-vimeo.svg
  package-lock.json
  package.json
  src/components/Icons/Icon.mdx
  src/components/Icons/Icon.stories.tsx
  src/components/Icons/Icon.tsx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconVariables.ts
  src/components/List/List.mdx
  src/components/Modal/Modal.mdx
  src/index.ts
  src/theme/components/list.ts
Labels: Ship It, Release
