Repository NYPL/nypl-design-system, pull requests merged in 2023-01, with the labels that each got.

#1222 DSD-1234: adjustments for FilterBar spacing and alignment
  src/components/FilterBar/FilterBar.stories.mdx
  src/components/FilterBar/FilterBar.stories.tsx
  src/components/FilterBar/FilterBar.tsx
  src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/theme/components/filterBar.ts
  src/theme/components/multiSelectGroup.ts
  src/theme/components/multiSelectMenuButton.ts
  src/theme/index.ts
Labels: Needs Review

#1229 Bug fix: Temporarily commenting out Header tests which are failing
  src/components/Footer/__snapshots__/Footer.test.tsx.snap
  src/components/Header/Header.test.tsx
  src/components/Header/components/HeaderSitewideAlerts.test.tsx
Labels: Ship It

#1228 DSD-1242: HelperErrorTexta and aria-live
  CHANGELOG.md
  package-lock.json
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/ComponentWrapper/__snapshots__/ComponentWrapper.test.tsx.snap
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/HelperErrorText/HelperErrorText.stories.mdx
  src/components/HelperErrorText/HelperErrorText.test.tsx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/HelperErrorText/__snapshots__/HelperErrorText.test.tsx.snap
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
Labels: Needs Review

#1231 DSD-1221: Add onChangeEnd prop to Slider
  CHANGELOG.md
  src/components/Slider/Slider.stories.mdx
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
Labels: Ship It

#1230 DSD-1228: TextInput accessibility updates
  CHANGELOG.md
  package-lock.json
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/TextInput.stories.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: Ship It

#1232 DSD-1279: improved a11y for CheckboxGroup, MultiSelectGroup and RadioGroup
  CHANGELOG.md
  src/components/CheckboxGroup/CheckboxGroup.stories.mdx
  src/components/CheckboxGroup/CheckboxGroup.test.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/RadioGroup/RadioGroup.stories.mdx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
Labels: Needs Review

#1234 DSD-1270: updated a11y docs for Notification
  CHANGELOG.md
  src/components/Notification/Notification.stories.mdx
Labels: Ship It

#1235 DSD-1266 & DSD-1275: new pages for A11y Guide
  CHANGELOG.md
  src/components/AccessibilityGuide/Links.stories.mdx
  src/components/AccessibilityGuide/RepetitiveActions.stories.mdx
  src/components/AccessibilityGuide/SkipNavigation.stories.mdx
  src/utils/componentCategories.ts
Labels: Ship It

#1237 DSD-1283: arial-label for Total Items Selected button
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelectMenuButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
Labels: Needs Review

#1238 DSD-1276: Header logged out state
  CHANGELOG.md
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderLogin.test.tsx
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/theme/components/header/headerLogin.ts
Labels: Ship It, Header

#1241 DSD-1294: Update MultiSelect prop names
  src/components/FilterBar/FilterBar.stories.tsx
  src/components/FilterBar/FilterBar.test.tsx
  src/components/MultiSelect/MultiSelect.stories.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectDialog.tsx
  src/components/MultiSelect/MultiSelectListbox.tsx
  src/components/MultiSelect/MultiSelectMenuButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
Labels: Ship It

#1242 Prep for Release v1.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It, Release
