Repository NYPL/nypl-design-system, pull requests merged in 2024-03, with the labels that each got.

#1536 Accessibility: fixing duplicate id issue in MultiSelect
  CHANGELOG.md
  src/components/Checkbox/checkboxChangelogData.ts
  src/components/CheckboxGroup/CheckboxGroup.test.tsx
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/checkboxGroupChangelogData.ts
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectItemsCountButton.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
Labels: Ship It

#1541 Exporting helpers from Chakra
  CHANGELOG.md
  src/index.ts
Labels: Ship It

#1546 No ref: SkeletonLoader layout and color fix
  src/components/SkeletonLoader/SkeletonLoader.tsx
  src/theme/components/skeletonLoader.ts
  src/theme/index.ts
Labels: Ship It

#1537 DSD-1698: Removing errors and refactoring the `Link` component
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Heading/__snapshots__/Heading.test.tsx.snap
  src/components/Link/Link.mdx
  src/components/Link/Link.stories.tsx
  src/components/Link/Link.test.tsx
  src/components/Link/Link.tsx
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/components/Link/linkChangelogData.ts
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/components/SkipNavigation/__snapshots__/SkipNavigation.test.tsx.snap
  src/components/SocialMediaLinks/__snapshots__/SocialMediaLinks.test.tsx.snap
Labels: Needs Review

#1552 DSD-1710: Use onClearAll function in multi-select component
  src/components/FilterBar/FilterBar.test.tsx
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectItemsCountButton.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.md
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
  src/theme/components/multiSelect.ts
  src/theme/components/multiSelectItemsCountButton.ts
Labels: Ship It

#1545 DSD-1708: TagSet update to allow more properties in the data object
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/TagSet/TagSet.mdx
  src/components/TagSet/TagSet.stories.tsx
  src/components/TagSet/TagSet.test.tsx
  src/components/TagSet/TagSet.tsx
  src/components/TagSet/TagSetExplore.tsx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/components/TagSet/tagSetChangelogData.ts
Labels: Ship It

#1556 MultiSelect onClear function
  src/components/FilterBar/FilterBar.test.tsx
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectItemsCountButton.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
Labels: Ship It

#1555 V3 Repo update
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
  .github/workflows/static.yml
  .jest-test-results.json
  .storybook/public/nypl-reservoir-design-system-logo.svg
  CHAKRA_MIGRATION_GUIDE.md
  README.md
  package-lock.json
  package.json
  src/components/Menu/Menu.mdx
  src/components/TagSet/TagSet.mdx
  src/docs/Welcome.mdx
  src/theme/foundations/colors.ts
  vite.config.ts
Labels: Needs Review

#1553 DS v3 - Migration Guide
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .github/workflows/release.yml
  .github/workflows/static.yml
  .jest-test-results.json
  .storybook/public/nypl-reservoir-design-system-logo.svg
  CHAKRA_MIGRATION_GUIDE.md
  README.md
  package-lock.json
  package.json
  src/components/DevelopmentGuide/V3MigrationGuide.mdx
  src/components/Menu/Menu.mdx
  src/components/NewsletterSignup/NewsletterSignup.test.tsx
  src/components/SocialMediaLinks/SocialMediaLinks.test.tsx
  src/components/TagSet/TagSet.mdx
  src/docs/Welcome.mdx
  src/theme/components/multiSelectItemsCountButton.ts
  src/theme/foundations/colors.ts
  vite.config.ts
Labels: Needs Review

#1561 DSD-1725: pencil icon
  CHANGELOG.md
  icons/svg/editor-mode.svg
  package-lock.json
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
Labels: Ship It

#1563 DSD-1619: Add Errors page to Accessibility Guide
  CHANGELOG.md
  src/components/AccessibilityGuide/Errors.mdx
Labels: Ship It

#1566 DSD-1717: Update list bullet color
  CHANGELOG.md
  src/components/List/List.mdx
  src/components/List/listChangelogData.ts
  src/theme/components/list.ts
Labels: Ship It

#1567 DSD-1718: Modal heading size update
  CHANGELOG.md
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/modalChangelogData.ts
  src/hooks/useDSHeading.tsx
  src/theme/components/modal.ts
Labels: Ship It

#1548 DSD-1686: Updates mobile styles for SocialMediaLinks component
  CHANGELOG.md
  src/components/SocialMediaLinks/SocialMediaLinks.mdx.temp-remove
  src/components/SocialMediaLinks/SocialMediaLinks.stories.tsx.temp-remove
  src/components/SocialMediaLinks/SocialMediaLinks.tsx
  src/components/SocialMediaLinks/socialMediaLinksChangelogData.ts
  src/theme/components/socialmedialinks.ts
Labels: Ship It

#1568 Prep Release for 3.0.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Icons/Icon.mdx
  src/components/Icons/iconChangelogData.ts
  src/components/List/List.mdx
  src/components/List/listChangelogData.ts
  src/components/Modal/Modal.mdx
  src/components/Modal/modalChangelogData.ts
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/SocialMediaLinks/SocialMediaLinks.mdx.temp-remove
  src/components/SocialMediaLinks/socialMediaLinksChangelogData.ts
Labels: Needs Review, Release

#1569 Release v3.0.1
  CHANGELOG.md
  icons/svg/editor-mode.svg
  package-lock.json
  package.json
  src/components/AccessibilityGuide/Errors.mdx
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
  src/components/List/List.mdx
  src/components/List/listChangelogData.ts
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/modalChangelogData.ts
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/SocialMediaLinks/SocialMediaLinks.mdx.temp-remove
  src/components/SocialMediaLinks/SocialMediaLinks.stories.tsx.temp-remove
  src/components/SocialMediaLinks/SocialMediaLinks.tsx
  src/components/SocialMediaLinks/socialMediaLinksChangelogData.ts
  src/hooks/useDSHeading.tsx
  src/theme/components/list.ts
  src/theme/components/modal.ts
  src/theme/components/socialmedialinks.ts
Labels: Needs Review, Release
