Repository NYPL/nypl-design-system, pull requests merged in 2024-08, with the labels that each got.

#1643 DSD-1797: Breadcrumbs custom link prop
  CHANGELOG.md
  package-lock.json
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/theme/components/breadcrumb.ts
Labels: Needs Review, x2

#1642 DSD-1799: Add closeOnBlur to FilterBarInline
  CHANGELOG.md
  src/components/FilterBarInline/FilterBarInline.mdx
  src/components/FilterBarInline/FilterBarInline.stories.tsx
  src/components/FilterBarInline/FilterBarInline.tsx
  src/components/FilterBarInline/filterBarInlineChangelogData.ts
Labels: Ship It

#1636 DSD-1771: FilterBarPopup Component
  CHANGELOG.md
  src/components/FilterBarPopup/FilterBarPopup.mdx
  src/components/FilterBarPopup/FilterBarPopup.stories.tsx
  src/components/FilterBarPopup/FilterBarPopup.test.tsx
  src/components/FilterBarPopup/FilterBarPopup.tsx
  src/components/FilterBarPopup/__snapshots__/FilterBarPopup.test.tsx.snap
  src/components/FilterBarPopup/filterBarPopupChangelogData.ts
  src/index.ts
  src/theme/components/filterBarPopup.ts
  src/theme/index.ts
Labels: Ship It

#1648 NO-REF: Fix issues in FilterBarPopup
  CHANGELOG.md
  src/components/FilterBarPopup/FilterBarPopup.mdx
  src/components/FilterBarPopup/FilterBarPopup.tsx
  src/components/FilterBarPopup/__snapshots__/FilterBarPopup.test.tsx.snap
Labels: Ship It

#1646 DSD-1811: Searchbar responsive styling
  CHANGELOG.md
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/SearchBar/searchBarChangelogData.ts
  src/theme/components/searchBar.ts
Labels: Ship It

#1651 DSD-1733: Adds defaultValue prop to Select
  CHANGELOG.md
  src/components/Select/Select.mdx
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Select/selectChangelogData.ts
Labels: Ship It

#1647 DSD-1817: Conditional viewport guide
  .prettierignore
  CHANGELOG.md
  src/components/DevelopmentGuide/ConditionalViewport.mdx
Labels: Needs Review, x2

#1650 DSD-1823: using buttonText in MultiSelect for CheckboxGroup legend value
  CHANGELOG.md
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
Labels: Ship It

#1653 NO-REF: Update focus for FilterBarPopup on clear
  src/components/FilterBarPopup/FilterBarPopup.tsx
Labels: Ship It

#1654 Prep for Release v3.3.0
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Banner/Banner.mdx
  src/components/Banner/bannerChangelogData.ts
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/components/FeaturedContent/FeaturedContent.mdx
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/components/FilterBarInline/FilterBarInline.mdx
  src/components/FilterBarInline/filterBarInlineChangelogData.ts
  src/components/FilterBarPopup/FilterBarPopup.mdx
  src/components/FilterBarPopup/filterBarPopupChangelogData.ts
  src/components/Image/Image.mdx
  src/components/Image/imageChangelogData.ts
  src/components/Menu/Menu.mdx
  src/components/Menu/menuChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Select/Select.mdx
  src/components/Select/selectChangelogData.ts
Labels: Ship It, Release
