Repository NYPL/nypl-design-system, pull requests merged in 2024-10, with the labels that each got.

#1676 DSD-1838: Template style updates to accommodate Table
  CHANGELOG.md
  package-lock.json
  src/components/Template/templateChangelogData.ts
  src/theme/components/template.ts
Labels: Ship It

#1678 Prep for Release v3.4.0
  package-lock.json
  package.json
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Table/Table.mdx
  src/components/Table/tableChangelogData.ts
  src/components/Template/Template.mdx
  src/components/Template/templateChangelogData.ts
Labels: Ship It, Release

#1679 Release v3.4.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/Card.mdx
  src/components/Card/Card.stories.tsx
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/Image/Image.tsx
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Table/Table.mdx
  src/components/Table/Table.stories.tsx
  src/components/Table/Table.test.tsx
  src/components/Table/Table.tsx
  src/components/Table/__snapshots__/Table.test.tsx.snap
  src/components/Table/tableChangelogData.ts
  src/components/Template/Template.mdx
  src/components/Template/Template.stories.tsx
  src/components/Template/templateChangelogData.ts
  src/index.ts
  src/theme/components/customTable.ts
  src/theme/components/feedbackBox.ts
  src/theme/components/template.ts
  src/theme/foundations/global.ts
  src/utils/ComponentChangelogTable.tsx
Labels: Release

#1677 DSD-1791: Fix SearchBar select cutoff issue
  CHANGELOG.md
  src/components/SearchBar/SearchBar.mdx
  src/theme/components/searchBar.ts
  src/theme/components/select.ts
Labels: Ship It

#1681 DSD-1847: decorativeBookBroken icon
  CHANGELOG.md
  icons/svg/decorative-book-broken.svg
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
Labels: Ship It

#1680 DSD-1798: Add labelPlacement prop to ProgressIndicator
  CHANGELOG.md
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.tsx
  src/components/ProgressIndicator/ProgressIndicator.tsx
  src/components/ProgressIndicator/progressIndicatorChangelogData.ts
  src/theme/components/progressIndicator.ts
Labels: Ship It

#1682 DSD-1849: new size options for Icon
  CHANGELOG.md
  src/components/Icons/Icon.stories.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
  src/theme/components/icon.ts
Labels: Ship It

#1683 DSD-1840: Allowing custom image component in Hero
  CHANGELOG.md
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/heroChangelogData.ts
  src/index.ts
  src/theme/components/hero.ts
Labels: Needs Review, x2

#1689 Prep for Release v3.4.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Hero/Hero.mdx
  src/components/Hero/heroChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/iconChangelogData.ts
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/ProgressIndicator/progressIndicatorChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
Labels: Ship It, Release

#1690 Release v3.4.1
  CHANGELOG.md
  icons/svg/decorative-book-broken.svg
  package-lock.json
  package.json
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/heroChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/Icon.stories.tsx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/ProgressIndicator/ProgressIndicator.stories.tsx
  src/components/ProgressIndicator/ProgressIndicator.tsx
  src/components/ProgressIndicator/progressIndicatorChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/index.ts
  src/theme/components/hero.ts
  src/theme/components/icon.ts
  src/theme/components/progressIndicator.ts
  src/theme/components/searchBar.ts
  src/theme/components/select.ts
Labels: Release

#1688 DSD-1855: additional sizes for Heading component
  CHANGELOG.md
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.stories.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/headingChangelogData.ts
  src/components/StyleGuide/Typography.mdx
  src/theme/components/heading.ts
  src/theme/foundations/typography.ts
Labels: Ship It

#1693 DSD-1868: better spacing and dark mode styles
  CHANGELOG.md
  src/components/Table/Table.mdx
  src/components/Table/tableChangelogData.ts
  src/theme/components/customTable.ts
Labels: Ship It
