Repository NYPL/nypl-design-system, pull requests merged in 2024-11, with the labels that each got.

#1696 DSD-1870: contentFilterList icon
  CHANGELOG.md
  icons/svg/content-filter-list.svg
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
Labels: Ship It

#1695 DSD-1846 & DSD-1869: X icon in Icon and SocialMediaLinks
  CHANGELOG.md
  icons/svg/social-x.svg
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
  src/components/SocialMediaLinks/SocialMediaLinks.mdx
  src/components/SocialMediaLinks/SocialMediaLinks.stories.tsx
  src/components/SocialMediaLinks/SocialMediaLinks.tsx
  src/components/SocialMediaLinks/socialMediaLinksChangelogData.ts
Labels: Ship It

#1699 Prep for Release v3.4.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/iconChangelogData.ts
  src/components/Link/Link.mdx
  src/components/Link/linkChangelogData.ts
  src/components/SocialMediaLinks/SocialMediaLinks.mdx
  src/components/SocialMediaLinks/socialMediaLinksChangelogData.ts
  src/components/Table/Table.mdx
  src/components/Table/tableChangelogData.ts
Labels: Ship It, Release

#1700 Release v3.4.2
  CHANGELOG.md
  icons/svg/content-filter-list.svg
  icons/svg/social-x.svg
  package-lock.json
  package.json
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.stories.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/headingChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
  src/components/Link/Link.mdx
  src/components/Link/Link.tsx
  src/components/Link/linkChangelogData.ts
  src/components/SocialMediaLinks/SocialMediaLinks.mdx
  src/components/SocialMediaLinks/SocialMediaLinks.stories.tsx
  src/components/SocialMediaLinks/SocialMediaLinks.tsx
  src/components/SocialMediaLinks/socialMediaLinksChangelogData.ts
  src/components/StyleGuide/Typography.mdx
  src/components/Table/Table.mdx
  src/components/Table/tableChangelogData.ts
  src/theme/components/customTable.ts
  src/theme/components/heading.ts
  src/theme/components/icon.ts
  src/theme/components/link.ts
  src/theme/foundations/typography.ts
Labels: Ship It, Release

#1703 DSD-1872: temp Header
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Header/Header.mdx
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/Header/components/HeaderLogin.test.tsx
  src/components/Header/components/HeaderLogin.tsx
  src/components/Header/components/HeaderLoginButton.test.tsx
  src/components/Header/components/HeaderLoginButton.tsx
  src/components/Header/components/HeaderLowerNav.tsx
  src/components/Header/components/HeaderMobileIconNav.tsx
  src/components/Header/components/HeaderMobileNav.test.tsx
  src/components/Header/components/HeaderMobileNav.tsx
  src/components/Header/components/HeaderMobileNavButton.test.tsx
  src/components/Header/components/HeaderMobileNavButton.tsx
  src/components/Header/components/HeaderSearchButton.test.tsx
  src/components/Header/components/HeaderSearchButton.tsx
  src/components/Header/components/HeaderSearchForm.test.tsx
  src/components/Header/components/HeaderSearchForm.tsx
  src/components/Header/components/HeaderSitewideAlerts.test.tsx
  src/components/Header/components/HeaderSitewideAlerts.tsx
  src/components/Header/components/HeaderUpperNav.tsx
  src/components/Header/components/__snapshots__/HeaderMobileNav.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderMobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSitewideAlerts.test.tsx.snap
  src/components/Header/context/headerContext.test.tsx
  src/components/Header/context/headerContext.tsx
  src/components/Header/utils/authApiMockResponse.ts
  src/components/Header/utils/encoreCatalogLogOutTimer.test.ts
  src/components/Header/utils/encoreCatalogLogOutTimer.ts
  src/components/Header/utils/headerUtils.test.ts
  src/components/Header/utils/headerUtils.ts
  src/components/Header/utils/sitewideAlertsMocks.ts
  src/index.ts
  src/theme/components/header.ts
  src/theme/components/headerLogin.ts
  src/theme/components/headerLoginButton.ts
  src/theme/components/headerLowerNav.ts
  src/theme/components/headerMobileIconNav.ts
  src/theme/components/headerMobileNav.ts
  src/theme/components/headerMobileNavButton.ts
  src/theme/components/headerSearchButton.ts
  src/theme/components/headerSearchForm.ts
  src/theme/components/headerSitewideAlerts.ts
  src/theme/components/headerUpperNav.ts
  src/theme/foundations/breakpoints.ts
  src/theme/index.ts
Labels: Needs Review

#1706 Quick fixes in header nav
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Header/Header.stories.tsx
  src/theme/components/headerLowerNav.ts
  src/theme/components/headerUpperNav.ts
Labels: Ship It

#1702 DSD-1871: Add item count to MultiSelect
  CHANGELOG.md
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
Labels: Ship It

#1697 DSD-1852: SubNav Menu Component
  CHANGELOG.md
  package-lock.json
  src/components/SubNav/SubNav.mdx
  src/components/SubNav/SubNav.stories.tsx
  src/components/SubNav/SubNav.test.tsx
  src/components/SubNav/SubNav.tsx
  src/components/SubNav/subNavChangelogData.ts
  src/hooks/useScrollFadeStyles.mdx
  src/hooks/useScrollFadeStyles.ts
  src/index.ts
  src/theme/components/subnav.ts
  src/theme/index.ts
Labels: Ship It

#1701 DSD-1867: overflow focus indicator
  CHANGELOG.md
  package-lock.json
  src/components/Template/Template.mdx
  src/components/Template/templateChangelogData.ts
  src/theme/components/template.ts
Labels: Ship It
