Repository NYPL/nypl-design-system, pull requests merged in 2024-06, with the labels that each got.

#1615 Prep for Release v3.1.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Release

#1612 Modal docs update
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.tsx
Labels: Ship It

#1614 DSD-1750: Select interaction tests
  CHANGELOG.md
  src/components/Select/Select.mdx
  src/components/Select/Select.stories.tsx
  src/components/Select/selectChangelogData.ts
Labels: Ship It

#1597 DSD-1748: Adding interaction tests for RadioGroup
  CHANGELOG.md
  package-lock.json
  src/components/RadioGroup/RadioGroup.mdx
  src/components/RadioGroup/RadioGroup.stories.tsx
  src/components/RadioGroup/radioGroupChangelogData.tsx
Labels: Ship It

#1611 DSD-1749: Search bar interaction tests
  CHANGELOG.md
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/SearchBar/searchBarChangelogData.ts
Labels: Ship It

#1619 DSD-1685: Github Action tag/release fix
  .github/workflows/release.yml
  CHANGELOG.md
Labels: Ship It

#1626 Prep for Release v3.1.6
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/RadioGroup/RadioGroup.mdx
  src/components/RadioGroup/radioGroupChangelogData.tsx
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Select/Select.mdx
  src/components/Select/selectChangelogData.ts
Labels: Release

#1627 Release v3.1.6
  .github/workflows/release.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.stories.tsx
  src/components/Heading/headingChangelogData.ts
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.tsx
  src/components/RadioGroup/RadioGroup.mdx
  src/components/RadioGroup/RadioGroup.stories.tsx
  src/components/RadioGroup/radioGroupChangelogData.tsx
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Select/Select.mdx
  src/components/Select/Select.stories.tsx
  src/components/Select/selectChangelogData.ts
  src/theme/components/heading.ts
Labels: Release

#1618 DSD-1778: Update base font stack
  CHANGELOG.md
  src/theme/foundations/typography.ts
Labels: Ship It

#1621 DSD-1744: Adding interaction tests for CheckboxGroup
  CHANGELOG.md
  src/components/CheckboxGroup/CheckboxGroup.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.tsx
  src/components/CheckboxGroup/checkboxGroupChangelogData.ts
Labels: Needs Review

#1622 DSD-1745: Adding interaction tests for DatePicker
  CHANGELOG.md
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/DatePicker/datePickerChangelogData.ts
Labels: Needs Review

#1624 DSD-1751: Adding interaction tests for Slider component
  CHANGELOG.md
  src/components/Slider/Slider.mdx
  src/components/Slider/Slider.stories.tsx
  src/components/Slider/sliderChangelogData.ts
Labels: Ship It

#1607 DSD-1740/close dropdown multiselect
  CHANGELOG.md
  src/components/Accordion/Accordion.mdx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/accordionChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectItemsCountButton.tsx
Labels: Ship It

#1620 DSD-1740: Adds ability to close MultiSelect on blur
  CHANGELOG.md
  src/components/Accordion/Accordion.tsx
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/MultiSelectGroup/multiSelectGroupChangelogData.ts
Labels: Ship It

#1628 DSD-1746: FeedbackBox interaction tests
  CHANGELOG.md
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.stories.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
Labels: Ship It

#1629 DSD-1795: Breadcrumbs Digital Collections variant
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/theme/components/breadcrumb.ts
Labels: Ship It

#1625 jest routing npm package update
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It
