Repository NYPL/nypl-design-system, pull requests merged in 2024-09, with the labels that each got.

#1652 DSD-1827: Adding Tooltip positioning props
  CHANGELOG.md
  package-lock.json
  src/components/Card/Card.mdx
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.tsx
  src/components/Tooltip/Tooltip.mdx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/tooltipChangelogData.ts
Labels: Ship It

#1657 DSD-1826: Fixing an issue where an id was being duplicated in the Image component
  CHANGELOG.md
  src/components/Card/Card.stories.tsx
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Image/imageChangelogData.ts
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: Ship It

#1660 Prep for Release v3.3.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Image/Image.mdx
  src/components/Image/imageChangelogData.ts
  src/components/Tooltip/Tooltip.mdx
  src/components/Tooltip/tooltipChangelogData.ts
Labels: Needs Review, Release

#1661 Release v3.3.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/Card.mdx
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.tsx
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Image/imageChangelogData.ts
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/Table/__snapshots__/Table.test.tsx.snap
  src/components/Tooltip/Tooltip.mdx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/tooltipChangelogData.ts
Labels: Release

#1662 DSD-1792: Changes (required) text capitalization
  CHANGELOG.md
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/Fieldset/Fieldset.mdx
  src/components/Fieldset/Fieldset.test.tsx
  src/components/Fieldset/Fieldset.tsx
  src/components/Fieldset/__snapshots__/Fieldset.test.tsx.snap
  src/components/Fieldset/fieldsetChangelogData.ts
  src/components/Label/Label.mdx
  src/components/Label/Label.test.tsx
  src/components/Label/Label.tsx
  src/components/Label/__snapshots__/Label.test.tsx.snap
  src/components/Label/labelChangelogData.ts
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Select/Select.mdx
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/Slider/Slider.test.tsx
  src/components/Slider/Slider.tsx
  src/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
Labels: Ship It

#1659 DSD-1585: HelperErrorText styling bug
  CHANGELOG.md
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/HelperErrorText/__snapshots__/HelperErrorText.test.tsx.snap
  src/components/HelperErrorText/helperErrorTextChangelogData.ts
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
Labels: Ship It

#1670 Prep for Release v3.3.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/Card.mdx
  src/components/Card/cardChangelogData.ts
  src/components/CheckboxGroup/CheckboxGroup.mdx
  src/components/CheckboxGroup/checkboxGroupChangelogData.ts
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/Fieldset/Fieldset.mdx
  src/components/Fieldset/fieldsetChangelogData.ts
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/HelperErrorText/helperErrorTextChangelogData.ts
  src/components/Label/Label.mdx
  src/components/Label/labelChangelogData.ts
  src/components/RadioGroup/RadioGroup.mdx
  src/components/RadioGroup/radioGroupChangelogData.tsx
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Select/Select.mdx
  src/components/Select/selectChangelogData.ts
  src/components/Slider/Slider.mdx
  src/components/Slider/sliderChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/textInputChangelogData.ts
Labels: Ship It, Release

#1667 DSD-1747: Multiselect interaction tests
  CHANGELOG.md
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
Labels: Ship It

#1668 Dsd 1695/search bar better error message
  CHANGELOG.md
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/searchBarChangelogData.ts
Labels: Ship It

#1658 DSD-1814: table enhancements
  CHANGELOG.md
  package-lock.json
  src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap
  src/components/Image/Image.tsx
  src/components/Table/Table.mdx
  src/components/Table/Table.stories.tsx
  src/components/Table/Table.test.tsx
  src/components/Table/Table.tsx
  src/components/Table/__snapshots__/Table.test.tsx.snap
  src/components/Table/tableChangelogData.ts
  src/index.ts
  src/theme/components/customTable.ts
  src/utils/ComponentChangelogTable.tsx
Labels: Ship It

#1666 DSD 1829: Adding responsive tooltip example to Card docs
  src/components/Card/Card.mdx
  src/components/Card/Card.stories.tsx
Labels: Ship It

#1673 DSD-1838: primary content area styles
  CHANGELOG.md
  package-lock.json
  src/components/Template/Template.mdx
  src/components/Template/Template.stories.tsx
  src/components/Template/templateChangelogData.ts
  src/theme/components/template.ts
Labels: Ship It

#1675 DSD-1836: better overflow styles for Template
  CHANGELOG.md
  src/components/Template/Template.stories.tsx
  src/components/Template/templateChangelogData.ts
  src/theme/components/template.ts
Labels: Needs Review
