Repository NYPL/nypl-design-system, pull requests merged in 2024-04, with the labels that each got.

#1562 DSD-1623: label spacing for DatePicker, Select, Slider, and TextInput
  CHANGELOG.md
  package-lock.json
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/Select/Select.mdx
  src/components/Select/selectChangelogData.ts
  src/components/Slider/Slider.mdx
  src/components/Slider/sliderChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/textInputChangelogData.ts
  src/theme/components/datePicker.ts
  src/theme/components/global.ts
  src/theme/components/select.ts
  src/theme/components/slider.ts
  src/theme/components/textInput.ts
Labels: Ship It

#1533 DSD-1691: Banner
  CHANGELOG.md
  icons/svg/action-lightbulb.svg
  package-lock.json
  src/__tests__/utils/getSectionColors.test.ts
  src/components/Banner/Banner.mdx
  src/components/Banner/Banner.stories.tsx
  src/components/Banner/Banner.test.tsx
  src/components/Banner/Banner.tsx
  src/components/Banner/__snapshots__/Banner.test.tsx.snap
  src/components/Banner/bannerChangelogData.ts
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/Iconography.mdx
  src/helpers/types.ts
  src/theme/components/banner.ts
  src/theme/components/statusBadge.ts
  src/theme/foundations/colors.ts
  src/theme/index.ts
Labels: Ship It

#1547 DSD-1711: MultiSelectGroup Chakra update
  package-lock.json
  src/components/FilterBar/FilterBar.test.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.md
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories-temp-remove.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.test.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/MultiSelectGroup/multiSelectGroupChangelogData.ts
Labels: Ship It

#1571 Prep for Release v3.1.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Banner/Banner.mdx
  src/components/Banner/bannerChangelogData.ts
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/iconChangelogData.ts
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/MultiSelectGroup/multiSelectGroupChangelogData.ts
  src/components/Select/Select.mdx
  src/components/Select/selectChangelogData.ts
  src/components/Slider/Slider.mdx
  src/components/Slider/sliderChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/textInputChangelogData.ts
Labels: Ship It, Release

#1574 DSD-1761: placeholder value for MultiSelect search field
  CHANGELOG.md
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
Labels: Ship It

#1576 DSD-1714: update "NoBrand" Button styles
  CHANGELOG.md
  src/components/Button/Button.mdx
  src/components/Button/buttonChangelogData.ts
  src/theme/components/button.ts
Labels: Ship It

#1577 DSD-1659: docs for Link component "Visited State Patterns"
  CHANGELOG.md
  src/components/Link/Link.mdx
Labels: Ship It

#1579 DSD-1556: better layout for Icon examples
  src/components/Icons/Icon.mdx
  src/components/Icons/Icon.stories.tsx
Labels: Ship It

#1504 DSD-1677: Adding interaction test examples
  .storybook/main.ts
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/TextInput/TextInput.stories.tsx
Labels: Needs Review, x2

#1573 DSD-1758: updated hex values for semantic "warning" color
  CHANGELOG.md
  src/components/Banner/Banner.mdx
  src/components/Banner/bannerChangelogData.ts
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StatusBadge/statusBadgeChangelogData.ts
  src/components/StyleGuide/ColorCard.tsx
  src/theme/components/banner.ts
  src/theme/components/statusBadge.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#1581 DSD-1767: Adding fallback and onerror feature to Image and Hero components
  CHANGELOG.md
  package-lock.json
  src/components/Card/Card.stories.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Hero/heroChangelogData.ts
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Image/imageChangelogData.ts
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: Needs Review, x2

#1575 DSD-1726 & DSD-1765: TagSet style updates
  CHANGELOG.md
  src/components/TagSet/TagSet.mdx
  src/components/TagSet/TagSet.stories.tsx
  src/components/TagSet/TagSet.test.tsx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/components/TagSet/tagSetChangelogData.ts
  src/theme/components/link.ts
  src/theme/components/tagSet.ts
Labels: Ship It

#1578 DSD-1760: implementing NYPL placeholder images
  CHANGELOG.md
  src/components/Card/Card.mdx
  src/components/Card/Card.stories.tsx
  src/components/Card/Card.test.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Chakra/Center.mdx
  src/components/FeaturedContent/FeaturedContent.stories.tsx
  src/components/FeaturedContent/FeaturedContent.test.tsx
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/Grid/SimpleGrid.stories.tsx
  src/components/Grid/SimpleGrid.test.tsx
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.test.tsx
  src/components/Menu/Menu.mdx
  src/components/Menu/Menu.stories.tsx
  src/components/StructuredContent/StructuredContent.stories.tsx
  src/components/StructuredContent/StructuredContent.test.tsx
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/StyleGuide/Bidirectionality.mdx
  src/components/StyleGuide/Typography.mdx
  src/components/Template/Template.mdx
  src/components/Template/Template.stories.tsx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.test.tsx
  src/utils/utils.ts
Labels: Needs Review, x2

#1485 DSD-1660: default text colors in Hero
  CHANGELOG.md
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Hero/heroChangelogData.ts
  src/theme/components/hero.ts
Labels: Ship It

#1582 DSD-1769: BackgroundImage CSS workaround
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/FeaturedContent/FeaturedContent.stories.tsx
  src/components/FeaturedContent/FeaturedContent.tsx
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Hero/heroChangelogData.ts
Labels: Needs Review

#1584 Prep for Release v3.1.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Banner/Banner.mdx
  src/components/Banner/bannerChangelogData.ts
  src/components/Button/Button.mdx
  src/components/Button/buttonChangelogData.ts
  src/components/FeaturedContent/FeaturedContent.mdx
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/heroChangelogData.ts
  src/components/Image/Image.mdx
  src/components/Image/imageChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StatusBadge/statusBadgeChangelogData.ts
  src/components/TagSet/TagSet.mdx
  src/components/TagSet/tagSetChangelogData.ts
Labels: Ship It, Release
