Repository NYPL/nypl-design-system, pull requests merged in 2024-12, with the labels that each got.

#1708 Prep for Release v3.5.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/SubNav/SubNav.mdx
  src/components/SubNav/subNavChangelogData.ts
  src/components/Template/Template.mdx
  src/components/Template/templateChangelogData.ts
  src/hooks/useScrollFadeStyles.mdx
Labels: Release

#1709 Release v3.5.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/SubNav/SubNav.mdx
  src/components/SubNav/SubNav.stories.tsx
  src/components/SubNav/SubNav.test.tsx
  src/components/SubNav/SubNav.tsx
  src/components/SubNav/subNavChangelogData.ts
  src/components/Template/Template.mdx
  src/components/Template/templateChangelogData.ts
  src/hooks/useScrollFadeStyles.mdx
  src/hooks/useScrollFadeStyles.ts
  src/index.ts
  src/theme/components/subnav.ts
  src/theme/components/template.ts
  src/theme/index.ts
Labels: Release

#1715 Fixing type issue
  package-lock.json
  src/hooks/__tests__/useNYPLTheme.test.tsx
Labels: Ship It

#1710 DSD-1121: SVG testing update
  CHANGELOG.md
  jest.config.js
  package-lock.json
  src/__tests__/fileMock.ts
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Banner/Banner.test.tsx
  src/components/Banner/__snapshots__/Banner.test.tsx.snap
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderMobileNav.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderMobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Icons/Icon.test.tsx
  src/components/Icons/__snapshots__/Icon.test.tsx.snap
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/components/Logo/Logo.test.tsx
  src/components/Logo/__snapshots__/Logo.test.tsx.snap
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/SocialMediaLinks/SocialMediaLinks.test.tsx
  src/components/SocialMediaLinks/__snapshots__/SocialMediaLinks.test.tsx.snap
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
Labels: Needs Review

#1717 Prep for release v3.5.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/textInputChangelogData.ts
Labels: Release

#1718 Release v3.5.1
  CHANGELOG.md
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/fileMock.ts
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Banner/Banner.test.tsx
  src/components/Banner/__snapshots__/Banner.test.tsx.snap
  src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderMobileNav.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderMobileNavButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchButton.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Icons/Icon.test.tsx
  src/components/Icons/__snapshots__/Icon.test.tsx.snap
  src/components/Link/__snapshots__/Link.test.tsx.snap
  src/components/Logo/Logo.test.tsx
  src/components/Logo/__snapshots__/Logo.test.tsx.snap
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/Select/__snapshots__/Select.test.tsx.snap
  src/components/SocialMediaLinks/SocialMediaLinks.test.tsx
  src/components/SocialMediaLinks/__snapshots__/SocialMediaLinks.test.tsx.snap
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/TextInput.stories.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/textInputChangelogData.ts
  src/hooks/__tests__/useNYPLTheme.test.tsx
Labels: Release

#1711 DSD-1884: new template component
  CHANGELOG.md
  package-lock.json
  src/components/Template/Template.mdx
  src/components/Template/Template.stories.tsx
  src/components/Template/Template.test.tsx
  src/components/Template/Template.tsx
  src/components/Template/__snapshots__/Template.test.tsx.snap
  src/components/Template/templateChangelogData.ts
  src/hooks/__tests__/useNYPLTheme.test.tsx
  src/index.ts
  src/theme/components/global.ts
  src/theme/components/template.ts
  src/utils/utils.ts
Labels: Needs Review, DON’T MERGE YET, v4
