Repository NYPL/nypl-design-system, pull requests merged in 2024-02, with the labels that each got.

#1510 DSD-1632: QA fix - update padding to fix focus outline
  src/theme/components/tabs.ts
Labels: Ship It

#1500 DSD-1669: responsive font sizes for Heading and Text components (React 17 / Chakra 1)
  CHANGELOG.md
  package-lock.json
  src/components/AlphabetFilter/__snapshots__/AlphabetFilter.test.tsx.snap
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/ComponentWrapper/__snapshots__/ComponentWrapper.test.tsx.snap
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.tsx
  src/components/Heading/__snapshots__/Heading.test.tsx.snap
  src/components/Heading/headingChangelogData.ts
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/List/__snapshots__/List.test.tsx.snap
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/Text/Text.mdx
  src/components/Text/textChangelogData.ts
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
  src/hooks/useNYPLBreakpoints.mdx
  src/theme/components/heading.ts
  src/theme/components/text.ts
Labels: Ship It, DON’T MERGE YET

#1512 DSD-1679: vertical ellipsis icon
  CHANGELOG.md
  icons/svg/navigation-more-vert.svg
  package-lock.json
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconVariables.ts
Labels: Ship It

#1507 DSD-1670: updated UI styles for StatusBadge
  CHANGELOG.md
  package-lock.json
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StatusBadge/StatusBadge.stories.tsx
  src/components/StatusBadge/StatusBadge.test.tsx
  src/components/StatusBadge/StatusBadge.tsx
  src/components/StatusBadge/__snapshots__/StatusBadge.test.tsx.snap
  src/components/StatusBadge/statusBadgeChangelogData.ts
  src/theme/components/statusBadge.ts
  src/theme/foundations/colors.ts
Labels: Ship It

#1509 DSD-1668: Using the useDSHeading hook in the Modal component
  CHANGELOG.md
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/modalChangelogData.ts
Labels: Ship It

#1495 DSD-1669: responsive font sizes for Heading and Text components (React 18 / Chakra 2)
  CHANGELOG.md
  package-lock.json
  src/components/Heading/Heading.tsx
  src/components/Heading/headingChangelogData.ts
  src/components/Text/textChangelogData.ts
  src/theme/components/heading.ts
  src/theme/components/text.ts
Labels: Ship It, DON’T MERGE YET

#1522 DSD-1636: React18 QA fixes for Basic Elements components
  src/components/FeaturedContent/FeaturedContent.stories.tsx
  src/theme/components/link.ts
Labels: Ship It

#1506 DSD-1331: Menu component
  package-lock.json
  src/components/Menu/Menu.mdx
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/Menu.test.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/menuChangelogData.ts
  src/components/Menu/menuTestData.ts
  src/index.ts
  src/theme/components/menu.ts
  src/theme/foundations/colors.ts
  src/theme/index.ts
Labels: Ship It

#1526 DSD-1689: remove warningLow variant from StatusBadge
  src/components/StatusBadge/StatusBadge.stories.tsx
  src/components/StatusBadge/StatusBadge.test.tsx
  src/components/StatusBadge/StatusBadge.tsx
  src/components/StatusBadge/__snapshots__/StatusBadge.test.tsx.snap
  src/theme/components/statusBadge.ts
Labels: Ship It

#1527 DSD-1611: better error message for NewsletterSignup
  CHANGELOG.md
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
Labels: Ship It

#1529 DSD-1693: responsive size bug for heading5
  CHANGELOG.md
  package-lock.json
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/theme/components/heading.ts
Labels: Ship It

#1523 DSD-1690: color manager export
  package-lock.json
  src/index.ts
Labels: Ship It

#1530 DSD-1696: lightbulb icon
  CHANGELOG.md
  icons/svg/action-lightbulb.svg
  package-lock.json
  src/components/Banner/Banner.test.tsx
  src/components/Banner/Banner.tsx
  src/components/Banner/__snapshots__/Banner.test.tsx.snap
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
Labels: Needs Review

#1528 DSD-1688: Updates StatusBadge styles and Storybook docs
  CHANGELOG.md
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StatusBadge/StatusBadge.stories.tsx
  src/components/StatusBadge/statusBadgeChangelogData.ts
  src/theme/components/statusBadge.ts
Labels: Ship It

#1524 Updates to MultiSelect PR #5121
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectItemsCountButton.tsx
  src/theme/components/multiSelect.ts
Labels: Ship It

#1531 Prep for Release v2.1.6
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/Notification/Notification.mdx
  src/components/Notification/notificationChangelogData.ts
  src/components/StatusBadge/StatusBadge.mdx
  src/components/StatusBadge/statusBadgeChangelogData.ts
Labels: Release

#1535 DSD-1701: Storybook preview sizes
  .storybook/preview.tsx
  CHANGELOG.md
Labels: Ship It

#1543 DSD-1704: responsive styles for FeaturedContent image
  CHANGELOG.md
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/theme/components/featuredContent.ts
Labels: Ship It

#1542 DSD-1705: remove legacy media queries in Heading
  src/theme/components/heading.ts
Labels: Ship It

#1540 DSD-1331: Menu QA colors fix
  src/components/Menu/Menu.mdx
  src/components/Menu/Menu.stories.tsx
  src/theme/components/menu.ts
Labels: Ship It

#1544 DSD-1706: remove NLS and SML component
  CHANGELOG.md
  src/components/NewsletterSignup/NewsletterSignup.mdx.temp-remove
  src/components/NewsletterSignup/NewsletterSignup.stories.tsx.temp-remove
  src/components/SocialMediaLinks/SocialMediaLinks.mdx.temp-remove
  src/components/SocialMediaLinks/SocialMediaLinks.stories.tsx.temp-remove
  src/index.ts
Labels: Ship It
