Repository NYPL/nypl-design-system, pull requests merged in 2024-05, with the labels that each got.

#1586 DSD-1764: Extending Heading prop interface
  CHANGELOG.md
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.test.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/headingChangelogData.ts
Labels: Ship It

#1590 DSD-1773 and DSD-1774: adding id as prop
  CHANGELOG.md
  src/components/Card/Card.mdx
  src/components/Card/Card.test.tsx
  src/components/Card/Card.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Card/cardChangelogData.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Hero/heroChangelogData.ts
  src/components/HorizontalRule/HorizontalRule.mdx
  src/components/HorizontalRule/HorizontalRule.test.tsx
  src/components/HorizontalRule/HorizontalRule.tsx
  src/components/HorizontalRule/horizontalRuleChangelogData.ts
  src/components/SkeletonLoader/SkeletonLoader.mdx
  src/components/SkeletonLoader/SkeletonLoader.test.tsx
  src/components/SkeletonLoader/SkeletonLoader.tsx
  src/components/SkeletonLoader/skeletonLoaderChangelogData.ts
  src/components/Template/Template.mdx
  src/components/Template/Template.test.tsx
  src/components/Template/Template.tsx
  src/components/Template/templateChangelogData.ts
  src/components/Text/Text.mdx
  src/components/Text/Text.test.tsx
  src/components/Text/Text.tsx
  src/components/Text/__snapshots__/Text.test.tsx.snap
  src/components/Text/textChangelogData.ts
Labels: Needs Review

#1592 Prep for release v3.1.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/Card.mdx
  src/components/Card/cardChangelogData.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/heroChangelogData.ts
  src/components/HorizontalRule/HorizontalRule.mdx
  src/components/HorizontalRule/horizontalRuleChangelogData.ts
  src/components/SkeletonLoader/SkeletonLoader.mdx
  src/components/SkeletonLoader/skeletonLoaderChangelogData.ts
  src/components/Table/Table.mdx
  src/components/Table/tableChangelogData.ts
  src/components/Template/Template.mdx
  src/components/Template/templateChangelogData.ts
  src/components/Text/Text.mdx
  src/components/Text/textChangelogData.ts
Labels: Ship It, Release

#1593 Release 3.1.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/Card.mdx
  src/components/Card/Card.test.tsx
  src/components/Card/Card.tsx
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/Card/cardChangelogData.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.test.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/headingChangelogData.ts
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Hero/heroChangelogData.ts
  src/components/HorizontalRule/HorizontalRule.mdx
  src/components/HorizontalRule/HorizontalRule.test.tsx
  src/components/HorizontalRule/HorizontalRule.tsx
  src/components/HorizontalRule/horizontalRuleChangelogData.ts
  src/components/SkeletonLoader/SkeletonLoader.mdx
  src/components/SkeletonLoader/SkeletonLoader.test.tsx
  src/components/SkeletonLoader/SkeletonLoader.tsx
  src/components/SkeletonLoader/skeletonLoaderChangelogData.ts
  src/components/Table/Table.mdx
  src/components/Table/Table.test.tsx
  src/components/Table/Table.tsx
  src/components/Table/__snapshots__/Table.test.tsx.snap
  src/components/Table/tableChangelogData.ts
  src/components/Template/Template.mdx
  src/components/Template/Template.test.tsx
  src/components/Template/Template.tsx
  src/components/Template/templateChangelogData.ts
  src/components/Text/Text.mdx
  src/components/Text/Text.test.tsx
  src/components/Text/Text.tsx
  src/components/Text/__snapshots__/Text.test.tsx.snap
  src/components/Text/textChangelogData.ts
Labels: Ship It, Release

#1587 DSD-1762: Modal variant
  package-lock.json
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/modalChangelogData.ts
Labels: Ship It

#1599 DSD-1777: Fixing the desktop styling flicker in ButtonGroup
  CHANGELOG.md
  src/components/ButtonGroup/ButtonGroup.mdx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/ButtonGroup/buttonGroupChangelogData.ts
  src/theme/components/buttonGroup.ts
Labels: Ship It

#1600 Prep for release v3.1.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/ButtonGroup/ButtonGroup.mdx
  src/components/ButtonGroup/buttonGroupChangelogData.ts
  src/components/Modal/Modal.mdx
  src/components/Modal/modalChangelogData.ts
  src/index.ts
Labels: Ship It, Release

#1602 Release 3.1.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/ButtonGroup/ButtonGroup.mdx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/ButtonGroup/buttonGroupChangelogData.ts
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/modalChangelogData.ts
  src/index.ts
  src/theme/components/buttonGroup.ts
Labels: Ship It, Release

#1601 DSD-1742: Fixing z-index issue on MultiSelect selected items count button
  CHANGELOG.md
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectItemsCountButton.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/theme/components/multiSelect.ts
Labels: Ship It

#1603 DSD-1741: Fixing checkbox's positioning so it is visible when focused
  CHANGELOG.md
  package-lock.json
  src/components/Checkbox/Checkbox.mdx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/Checkbox/checkboxChangelogData.ts
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/theme/components/checkbox.ts
Labels: Ship It

#1596 DSD-1565: Fixing a breadcrumbs test to have the appropriate type
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
Labels: Ship It

#1595 DSd-1735: Exporting helper chakra functions
  CHANGELOG.md
  src/index.ts
Labels: Ship It

#1604 DSD-1775/add esc func to accordion
  CHANGELOG.md
  src/components/Accordion/Accordion.mdx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Accordion/accordionChangelogData.ts
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
Labels: Ship It

#1594 DSD-1582: better association between the SearchBar's helper text and input element
  CHANGELOG.md
  package-lock.json
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/textInputChangelogData.ts
Labels: Needs Review, x2

#1606 Bug fix: zindex click issue on MultiSelect count button
  src/theme/components/multiSelectItemsCountButton.ts
Labels: Ship It

#1598 DSD-1729: Adding showRowDividers prop to hide List description list dividers
  CHANGELOG.md
  package-lock.json
  src/components/List/List.mdx
  src/components/List/List.stories.tsx
  src/components/List/List.test.tsx
  src/components/List/List.tsx
  src/components/List/__snapshots__/List.test.tsx.snap
  src/components/List/listChangelogData.ts
  src/theme/components/list.ts
  src/theme/components/structuredContent.ts
Labels: Ship It

#1609 Prep for Release v3.1.4
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Accordion/Accordion.mdx
  src/components/Accordion/accordionChangelogData.ts
  src/components/Checkbox/Checkbox.mdx
  src/components/Checkbox/checkboxChangelogData.ts
  src/components/List/List.mdx
  src/components/List/listChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/textInputChangelogData.ts
Labels: Ship It, Release
