Repository NYPL/nypl-design-system, pull requests merged in 2024-07, with the labels that each got.

#1634 Prep for Release v3.1.7
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/components/CheckboxGroup/CheckboxGroup.mdx
  src/components/CheckboxGroup/checkboxGroupChangelogData.ts
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/MultiSelectGroup/multiSelectGroupChangelogData.ts
  src/components/Slider/Slider.mdx
  src/components/Slider/sliderChangelogData.ts
Labels: Ship It, Release

#1635 Release v3.1.7
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Accordion/Accordion.mdx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/accordionChangelogData.ts
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/components/CheckboxGroup/CheckboxGroup.mdx
  src/components/CheckboxGroup/CheckboxGroup.stories.tsx
  src/components/CheckboxGroup/checkboxGroupChangelogData.ts
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.stories.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/MultiSelectItemsCountButton.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/MultiSelectGroup/multiSelectGroupChangelogData.ts
  src/components/Slider/Slider.mdx
  src/components/Slider/Slider.stories.tsx
  src/components/Slider/sliderChangelogData.ts
  src/theme/components/breadcrumb.ts
  src/theme/foundations/typography.ts
Labels: Ship It, Release

#1608 DSD-1770: FilterBarInline Component
  CHANGELOG.md
  src/components/FilterBarInline/FilterBarInline.mdx
  src/components/FilterBarInline/FilterBarInline.stories.tsx
  src/components/FilterBarInline/FilterBarInline.test.tsx
  src/components/FilterBarInline/FilterBarInline.tsx
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/FilterBarInline/filterBarInlineChangelogData.ts
Labels: Ship It

#1613 Reno 3904/update newsletter signup component
  CHANGELOG.md
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/NewsletterSignup.stories.tsx
  src/components/NewsletterSignup/NewsletterSignup.test.tsx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/NewsletterSignup/NewsletterSignupResponse.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/theme/components/newsletterSignup.ts
Labels: Ship It

#1631 Storybook version bump
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Button/Button.stories.tsx
  src/components/ButtonGroup/ButtonGroup.stories.tsx
  src/components/Card/Card.stories.tsx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/CheckboxGroup/CheckboxGroup.stories.tsx
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/FeaturedContent/FeaturedContent.stories.tsx
  src/components/FeedbackBox/FeedbackBox.stories.tsx
  src/components/Fieldset/Fieldset.stories.tsx
  src/components/Heading/Heading.stories.tsx
  src/components/HelperErrorText/HelperErrorText.stories.tsx
  src/components/Icons/Icon.stories.tsx
  src/components/Link/Link.stories.tsx
  src/components/List/List.stories.tsx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelectGroup/MultiSelectGroup.stories.tsx
  src/components/Notification/Notification.stories.tsx
  src/components/Pagination/Pagination.stories.tsx
  src/components/ProgressIndicator/ProgressIndicator.stories.tsx
  src/components/Radio/Radio.stories.tsx
  src/components/RadioGroup/RadioGroup.stories.tsx
  src/components/Select/Select.stories.tsx
  src/components/Slider/Slider.stories.tsx
  src/components/SocialMediaLinks/SocialMediaLinks.stories.tsx
  src/components/Tabs/Tabs.stories.tsx
  src/components/Template/Template.stories.tsx
  src/components/TextInput/TextInput.stories.tsx
  src/components/VideoPlayer/VideoPlayer.stories.tsx
  src/helpers/storybookUtils.ts
Labels: Ship It

#1632 Documentation updates and exporting types and prop interfaces.
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE
  CHAKRA_MIGRATION_GUIDE.md
  README.md
  src/components/AccessibilityGuide/Errors.mdx
  src/components/AccessibilityGuide/StickyElements.mdx
  src/components/Banner/Banner.tsx
  src/components/Button/Button.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DevelopmentGuide/DisablingGlobalStyles.mdx
  src/components/FeaturedContent/FeaturedContent.tsx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/Fieldset/Fieldset.tsx
  src/components/FilterBarInline/FilterBarInline.tsx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/Label/Label.tsx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/SkipNavigation/SkipNavigation.tsx
  src/components/StyledList/StyledList.tsx
  src/docs/Welcome.mdx
  src/index.ts
Labels: Ship It, DON’T MERGE YET

#1639 Prep for Release v3.2.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Banner/Banner.mdx
  src/components/Banner/bannerChangelogData.ts
  src/components/Button/Button.mdx
  src/components/Button/buttonChangelogData.ts
  src/components/ButtonGroup/ButtonGroup.mdx
  src/components/ButtonGroup/buttonGroupChangelogData.ts
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/FeaturedContent/FeaturedContent.mdx
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/Fieldset/Fieldset.mdx
  src/components/Fieldset/fieldsetChangelogData.ts
  src/components/FilterBarInline/FilterBarInline.mdx
  src/components/FilterBarInline/filterBarInlineChangelogData.ts
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/HelperErrorText/helperErrorTextChangelogData.ts
  src/components/Label/Label.mdx
  src/components/Label/labelChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/components/SkipNavigation/SkipNavigation.mdx
  src/components/SkipNavigation/skipNavigationChangelogData.ts
  src/components/SocialMediaLinks/SocialMediaLinks.mdx
  src/components/SocialMediaLinks/socialMediaLinksChangelogData.ts
  src/components/StyledList/StyledList.mdx
  src/components/StyledList/styledListChangelogData.ts
Labels: Ship It, Release

#1638 DSD-1809: Prop to display selected item as Menu label
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  src/components/Menu/Menu.mdx
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/Menu.test.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/menuChangelogData.ts
Labels: Ship It
