Repository NYPL/nypl-design-system, pull requests merged in 2024-01, with the labels that each got.

#1477 DSD-1657: new icons for LSP
  CHANGELOG.md
  icons/svg/action-delete.svg
  icons/svg/action-home.svg
  icons/svg/action-lock-closed.svg
  icons/svg/action-payment.svg
  icons/svg/communication-call.svg
  icons/svg/communication-chat-bubble.svg
  icons/svg/communication-email.svg
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
Labels: Ship It

#1483 Prep for Release v2.1.4
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/iconChangelogData.ts
Labels: Ship It, Release

#1484 Release v2.1.4
  CHANGELOG.md
  icons/svg/action-delete.svg
  icons/svg/action-home.svg
  icons/svg/action-lock-closed.svg
  icons/svg/action-payment.svg
  icons/svg/communication-call.svg
  icons/svg/communication-chat-bubble.svg
  icons/svg/communication-email.svg
  package-lock.json
  package.json
  src/components/DatePicker/DatePicker.mdx
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/DatePicker/DatePicker.test.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/_DatePicker.scss
  src/components/DatePicker/datePickerChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
Labels: Release

#1478 DSD-1651: Documentation: sticky header accessibility guide
  src/components/AccessibilityGuide/StickyElements.mdx
Labels: Ship It

#1468 React 18/Chakra 2.8 Checkbox update
  .storybook/main.ts
  package-lock.json
  src/components/Checkbox/Checkbox.mdx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/Checkbox/checkboxChangelogData.ts
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/Slider/Slider.mdx
  src/theme/components/checkbox.ts
Labels: Needs Review

#1489 DSD-1639: Updating media & icons components to chakra 2.8
  package-lock.json
  src/components/Accordion/Accordion.tsx
  src/components/AudioPlayer/AudioPlayer.mdx
  src/components/AudioPlayer/AudioPlayer.stories.tsx
  src/components/AudioPlayer/AudioPlayer.tsx
  src/components/AudioPlayer/audioPlayerChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/Icon.stories.tsx
  src/components/Icons/Icon.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Image/imageChangelogData.ts
  src/components/Logo/Logo.mdx
  src/components/Logo/Logo.stories.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/logoChangelogData.ts
  src/components/StyleGuide/ColorCard.tsx
  src/components/VideoPlayer/VideoPlayer.mdx
  src/components/VideoPlayer/VideoPlayer.stories.tsx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/components/VideoPlayer/videoPlayerChangelogData.ts
  src/theme/components/audioPlayer.ts
  src/theme/components/icon.ts
  src/theme/components/image.ts
  src/theme/components/logo.ts
  src/theme/components/videoPlayer.ts
  src/theme/index.ts
Labels: Needs Review

#1494 DSD-1648: Checkbox and global bold fix
  package-lock.json
  src/components/Checkbox/Checkbox.tsx
  src/theme/components/checkbox.ts
  src/theme/foundations/global.ts
Labels: Ship It

#1499 DSD-1644: Fixes from VQA of form elms pt 1
  src/components/DatePicker/_DatePicker.scss
  src/theme/components/checkboxGroup.ts
  src/theme/components/global.ts
Labels: Ship It

#1502 DSD-1673: FeedbackBox form fixes
  CHANGELOG.md
  src/components/FeedbackBox/FeedbackBox.test.tsx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
Labels: Ship It

#1508 DSD-1647: QA fix - minor update to button for consistent height
  package-lock.json
  src/theme/components/button.ts
Labels: Needs Review

#1497 DSD-1632: Tabs left/right scrolling
  CHANGELOG.md
  src/components/Tabs/Tabs.mdx
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/tabsChangelogData.ts
  src/hooks/useScrollTabIntoView.ts
  src/theme/components/tabs.ts
Labels: Ship It

#1501 DSD-1671: Accessibility update for the focus ring style in the FeedbackBox open button
  CHANGELOG.md
  package-lock.json
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.stories.tsx
  src/components/FeedbackBox/FeedbackBox.test.tsx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/theme/components/feedbackBox.ts
Labels: Ship It

#1488 DSD-1666 NYPL Patterns for sticky header
  src/components/AccessibilityGuide/StickyElements.mdx
Labels: Ship It

#1505 DSD-1641: QA fixes on Overlays/Switchers Chakra 2.8
  src/components/Accordion/Accordion.tsx
  src/theme/components/accordion.ts
Labels: Ship It
