Repository NYPL/nypl-design-system, pull requests merged in 2025-05, with the labels that each got.

#1797 DSD-2006: update props with html equiv pt 1
  CHANGELOG.md
  src/components/Accordion/Accordion.mdx
  src/components/Accordion/Accordion.stories.tsx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/accordionChangelogData.ts
  src/components/Banner/Banner.mdx
  src/components/Banner/Banner.stories.tsx
  src/components/Banner/Banner.test.tsx
  src/components/Banner/Banner.tsx
  src/components/Banner/bannerChangelogData.ts
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/HelperErrorText/HelperErrorText.stories.tsx
  src/components/HelperErrorText/HelperErrorText.test.tsx
  src/components/HelperErrorText/HelperErrorText.tsx
  src/components/HelperErrorText/helperErrorTextChangelogData.ts
  src/components/Image/Image.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/Notification/Notification.mdx
  src/components/Notification/Notification.stories.tsx
  src/components/Notification/Notification.test.tsx
  src/components/Notification/Notification.tsx
  src/components/Notification/notificationChangelogData.ts
Labels: Needs Review

#1810 DSD-2036: Removes useNYPLBreakpoints hook where possible
  CHANGELOG.md
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.tsx
  src/components/Modal/modalChangelogData.ts
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/MultiSelectGroup/multiSelectGroupChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Table/Table.mdx
  src/components/Table/Table.tsx
  src/components/Table/tableChangelogData.ts
  src/theme/components/feedbackBox.ts
  src/theme/components/icon.ts
  src/theme/components/searchBar.ts
  src/theme/sharedStyles.ts
Labels: Needs Review, x2

#1807 DSD-1901: Remove `role="search"` from `Searchbar`
  CHANGELOG.md
  src/components/Banner/Banner.mdx
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.test.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/SearchBar/searchBarChangelogData.ts
Labels: Ship It, v4

#1765 DSD-1843: Hero primary refactor
  CHANGELOG.md
  package-lock.json
  src/components/Hero/Hero.mdx
  src/components/Hero/Hero.stories.tsx
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/heroChangelogData.ts
  src/components/Template/Template.stories.tsx
  src/theme/components/hero.ts
Labels: Ship It, v4

#1806 DSD-1900: ARIA landmarks guide
  CHANGELOG.md
  src/components/AccessibilityGuide/AriaLandmarks.mdx
  src/components/SearchBar/SearchBar.stories.tsx
Labels: Ship It

#1803 DSD-2052: Progressive Enhancement Storybook doc
  CHANGELOG.md
  src/components/AccessibilityGuide/ProgressiveEnhancement.mdx
  static/progressive-enhancement.png
Labels: Needs Review, x2

#1819 Release v3.6.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/AccessibilityGuide/AriaLandmarks.mdx
  src/components/AccessibilityGuide/ProgressiveEnhancement.mdx
  src/components/Button/Button.mdx
  src/components/Button/buttonChangelogData.ts
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/FeedbackBox/FeedbackBox.tsx
  src/components/FeedbackBox/feedbackBoxChangelogData.ts
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/Modal/Modal.mdx
  src/components/Modal/Modal.tsx
  src/components/Modal/modalChangelogData.ts
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.tsx
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/MultiSelectGroup/multiSelectGroupChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/SearchBar.stories.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Table/Table.mdx
  src/components/Table/Table.tsx
  src/components/Table/tableChangelogData.ts
  src/components/Tabs/Tabs.mdx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/Tabs/tabsChangelogData.ts
  src/theme/components/button.ts
  src/theme/components/feedbackBox.ts
  src/theme/components/icon.ts
  src/theme/components/searchBar.ts
  src/theme/components/tabs.ts
  src/theme/foundations/typography.ts
  src/theme/sharedStyles.ts
  static/progressive-enhancement.png
Labels: Ship It, Release

#1815 DSD-2048: Removes `isDarkMode`
  CHANGELOG.md
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  src/components/Accordion/accordionChangelogData.ts
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/Icons/Icon.mdx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/Slider/Slider.tsx
  src/components/Slider/sliderChangelogData.ts
  src/theme/components/slider.ts
Labels: Needs Review, x2
