Repository NYPL/nypl-design-system, pull requests merged in 2025-01, with the labels that each got.

#1722 DSD-1978: Fixing image onerror callback function so it doesn't infinite loop
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Card/__snapshots__/Card.test.tsx.snap
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/components/Image/Image.mdx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Image/imageChangelogData.ts
  src/components/StructuredContent/__snapshots__/StructuredContent.test.tsx.snap
  src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: Ship It

#1723 DSD-1895: Removing hard coded aria-label in the Form component
  CHANGELOG.md
  src/components/Form/Form.mdx
  src/components/Form/Form.test.tsx
  src/components/Form/Form.tsx
  src/components/Form/__snapshots__/Form.test.tsx.snap
  src/components/Form/formChangelogData.ts
  src/components/Header/components/HeaderSearchButton.test.tsx
  src/components/Header/components/HeaderSearchForm.test.tsx
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/NewsletterSignup/NewsletterSignup.test.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
Labels: Ship It

#1724 DSD-1896: replacing the fieldset/legend in RadioGroup with a simpler div/span
  CHANGELOG.md
  src/components/Header/components/__snapshots__/HeaderSearchForm.test.tsx.snap
  src/components/RadioGroup/RadioGroup.mdx
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap
  src/components/RadioGroup/radioGroupChangelogData.tsx
  src/theme/components/radioGroup.ts
Labels: Ship It

#1720 DSD-1888: Pagination style updates
  src/components/Pagination/Pagination.mdx
  src/components/Pagination/Pagination.stories.tsx
  src/components/Pagination/Pagination.test.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/components/Pagination/paginationChangelogData.ts
  src/theme/components/pagination.ts
Labels: Ship It

#1712 DSD-1877: Filtering Style Guide
  .storybook/preview.tsx
  CHANGELOG.md
  src/components/StyleGuide/Filtering/Accessibility.mdx
  src/components/StyleGuide/Filtering/ApplyingClearing.mdx
  src/components/StyleGuide/Filtering/JavaScriptDisabled.mdx
  src/components/StyleGuide/Filtering/Overview.mdx
  src/components/StyleGuide/Filtering/PageComposition.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/ActiveFiltersList.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/FilterBar.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/KeywordSearch.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/PaginationMenu.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/ResultsList.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/SortingMenu.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/TotalResultsHeading.mdx
  src/utils/utils.ts
  static/filteringStyleGuide/activeFiltersList.png
  static/filteringStyleGuide/exampleColumn.png
  static/filteringStyleGuide/examplePopup.png
  static/filteringStyleGuide/exampleRow.png
  static/filteringStyleGuide/filterBar.png
  static/filteringStyleGuide/focusClearingFilters.gif
  static/filteringStyleGuide/focusKeywordSearch.gif
  static/filteringStyleGuide/focusLiveFiltering.gif
  static/filteringStyleGuide/focusPagination.gif
  static/filteringStyleGuide/focusSorting.gif
  static/filteringStyleGuide/fullPageExample.png
  static/filteringStyleGuide/keywordSearchField.png
  static/filteringStyleGuide/paginationMenu.png
  static/filteringStyleGuide/resultsList.png
  static/filteringStyleGuide/sortingMenu.png
  static/filteringStyleGuide/totalResultsHeading.png
Labels: Ship It

#1725 Prep for Release v3.5.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Form/Form.mdx
  src/components/Form/formChangelogData.ts
  src/components/Image/Image.mdx
  src/components/Image/imageChangelogData.ts
  src/components/Pagination/Pagination.mdx
  src/components/Pagination/paginationChangelogData.ts
  src/components/RadioGroup/RadioGroup.mdx
  src/components/RadioGroup/radioGroupChangelogData.tsx
Labels: Ship It, Release

#1730 DSD-1991: Pagination numbering fix
  CHANGELOG.md
  src/components/Pagination/Pagination.mdx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/paginationChangelogData.ts
  src/theme/components/pagination.ts
Labels: Ship It

#1727 DSD-1990: Adding breadcrumbs screen reader support
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/theme/components/breadcrumb.ts
Labels: Ship It

#1732 DSD-1993: styles for search input field
  CHANGELOG.md
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/theme/components/multiSelect.ts
Labels: Ship It

#1721 DSD-1905/formatting numbers
  CHANGELOG.md
  src/components/Text/Text.stories.tsx
  src/hooks/__tests__/useFormatNumber.test.ts
  src/hooks/useFormatNumber.mdx
  src/hooks/useFormatNumber.ts
  src/index.ts
Labels: Ship It

#1736 Prep for Release v3.5.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/Pagination/Pagination.mdx
  src/components/Pagination/paginationChangelogData.ts
  src/hooks/useFormatNumber.mdx
Labels: Release

#1738 Release v3.5.3
  .github/workflows/static.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/Pagination/Pagination.mdx
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/paginationChangelogData.ts
  src/components/Text/Text.stories.tsx
  src/hooks/__tests__/useFormatNumber.test.ts
  src/hooks/useFormatNumber.mdx
  src/hooks/useFormatNumber.ts
  src/index.ts
  src/theme/components/breadcrumb.ts
  src/theme/components/heading.ts
  src/theme/components/multiSelect.ts
  src/theme/components/pagination.ts
Labels: Release

#1565 Breakpoints Feature Branch
  .storybook/preview.tsx
  CHANGELOG.md
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/Select/Select.mdx
  src/components/StyleGuide/Breakpoints.mdx
  src/hooks/__tests__/useNYPLBreakpoints.test.ts
  src/hooks/useNYPLBreakpoints.mdx
  src/hooks/useNYPLBreakpoints.stories.tsx
  src/hooks/useNYPLBreakpoints.ts
  src/styles/_01-breakpoints.scss
  src/theme/foundations/breakpoints.ts
Labels: Ship It, v4
