Repository NYPL/nypl-design-system, pull requests merged in 2025-03, with the labels that each got.

#1757 NO-REF: Fix Card styles from container queries update
  src/theme/components/card.ts
Labels: no-changelog

#1756 DSD-1931: font weight for RadioGroup
  src/theme/components/global.ts
Labels: Needs Review

#1755 DSD-1940: Modal spacing
  CHANGELOG.md
  src/components/Modal/Modal.mdx
  src/components/Modal/modalChangelogData.ts
  src/theme/components/modal.ts
Labels: Ship It

#1758 DSD-1929: `Image` new aspect ratio options
  CHANGELOG.md
  src/components/Image/Image.mdx
  src/components/Image/Image.stories.tsx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/__snapshots__/Image.test.tsx.snap
  src/components/Image/imageChangelogData.ts
  src/theme/components/image.ts
Labels: Ship It

#1759 DSD-2012: `TagSetFilter` button wrapper
  CHANGELOG.md
  src/components/TagSet/TagSet.mdx
  src/components/TagSet/TagSet.stories.tsx
  src/components/TagSet/TagSet.test.tsx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/components/TagSet/tagSetChangelogData.ts
Labels: Ship It, x2

#1747 DSD-2000: Storybook font styles
  .storybook/preview-body.html
  CHANGELOG.md
  src/components/Banner/Banner.mdx
Labels: Ship It

#1760 DSD-2011: primitive and highlighter colors
  .storybook/preview-body.html
  CHANGELOG.md
  src/components/AccessibilityGuide/HighlightingText.mdx
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/StyleGuide/ColorCard.tsx
  src/components/StyleGuide/Colors.mdx
  src/theme/foundations/colors.ts
Labels: Ship It

#1762 Prep for Release v3.5.5
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Banner/Banner.mdx
  src/components/Banner/bannerChangelogData.ts
  src/components/Card/Card.mdx
  src/components/Card/cardChangelogData.ts
  src/components/FeaturedContent/FeaturedContent.mdx
  src/components/FeaturedContent/featuredContentChangelogData.ts
  src/components/Fieldset/Fieldset.mdx
  src/components/Fieldset/fieldsetChangelogData.ts
  src/components/Image/Image.mdx
  src/components/Image/imageChangelogData.ts
  src/components/Label/Label.mdx
  src/components/Label/labelChangelogData.ts
  src/components/Modal/Modal.mdx
  src/components/Modal/modalChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/TagSet/TagSet.mdx
  src/components/TagSet/tagSetChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/textInputChangelogData.ts
Labels: Ship It, Release

#1768 DSD-2007: replacing errors thrown with console.warn
  CHANGELOG.md
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/breadcrumbsChangelogData.ts
  src/components/Heading/Heading.mdx
  src/components/Heading/Heading.test.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/headingChangelogData.ts
  src/components/Image/Image.mdx
  src/components/Image/Image.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/imageChangelogData.ts
  src/components/Template/Template.mdx
Labels: Ship It

#1769 DSD-1946: ProgressIndicator label margin updates
  CHANGELOG.md
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/ProgressIndicator/ProgressIndicator.tsx
  src/components/ProgressIndicator/__snapshots__/ProgressIndicator.test.tsx.snap
  src/components/ProgressIndicator/progressIndicatorChangelogData.ts
  src/theme/components/progressIndicator.ts
Labels: Ship It
