Repository NYPL/nypl-design-system, pull requests merged in 2025-04, with the labels that each got.

#1772 DSD-2024: added new arrow icons
  CHANGELOG.md
  icons/svg/navigation-subdirectory-arrow-left.svg
  icons/svg/navigation-subdirectory-arrow-right.svg
  package-lock.json
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
Labels: Ship It

#1764 DSD-2014: Adding autoComplete and requiredLabelText props to Select
  CHANGELOG.md
  src/components/Select/Select.mdx
  src/components/Select/Select.stories.tsx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Select/selectChangelogData.ts
  src/components/TextInput/TextInput.stories.tsx
  src/components/TextInput/TextInput.tsx
  src/index.ts
  src/utils/constantValues.ts
Labels: Needs Review

#1776 DSD-2027: TagSet overflow bug
  CHANGELOG.md
  src/components/TagSet/TagSet.mdx
  src/components/TagSet/TagSet.stories.tsx
  src/components/TagSet/TagSetFilter.tsx
  src/components/TagSet/tagSetChangelogData.ts
Labels: Ship It

#1770 DSD-2022: update default font weight
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/StyleGuide/Typography.mdx
  src/theme/components/fieldset.ts
  src/theme/components/global.ts
  src/theme/components/label.ts
  src/theme/components/menu.ts
  src/theme/foundations/typography.ts
Labels: Ship It

#1779 DSD-1951: updates how labelPosition renders in storybook for Select
  CHANGELOG.md
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/Select/Select.stories.tsx
  src/theme/components/select.ts
Labels: Ship It

#1780 DSD-1956: adds more info to X socialMediaLink example
  src/components/SocialMediaLinks/SocialMediaLinks.stories.tsx
Labels: Ship It

#1778 DSD-1943: Updating newsletterSignup with vdl updates
  CHANGELOG.md
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/NewsletterSignup.tsx
  src/components/NewsletterSignup/__snapshots__/NewsletterSignup.test.tsx.snap
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/theme/components/newsletterSignup.ts
Labels: Ship It

#1767 DSD-1970/1971: TextInput updates to sync with VDL
  CHANGELOG.md
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/TextInput.stories.tsx
  src/components/TextInput/TextInput.test.tsx
  src/components/TextInput/TextInput.tsx
  src/components/TextInput/textInputChangelogData.ts
  src/theme/components/textInput.ts
Labels: Ship It

#1775 DSD-1916: `Button` height sync with VDL
  CHANGELOG.md
  src/components/Button/Button.mdx
  src/components/Button/buttonChangelogData.ts
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/hooks/__tests__/useNYPLTheme.test.tsx
  src/hooks/useNYPLTheme.ts
  src/theme/components/button.ts
  src/theme/foundations/sizes.ts
  src/theme/index.ts
Labels: Ship It

#1784 DSD-1941: Fix `Multiselect` search field to remain visible on scroll
  CHANGELOG.md
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/theme/components/multiSelect.ts
Labels: Ship It

#1786 Prep for Release v3.6.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Button/Button.mdx
  src/components/Button/buttonChangelogData.ts
  src/components/Checkbox/Checkbox.mdx
  src/components/Checkbox/checkboxChangelogData.ts
  src/components/Icons/Icon.mdx
  src/components/Icons/iconChangelogData.ts
  src/components/List/List.mdx
  src/components/List/listChangelogData.ts
  src/components/Menu/Menu.mdx
  src/components/Menu/menuChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/NewsletterSignup/newsletterSignupChangelogData.ts
  src/components/Notification/Notification.mdx
  src/components/Notification/notificationChangelogData.ts
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/ProgressIndicator/progressIndicatorChangelogData.ts
  src/components/Radio/Radio.mdx
  src/components/Radio/radioChangelogData.ts
  src/components/Select/Select.mdx
  src/components/Select/selectChangelogData.ts
  src/components/TagSet/TagSet.mdx
  src/components/TagSet/tagSetChangelogData.ts
  src/components/TextInput/TextInput.mdx
  src/components/TextInput/textInputChangelogData.ts
  src/docs/Welcome.mdx
Labels: Ship It, Release

#1789 DSD-1953: SkeletonLoader style fix
  CHANGELOG.md
  src/components/SkeletonLoader/SkeletonLoader.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.tsx
  src/components/SkeletonLoader/SkeletonLoader.tsx
  src/components/SkeletonLoader/__snapshots__/SkeletonLoader.test.tsx.snap
  src/components/SkeletonLoader/skeletonLoaderChangelogData.ts
  src/theme/components/skeletonLoader.ts
Labels: Ship It

#1790 DSD-1974: `Tooltip` text color update
  CHANGELOG.md
  src/components/Tooltip/Tooltip.mdx
  src/components/Tooltip/tooltipChangelogData.ts
  src/theme/components/tooltip.ts
Labels: Ship It

#1791 DSD-2025: `Notification` color update
  CHANGELOG.md
  src/components/Notification/Notification.mdx
  src/components/Notification/Notification.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/Notification/notificationChangelogData.ts
  src/theme/components/notificationContent.ts
  src/theme/components/notificationHeading.ts
Labels: Ship It

#1794 DSD-1964: Tabs border color
  CHANGELOG.md
  src/components/Tabs/Tabs.mdx
  src/components/Tabs/tabsChangelogData.ts
  src/theme/components/tabs.ts
Labels: Ship It

#1793 DSD-1962: SubNav dark mode styles
  CHANGELOG.md
  src/components/SubNav/SubNav.stories.tsx
  src/components/SubNav/subNavChangelogData.ts
  src/theme/components/subnav.ts
Labels: Ship It

#1777 DSD-2013: Multiselect visibility of item count zero
  CHANGELOG.md
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/Select/selectChangelogData.ts
Labels: Ship It

#1792 DSD-2032: heading font weight
  CHANGELOG.md
  src/components/AccessibilityGuide/HighlightingText.mdx
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/StyleGuide/Typography.mdx
  src/theme/components/heading.ts
  src/theme/foundations/typography.ts
Labels: Ship It, DON’T MERGE YET

#1796 DSD-1975: docs for Tooltip
  CHANGELOG.md
  package-lock.json
  src/components/Tooltip/Tooltip.mdx
  src/components/Tooltip/Tooltip.stories.tsx
Labels: Ship It

#1795 DSD-1965: docs for Tabs
  CHANGELOG.md
  src/components/Tabs/Tabs.mdx
Labels: Ship It

#1800 Release v3.6.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/AccessibilityGuide/HighlightingText.mdx
  src/components/DevelopmentGuide/DesignTokens.mdx
  src/components/Heading/Heading.mdx
  src/components/Heading/headingChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.test.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/Notification/Notification.mdx
  src/components/Notification/Notification.tsx
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/Notification/notificationChangelogData.ts
  src/components/SearchBar/SearchBar.mdx
  src/components/SearchBar/searchBarChangelogData.ts
  src/components/Select/selectChangelogData.ts
  src/components/SkeletonLoader/SkeletonLoader.mdx
  src/components/SkeletonLoader/SkeletonLoader.stories.tsx
  src/components/SkeletonLoader/SkeletonLoader.tsx
  src/components/SkeletonLoader/__snapshots__/SkeletonLoader.test.tsx.snap
  src/components/SkeletonLoader/skeletonLoaderChangelogData.ts
  src/components/StyleGuide/Typography.mdx
  src/components/SubNav/SubNav.mdx
  src/components/SubNav/SubNav.stories.tsx
  src/components/SubNav/subNavChangelogData.ts
  src/components/Tabs/Tabs.mdx
  src/components/Tabs/tabsChangelogData.ts
  src/components/Tooltip/Tooltip.mdx
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/tooltipChangelogData.ts
  src/theme/components/heading.ts
  src/theme/components/notificationContent.ts
  src/theme/components/notificationHeading.ts
  src/theme/components/searchBar.ts
  src/theme/components/skeletonLoader.ts
  src/theme/components/subnav.ts
  src/theme/components/tabs.ts
  src/theme/components/tooltip.ts
  src/theme/foundations/typography.ts
Labels: Release

#1804 DSD-2058: Updating Storybook to v8.6.12
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Ship It
