Repository NYPL/nypl-design-system, pull requests merged in 2025-07, with the labels that each got.

#1855 DSD-2041/remove children map
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Banner/__snapshots__/Banner.test.tsx.snap
  src/components/Button/Button.mdx
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/Button/buttonChangelogData.ts
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/ButtonGroupContext.tsx
  src/components/ButtonGroup/buttonGroupChangelogData.ts
  src/components/Card/Card.tsx
  src/components/Card/cardChangelogData.ts
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/checkboxChangelogData.ts
  src/components/CheckboxGroup/CheckboxGroup.tsx
  src/components/CheckboxGroup/CheckboxGroupContext.tsx
  src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap
  src/components/CheckboxGroup/checkboxGroupChangelogData.ts
  src/components/FilterBarInline/__snapshots__/FilterBarInline.test.tsx.snap
  src/components/List/List.test.tsx
  src/components/List/List.tsx
  src/components/List/listChangelogData.ts
  src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  src/components/MultiSelectGroup/__snapshots__/MultiSelectGroup.test.tsx.snap
  src/components/Notification/__snapshots__/Notification.test.tsx.snap
  src/components/Radio/Radio.tsx
  src/components/Radio/radioChangelogData.ts
  src/components/RadioGroup/RadioGroup.test.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupContext.tsx
  src/components/RadioGroup/radioGroupChangelogData.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/StyledList/StyledList.test.tsx
  src/components/StyledList/StyledList.tsx
  src/components/StyledList/styledListChangelogData.ts
  src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  src/components/TagSet/__snapshots__/TagSet.test.tsx.snap
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/tooltipChangelogData.ts
  src/theme/components/button.ts
Labels: Needs Review, x2

#1858 DSD-2099: story headers for Hooks category
  src/hooks/useCarouselStyles.mdx
  src/hooks/useCloseDropDown.mdx
  src/hooks/useFormatNumber.mdx
  src/hooks/useMultiSelect.mdx
  src/hooks/useNYPLBreakpoints.mdx
  src/hooks/useNYPLTheme.mdx
  src/hooks/useResponsiveSpacing.mdx
  src/hooks/useScrollFadeStyles.mdx
  src/hooks/useWindowSize.mdx
Labels: Ship It, v4

#1857 DSD-2097: props bug in Heading
  src/components/FeaturedContent/__snapshots__/FeaturedContent.test.tsx.snap
  src/components/Heading/Heading.stories.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/__snapshots__/Heading.test.tsx.snap
Labels: Ship It, v4

#1860 DSD-2101: Style Guide story headers
  src/components/DevelopmentGuide/ContainerQuery.mdx
  src/components/StyleGuide/Bidirectionality.mdx
  src/components/StyleGuide/Breakpoints.mdx
  src/components/StyleGuide/Buttons.mdx
  src/components/StyleGuide/Colors.mdx
  src/components/StyleGuide/Filtering/Accessibility.mdx
  src/components/StyleGuide/Filtering/ApplyingClearing.mdx
  src/components/StyleGuide/Filtering/JavaScriptDisabled.mdx
  src/components/StyleGuide/Filtering/Overview.mdx
  src/components/StyleGuide/Filtering/PageComposition.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/ActiveFiltersList.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/FilterBar.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/KeywordSearch.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/PaginationMenu.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/ResultsList.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/SortingMenu.mdx
  src/components/StyleGuide/Filtering/PageCompositionElements/TotalResultsHeading.mdx
  src/components/StyleGuide/Forms.mdx
  src/components/StyleGuide/Iconography.mdx
  src/components/StyleGuide/ResponsiveGrid.mdx
  src/components/StyleGuide/Spacing.mdx
  src/components/StyleGuide/Typography.mdx
Labels: Ship It

#1862 DSD-2090: Removing FilterBar and useFilterBar hook
  CHANGELOG.md
  src/components/FilterBar/FilterBar.md
  src/components/FilterBar/FilterBar.stories-temp-remove.tsx
  src/components/FilterBar/FilterBar.test.tsx
  src/components/FilterBar/FilterBar.tsx
  src/components/FilterBar/__snapshots__/FilterBar.test.tsx.snap
  src/components/FilterBarInline/FilterBarInline.mdx
  src/components/FilterBarInline/FilterBarInline.stories.tsx
  src/components/FilterBarPopup/FilterBarPopup.mdx
  src/components/FilterBarPopup/FilterBarPopup.stories.tsx
  src/components/MultiSelect/MultiSelect.mdx
  src/hooks/__tests__/useFilterBar.test.ts
  src/hooks/useFilterBar.md
  src/hooks/useFilterBar.ts
  src/theme/components/filterBar.ts
  src/theme/index.ts
Labels: Needs Review, v4

#1864 DSD-2103: Remove child validation warnings
  CHANGELOG.md
  src/components/ComponentWrapper/ComponentWrapper.tsx
  src/components/Form/Form.test.tsx
  src/components/Form/Form.tsx
  src/components/Form/formChangelogData.ts
  src/components/Heading/Heading.test.tsx
  src/components/Heading/Heading.tsx
  src/components/Heading/headingChangelogData.ts
  src/components/Logo/Logo.test.tsx
  src/components/Logo/Logo.tsx
  src/components/Logo/logoChangelogData.ts
  src/components/SubNav/SubNav.tsx
  src/components/SubNav/subNavChangelogData.ts
  src/components/Text/Text.test.tsx
  src/components/Text/Text.tsx
  src/components/Text/textChangelogData.ts
Labels: Ship It, x2, v4

#1875 Prep for Release v3.6.4
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/AudioPlayer/AudioPlayer.mdx
  src/components/AudioPlayer/audioPlayerChangelogData.ts
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelect/multiSelectChangelogData.ts
  src/components/VideoPlayer/VideoPlayer.mdx
  src/components/VideoPlayer/videoPlayerChangelogData.ts
Labels: Release

#1885 DSD-2132: TemplateBreakout spacing fixes
  src/theme/components/template.ts
Labels: Ship It, v4

#1886 DSD-2134: updated grid element in Hero Primary
  src/components/Hero/Hero.test.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/__snapshots__/Hero.test.tsx.snap
  src/theme/components/hero.ts
Labels: Ship It, v4

#1878 DSD-2092/updates to mig guide
  src/components/DevelopmentGuide/V4MigrationGuide.mdx
Labels: Ship It

#1879 DSD-2114: Updates README for v4
  CHANGELOG.md
  README.md
  public/readme/componentheader.png
Labels: Ship It
