Repository NYPL/nypl-design-system, pull requests merged in 2025-06, with the labels that each got.

#1821 DSD-2044: Removes the need for consuming apps to import mediaMatchMock
  CHANGELOG.md
  src/__tests__/setup.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/components/SearchBar/searchBarChangelogData.ts
  src/hooks/__tests__/useNYPLBreakpoints.test.ts
  src/hooks/useNYPLBreakpoints.mdx
  src/theme/components/searchBar.ts
Labels: Ship It

#1829 Prep for Release v3.6.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/Icons/Icon.mdx
  src/components/Icons/iconChangelogData.ts
Labels: Ship It, Release

#1830 Release v3.6.3
  CHANGELOG.md
  icons/svg/action-info.svg
  icons/svg/action-list.svg
  icons/svg/navigation-apps.svg
  package-lock.json
  package.json
  src/components/Icons/Icon.mdx
  src/components/Icons/IconSvgs.tsx
  src/components/Icons/iconChangelogData.ts
  src/components/Icons/iconVariables.ts
Labels: Ship It, Release

#1826 DSD-2043: update tableTextSize
  CHANGELOG.md
  src/components/Table/Table.tsx
  src/components/Table/tableChangelogData.ts
  src/theme/components/table.ts
Labels: Needs Review

#1828 DSD-2045: Reimplementing the Tab's component use of mobile panel scrolling
  CHANGELOG.md
  src/components/Tabs/Tabs.mdx
  src/components/Tabs/Tabs.test.tsx
  src/components/Tabs/tabsChangelogData.ts
  src/hooks/useScrollTabIntoView.ts
Labels: Needs Review, v4

#1838 DSD-2073: `Multiselect` missing key bug
  CHANGELOG.md
  src/components/MultiSelect/MultiSelect.tsx
  src/components/MultiSelect/multiSelectChangelogData.ts
Labels: Ship It

#1840 DSD-2074: Story headers for Basic Elements
  src/components/FeaturedContent/FeaturedContent.mdx
Labels: Ship It, v4

#1843 DSD-2083: updated story headers for Typography & Styles
  src/components/Heading/Heading.mdx
  src/components/List/List.mdx
  src/components/StyledList/StyledList.mdx
  src/components/Text/Text.mdx
Labels: Ship It, v4

#1841 DSD-2076: Story headers for Content Display
  src/components/HelperErrorText/HelperErrorText.mdx
  src/components/StatusBadge/StatusBadge.mdx
  src/components/TagSet/TagSet.mdx
Labels: Ship It, v4

#1832 DSD-2053 & DSD-2054: Add JavaScript disabled fallback warning to AudioPlayer and VideoPlayer
  CHANGELOG.md
  src/components/AudioPlayer/AudioPlayer.mdx
  src/components/AudioPlayer/AudioPlayer.tsx
  src/components/AudioPlayer/__snapshots__/AudioPlayer.test.tsx.snap
  src/components/AudioPlayer/audioPlayerChangelogData.ts
  src/components/VideoPlayer/VideoPlayer.mdx
  src/components/VideoPlayer/VideoPlayer.tsx
  src/components/VideoPlayer/__snapshots__/VideoPlayer.test.tsx.snap
  src/components/VideoPlayer/videoPlayerChangelogData.ts
Labels: Ship It

#1846 DSD-2082: story headers for Page Layout components
  src/components/Grid/SimpleGrid.mdx
  src/components/HorizontalRule/HorizontalRule.mdx
  src/components/StructuredContent/StructuredContent.mdx
  src/components/Table/Table.mdx
  src/components/Template/Template.mdx
Labels: Ship It, v4

#1844 DSD-2078: story headers for Forms Elements
  src/components/Button/Button.mdx
  src/components/ButtonGroup/ButtonGroup.mdx
  src/components/Checkbox/Checkbox.mdx
  src/components/CheckboxGroup/CheckboxGroup.mdx
  src/components/DatePicker/DatePicker.mdx
  src/components/FeedbackBox/FeedbackBox.mdx
  src/components/Fieldset/Fieldset.mdx
  src/components/FilterBarInline/FilterBarInline.mdx
  src/components/FilterBarPopup/FilterBarPopup.mdx
  src/components/Form/Form.mdx
  src/components/Label/Label.mdx
  src/components/MultiSelect/MultiSelect.mdx
  src/components/MultiSelectGroup/MultiSelectGroup.mdx
  src/components/NewsletterSignup/NewsletterSignup.mdx
  src/components/Radio/Radio.mdx
  src/components/RadioGroup/RadioGroup.mdx
  src/components/SearchBar/SearchBar.mdx
  src/components/Select/Select.mdx
  src/components/Slider/Slider.mdx
  src/components/TextInput/TextInput.mdx
  src/components/Toggle/Toggle.mdx
Labels: Ship It, v4

#1847 DSD-2077: Story headers for Feedback components
  src/components/Notification/Notification.mdx
  src/components/ProgressIndicator/ProgressIndicator.mdx
  src/components/SkeletonLoader/SkeletonLoader.mdx
Labels: Ship It, v4

#1851 DSD-2080: story headers for Navigation component
  src/components/AlphabetFilter/AlphabetFilter.mdx
  src/components/AlphabetFilter/AlphabetFilter.stories.tsx
  src/components/Breadcrumbs/Breadcrumbs.mdx
  src/components/Link/Link.mdx
  src/components/Link/Link.stories.tsx
  src/components/Menu/Menu.mdx
  src/components/Pagination/Pagination.mdx
  src/components/SkipNavigation/SkipNavigation.mdx
  src/components/SocialMediaLinks/SocialMediaLinks.mdx
  src/components/SubNav/SubNav.mdx
Labels: Ship It, v4
